language: c
compiler: clang
before_install:
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then git clone git://github.com/macmade/XSDocgen; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then cd XSDocgen && make && sudo make install && cd ..; fi
before_script: git submodule update --init --recursive
script:
  - make && make example && make test
os:
  - osx
  - linux
