language: c
compiler: clang
before_install:
  - git clone git://github.com/macmade/XSDocgen
  - cd XSDocgen && make && sudo make install && cd ..
before_script: git submodule update --init --recursive
script:
  - make && make example && make test
os:
  - osx
  - linux
