language: objective-c
compiler: clang
script: make && make test && xcodebuild -scheme "XSFoundation - Mac Static Library" test > /dev/null
before_install:
  - git clone git://github.com/macmade/XSDocgen
  - cd XSDocgen && make && sudo make install && cd ..
