language: objective-c
compiler: clang
xcode_project: XSFoundation.xcodeproj
xcode_scheme: Makefile Build
before_install:
  - git clone git://github.com/macmade/XSDocgen
  - cd XSDocgen && make && sudo make install && cd ..
