.TH "__machine.h" 3 "Sun Apr 24 2011" "Version 1.2.2-0" "XSFoundation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
__machine.h \- 
.PP
EOS-SKL (Source Kit Language) architecture private routines.  

.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
EOS-SKL (Source Kit Language) architecture private routines. 

\fBAuthor:\fP
.RS 4
Jean-David Gadina <macmade@eosgarden.com> 
.RE
.PP
\fBVersion:\fP
.RS 4
4.0.0 
.RE
.PP
\fBSince:\fP
.RS 4
2.5.0 
.RE
.PP

.PP
Definition in file \fB__machine.h\fP.
.SH "Author"
.PP 
Generated automatically by Doxygen for XSFoundation from the source code.
