.TH "__XSLock_Struct" 3 "Sun Apr 24 2011" "Version 1.2.2-0" "XSFoundation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
__XSLock_Struct \- 
.PP
XSLock class.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include '__XSLock.h'\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBXSRuntimeClass\fP \fB__class\fP"
.br
.ti -1c
.RI "\fBBOOL\fP \fBlocked\fP"
.br
.ti -1c
.RI "\fBpthread_mutex_t\fP \fBmutex\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
XSLock class. 
.PP
Definition at line 52 of file __XSLock.h.
.SH "Field Documentation"
.PP 
.SS "\fBXSRuntimeClass\fP \fB__XSLock_Struct::__class\fP"
.PP
Definition at line 54 of file __XSLock.h.
.SS "\fBBOOL\fP \fB__XSLock_Struct::locked\fP"... 
.PP
Definition at line 56 of file __XSLock.h.
.SS "\fBpthread_mutex_t\fP \fB__XSLock_Struct::mutex\fP"Runtime class 
.PP
Definition at line 55 of file __XSLock.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for XSFoundation from the source code.
