.TH "__XSApplicationArgument.h" 3 "Sun Apr 24 2011" "Version 1.2.2-0" "XSFoundation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
__XSApplicationArgument.h \- 
.PP
Private XSApplicationArgument class definitions.  

.SH SYNOPSIS
.br
.PP
\fC#include '../XSMacros.h'\fP
.br
\fC#include 'XS.h'\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fB__XSApplicationArgument_Struct\fP"
.br
.RI "\fIXSApplicationArgument class. \fP"
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef struct \fB__XSApplicationArgument_Struct\fP \fB__XSApplicationArgument\fP"
.br
.RI "\fIXSApplicationArgument class type. \fP"
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fB__XSApplicationArgument_Initialize\fP (void)"
.br
.RI "\fIRuntime initialization. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Private XSApplicationArgument class definitions. 

\fBAuthor:\fP
.RS 4
Jean-David Gadina <macmade@eosgarden.com> 
.RE
.PP

.PP
Definition in file \fB__XSApplicationArgument.h\fP.
.SH "Typedef Documentation"
.PP 
.SS "\fB__XSApplicationArgument\fP"
.PP
XSApplicationArgument class type. 
.PP
Definition at line 69 of file __XSApplicationArgument.h.
.SH "Function Documentation"
.PP 
.SS "void __XSApplicationArgument_Initialize (void)"
.PP
Runtime initialization. \fBReturns:\fP
.RS 4
void 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for XSFoundation from the source code.
