.TH "__XSURLRequest_Struct" 3 "Sun Apr 24 2011" "Version 1.2.2-0" "XSFoundation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
__XSURLRequest_Struct \- 
.PP
XSURLRequest class.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include '__XSURLRequest.h'\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBXSRuntimeClass\fP \fB__class\fP"
.br
.ti -1c
.RI "\fBXSData\fP \fBdata\fP"
.br
.ti -1c
.RI "\fBXSDictionary\fP \fBheaders\fP"
.br
.ti -1c
.RI "\fBXSHost\fP \fBhost\fP"
.br
.ti -1c
.RI "\fBXSInteger\fP \fBsocket\fP"
.br
.ti -1c
.RI "\fBBOOL\fP \fBstarted\fP"
.br
.ti -1c
.RI "\fBXSString\fP \fBstatus\fP"
.br
.ti -1c
.RI "\fBXSURL\fP \fBurl\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
XSURLRequest class. 
.PP
Definition at line 52 of file __XSURLRequest.h.
.SH "Field Documentation"
.PP 
.SS "\fBXSRuntimeClass\fP \fB__XSURLRequest_Struct::__class\fP"
.PP
Definition at line 54 of file __XSURLRequest.h.
.SS "\fBXSData\fP \fB__XSURLRequest_Struct::data\fP"... 
.PP
Definition at line 60 of file __XSURLRequest.h.
.SS "\fBXSDictionary\fP \fB__XSURLRequest_Struct::headers\fP"... 
.PP
Definition at line 59 of file __XSURLRequest.h.
.SS "\fBXSHost\fP \fB__XSURLRequest_Struct::host\fP"... 
.PP
Definition at line 56 of file __XSURLRequest.h.
.SS "\fBXSInteger\fP \fB__XSURLRequest_Struct::socket\fP"... 
.PP
Definition at line 57 of file __XSURLRequest.h.
.SS "\fBBOOL\fP \fB__XSURLRequest_Struct::started\fP"... 
.PP
Definition at line 61 of file __XSURLRequest.h.
.SS "\fBXSString\fP \fB__XSURLRequest_Struct::status\fP"... 
.PP
Definition at line 58 of file __XSURLRequest.h.
.SS "\fBXSURL\fP \fB__XSURLRequest_Struct::url\fP"Runtime class 
.PP
Definition at line 55 of file __XSURLRequest.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for XSFoundation from the source code.
