.TH "__XSBool_Struct" 3 "Sun Apr 24 2011" "Version 1.2.2-0" "XSFoundation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
__XSBool_Struct \- 
.PP
XSBool class.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include '__XSBool.h'\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBXSRuntimeClass\fP \fB__class\fP"
.br
.ti -1c
.RI "\fBBOOL\fP \fBvalue\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
XSBool class. 
.PP
Definition at line 52 of file __XSBool.h.
.SH "Field Documentation"
.PP 
.SS "\fBXSRuntimeClass\fP \fB__XSBool_Struct::__class\fP"
.PP
Definition at line 54 of file __XSBool.h.
.SS "\fBBOOL\fP \fB__XSBool_Struct::value\fP"
.PP
Definition at line 55 of file __XSBool.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for XSFoundation from the source code.
