.TH "__XSException_Struct" 3 "Sun Apr 24 2011" "Version 1.2.2-0" "XSFoundation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
__XSException_Struct \- 
.PP
XSException class.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include '__XSException.h'\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBXSRuntimeClass\fP \fB__class\fP"
.br
.ti -1c
.RI "\fBXSInteger\fP \fBcode\fP"
.br
.ti -1c
.RI "\fBXSString\fP \fBreason\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
XSException class. 
.PP
Definition at line 52 of file __XSException.h.
.SH "Field Documentation"
.PP 
.SS "\fBXSRuntimeClass\fP \fB__XSException_Struct::__class\fP"
.PP
Definition at line 54 of file __XSException.h.
.SS "\fBXSInteger\fP \fB__XSException_Struct::code\fP"Runtime class 
.PP
Definition at line 55 of file __XSException.h.
.SS "\fBXSString\fP \fB__XSException_Struct::reason\fP"The exception code 
.PP
Definition at line 56 of file __XSException.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for XSFoundation from the source code.
