.TH "__XSMemoryRecord_Struct" 3 "Sun Apr 24 2011" "Version 1.2.2-0" "XSFoundation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
__XSMemoryRecord_Struct \- 
.PP
...  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include '__XSMemoryDebug.h'\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "const char * \fBallocFile\fP"
.br
.ti -1c
.RI "const char * \fBallocFunc\fP"
.br
.ti -1c
.RI "size_t \fBallocID\fP"
.br
.ti -1c
.RI "int \fBallocLine\fP"
.br
.ti -1c
.RI "\fBXSClassID\fP \fBclassID\fP"
.br
.ti -1c
.RI "\fBBOOL\fP \fBfreed\fP"
.br
.ti -1c
.RI "const char * \fBfreeFile\fP"
.br
.ti -1c
.RI "const char * \fBfreeFunc\fP"
.br
.ti -1c
.RI "int \fBfreeLine\fP"
.br
.ti -1c
.RI "\fBStr255\fP \fBhash\fP"
.br
.ti -1c
.RI "\fB__XSMemoryObject\fP * \fBobject\fP"
.br
.ti -1c
.RI "size_t \fBsize\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
... 
.PP
Definition at line 53 of file __XSMemoryDebug.h.
.SH "Field Documentation"
.PP 
.SS "const char* \fB__XSMemoryRecord_Struct::allocFile\fP"... 
.PP
Definition at line 61 of file __XSMemoryDebug.h.
.SS "const char* \fB__XSMemoryRecord_Struct::allocFunc\fP"... 
.PP
Definition at line 63 of file __XSMemoryDebug.h.
.SS "size_t \fB__XSMemoryRecord_Struct::allocID\fP"... 
.PP
Definition at line 57 of file __XSMemoryDebug.h.
.SS "int \fB__XSMemoryRecord_Struct::allocLine\fP"... 
.PP
Definition at line 62 of file __XSMemoryDebug.h.
.SS "\fBXSClassID\fP \fB__XSMemoryRecord_Struct::classID\fP"... 
.PP
Definition at line 58 of file __XSMemoryDebug.h.
.SS "\fBBOOL\fP \fB__XSMemoryRecord_Struct::freed\fP"... 
.PP
Definition at line 60 of file __XSMemoryDebug.h.
.SS "const char* \fB__XSMemoryRecord_Struct::freeFile\fP"... 
.PP
Definition at line 64 of file __XSMemoryDebug.h.
.SS "const char* \fB__XSMemoryRecord_Struct::freeFunc\fP"... 
.PP
Definition at line 66 of file __XSMemoryDebug.h.
.SS "int \fB__XSMemoryRecord_Struct::freeLine\fP"... 
.PP
Definition at line 65 of file __XSMemoryDebug.h.
.SS "\fBStr255\fP \fB__XSMemoryRecord_Struct::hash\fP"... 
.PP
Definition at line 59 of file __XSMemoryDebug.h.
.SS "\fB__XSMemoryObject\fP* \fB__XSMemoryRecord_Struct::object\fP"
.PP
Definition at line 55 of file __XSMemoryDebug.h.
.SS "size_t \fB__XSMemoryRecord_Struct::size\fP"... 
.PP
Definition at line 56 of file __XSMemoryDebug.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for XSFoundation from the source code.
