.TH "__XSApplication_Struct" 3 "Sun Apr 24 2011" "Version 1.2.2-0" "XSFoundation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
__XSApplication_Struct \- 
.PP
XSApplication class.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include '__XSApplication.h'\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBXSRuntimeClass\fP \fB__class\fP"
.br
.ti -1c
.RI "\fBXSUInteger\fP \fBarg_alloc\fP"
.br
.ti -1c
.RI "\fBXSUInteger\fP \fBarg_count\fP"
.br
.ti -1c
.RI "int \fBargc\fP"
.br
.ti -1c
.RI "\fBXSApplicationArgument\fP * \fBargs\fP"
.br
.ti -1c
.RI "const char ** \fBargv\fP"
.br
.ti -1c
.RI "const char * \fBexecutable\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
XSApplication class. 
.PP
Definition at line 52 of file __XSApplication.h.
.SH "Field Documentation"
.PP 
.SS "\fBXSRuntimeClass\fP \fB__XSApplication_Struct::__class\fP"
.PP
Definition at line 54 of file __XSApplication.h.
.SS "\fBXSUInteger\fP \fB__XSApplication_Struct::arg_alloc\fP"The number of registered arguments 
.PP
Definition at line 60 of file __XSApplication.h.
.SS "\fBXSUInteger\fP \fB__XSApplication_Struct::arg_count\fP"The registered arguments 
.PP
Definition at line 59 of file __XSApplication.h.
.SS "int \fB__XSApplication_Struct::argc\fP"Runtime class 
.PP
Definition at line 55 of file __XSApplication.h.
.SS "\fBXSApplicationArgument\fP* \fB__XSApplication_Struct::args\fP"The executable name 
.PP
Definition at line 58 of file __XSApplication.h.
.SS "const char** \fB__XSApplication_Struct::argv\fP"The number of CLI arguments 
.PP
Definition at line 56 of file __XSApplication.h.
.SS "const char* \fB__XSApplication_Struct::executable\fP"A pointer to the CLI arguments 
.PP
Definition at line 57 of file __XSApplication.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for XSFoundation from the source code.
