.TH "__XSBTree.h" 3 "Sun Apr 24 2011" "Version 1.2.2-0" "XSFoundation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
__XSBTree.h \- 
.PP
Private BTree class definitions.  

.SH SYNOPSIS
.br
.PP
\fC#include '../XSMacros.h'\fP
.br
\fC#include 'XS.h'\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fB__XSBTree_Struct\fP"
.br
.RI "\fIXSBTree class. \fP"
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef struct \fB__XSBTree_Struct\fP \fB__XSBTree\fP"
.br
.RI "\fIXSBTree class type. \fP"
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fB__XSBTree_Copy\fP (\fBXSObject\fP source, \fBXSObject\fP destination)"
.br
.RI "\fIObject copy. \fP"
.ti -1c
.RI "void \fB__XSBTree_Destruct\fP (\fBXSObject\fP object)"
.br
.RI "\fIDestructor. \fP"
.ti -1c
.RI "void \fB__XSBTree_Initialize\fP (void)"
.br
.RI "\fIRuntime initialization. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Private BTree class definitions. 

\fBAuthor:\fP
.RS 4
Jean-David Gadina <macmade@eosgarden.com> 
.RE
.PP

.PP
Definition in file \fB__XSBTree.h\fP.
.SH "Typedef Documentation"
.PP 
.SS "\fB__XSBTree\fP"
.PP
XSBTree class type. 
.PP
Definition at line 65 of file __XSBTree.h.
.SH "Function Documentation"
.PP 
.SS "void __XSBTree_Copy (\fBXSObject\fPsource, \fBXSObject\fPdestination)"
.PP
Object copy. \fBParameters:\fP
.RS 4
\fIsource\fP The source object 
.br
\fIdestination\fP The destination object 
.RE
.PP
\fBReturns:\fP
.RS 4
void 
.RE
.PP

.SS "void __XSBTree_Destruct (\fBXSObject\fPobject)"
.PP
Destructor. \fBParameters:\fP
.RS 4
\fIobject\fP A pointer to the object 
.RE
.PP
\fBReturns:\fP
.RS 4
void 
.RE
.PP

.SS "void __XSBTree_Initialize (void)"
.PP
Runtime initialization. \fBReturns:\fP
.RS 4
void 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for XSFoundation from the source code.
