.TH "__XSApplicationArgument_Struct" 3 "Sun Apr 24 2011" "Version 1.2.2-0" "XSFoundation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
__XSApplicationArgument_Struct \- 
.PP
XSApplicationArgument class.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include '__XSApplicationArgument.h'\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBXSRuntimeClass\fP \fB__class\fP"
.br
.ti -1c
.RI "\fBBOOL\fP \fBflag_val\fP"
.br
.ti -1c
.RI "\fBXSFloat\fP \fBfloat_val\fP"
.br
.ti -1c
.RI "const char * \fBhelp\fP"
.br
.ti -1c
.RI "\fBXSInteger\fP \fBint_val\fP"
.br
.ti -1c
.RI "const char * \fBname\fP"
.br
.ti -1c
.RI "const char * \fBstr_val\fP"
.br
.ti -1c
.RI "\fBXSUInteger\fP \fBtype\fP"
.br
.ti -1c
.RI "\fBXSUInteger\fP \fBuint_val\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
XSApplicationArgument class. 
.PP
Definition at line 52 of file __XSApplicationArgument.h.
.SH "Field Documentation"
.PP 
.SS "\fBXSRuntimeClass\fP \fB__XSApplicationArgument_Struct::__class\fP"
.PP
Definition at line 54 of file __XSApplicationArgument.h.
.SS "\fBBOOL\fP \fB__XSApplicationArgument_Struct::flag_val\fP"... 
.PP
Definition at line 60 of file __XSApplicationArgument.h.
.SS "\fBXSFloat\fP \fB__XSApplicationArgument_Struct::float_val\fP"... 
.PP
Definition at line 61 of file __XSApplicationArgument.h.
.SS "const char* \fB__XSApplicationArgument_Struct::help\fP"... 
.PP
Definition at line 62 of file __XSApplicationArgument.h.
.SS "\fBXSInteger\fP \fB__XSApplicationArgument_Struct::int_val\fP"... 
.PP
Definition at line 57 of file __XSApplicationArgument.h.
.SS "const char* \fB__XSApplicationArgument_Struct::name\fP"Runtime class 
.PP
Definition at line 55 of file __XSApplicationArgument.h.
.SS "const char* \fB__XSApplicationArgument_Struct::str_val\fP"... 
.PP
Definition at line 59 of file __XSApplicationArgument.h.
.SS "\fBXSUInteger\fP \fB__XSApplicationArgument_Struct::type\fP"... 
.PP
Definition at line 56 of file __XSApplicationArgument.h.
.SS "\fBXSUInteger\fP \fB__XSApplicationArgument_Struct::uint_val\fP"... 
.PP
Definition at line 58 of file __XSApplicationArgument.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for XSFoundation from the source code.
