.TH "__XSNull_Struct" 3 "Sun Apr 24 2011" "Version 1.2.2-0" "XSFoundation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
__XSNull_Struct \- 
.PP
XSNull class.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include '__XSNull.h'\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBXSRuntimeClass\fP \fB__class\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
XSNull class. 
.PP
Definition at line 52 of file __XSNull.h.
.SH "Field Documentation"
.PP 
.SS "\fBXSRuntimeClass\fP \fB__XSNull_Struct::__class\fP"
.PP
Definition at line 54 of file __XSNull.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for XSFoundation from the source code.
