.TH "__XSNotification_Struct" 3 "Sun Apr 24 2011" "Version 1.2.2-0" "XSFoundation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
__XSNotification_Struct \- 
.PP
XSNotification class.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include '__XSNotification.h'\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBXSRuntimeClass\fP \fB__class\fP"
.br
.ti -1c
.RI "\fBXSString\fP \fBname\fP"
.br
.ti -1c
.RI "\fBXSObject\fP \fBobject\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
XSNotification class. 
.PP
Definition at line 52 of file __XSNotification.h.
.SH "Field Documentation"
.PP 
.SS "\fBXSRuntimeClass\fP \fB__XSNotification_Struct::__class\fP"
.PP
Definition at line 54 of file __XSNotification.h.
.SS "\fBXSString\fP \fB__XSNotification_Struct::name\fP"... 
.PP
Definition at line 56 of file __XSNotification.h.
.SS "\fBXSObject\fP \fB__XSNotification_Struct::object\fP"Runtime class 
.PP
Definition at line 55 of file __XSNotification.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for XSFoundation from the source code.
