.TH "__XSBool.h" 3 "Sun Apr 24 2011" "Version 1.2.2-0" "XSFoundation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
__XSBool.h \- 
.PP
Private XSBool class definitions.  

.SH SYNOPSIS
.br
.PP
\fC#include '../XSMacros.h'\fP
.br
\fC#include 'XS.h'\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fB__XSBool_Struct\fP"
.br
.RI "\fIXSBool class. \fP"
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef struct \fB__XSBool_Struct\fP \fB__XSBool\fP"
.br
.RI "\fIXSBool class type. \fP"
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBBOOL\fP \fB__XSBool_Equals\fP (\fBXSObject\fP object1, \fBXSObject\fP object2)"
.br
.RI "\fIObject comparison. \fP"
.ti -1c
.RI "void \fB__XSBool_Initialize\fP (void)"
.br
.RI "\fIRuntime initialization. \fP"
.ti -1c
.RI "\fBXSString\fP \fB__XSBool_ToString\fP (\fBXSObject\fP object)"
.br
.RI "\fIObject description. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Private XSBool class definitions. 

\fBAuthor:\fP
.RS 4
Jean-David Gadina <macmade@eosgarden.com> 
.RE
.PP

.PP
Definition in file \fB__XSBool.h\fP.
.SH "Typedef Documentation"
.PP 
.SS "\fB__XSBool\fP"
.PP
XSBool class type. 
.PP
Definition at line 62 of file __XSBool.h.
.SH "Function Documentation"
.PP 
.SS "\fBBOOL\fP __XSBool_Equals (\fBXSObject\fPobject1, \fBXSObject\fPobject2)"
.PP
Object comparison. \fBParameters:\fP
.RS 4
\fIobject1\fP The first object to compare 
.br
\fIobject2\fP The second object to compare 
.RE
.PP
\fBReturns:\fP
.RS 4
YES if both objects are equals, otherwise NO 
.RE
.PP

.SS "void __XSBool_Initialize (void)"
.PP
Runtime initialization. \fBReturns:\fP
.RS 4
void 
.RE
.PP

.SS "\fBXSString\fP __XSBool_ToString (\fBXSObject\fPobject)"
.PP
Object description. \fBParameters:\fP
.RS 4
\fIobject\fP A pointer to the object 
.RE
.PP
\fBReturns:\fP
.RS 4
The object's description 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for XSFoundation from the source code.
