.TH "__XSNull.h" 3 "Sun Apr 24 2011" "Version 1.2.2-0" "XSFoundation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
__XSNull.h \- 
.PP
Private XSNull class definitions.  

.SH SYNOPSIS
.br
.PP
\fC#include '../XSMacros.h'\fP
.br
\fC#include 'XS.h'\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fB__XSNull_Struct\fP"
.br
.RI "\fIXSNull class. \fP"
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef struct \fB__XSNull_Struct\fP \fB__XSNull\fP"
.br
.RI "\fIXSNull class type. \fP"
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBBOOL\fP \fB__XSNull_Equals\fP (\fBXSObject\fP object1, \fBXSObject\fP object2)"
.br
.RI "\fIObject comparison. \fP"
.ti -1c
.RI "void \fB__XSNull_Initialize\fP (void)"
.br
.RI "\fIRuntime initialization. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Private XSNull class definitions. 

\fBAuthor:\fP
.RS 4
Jean-David Gadina <macmade@eosgarden.com> 
.RE
.PP

.PP
Definition in file \fB__XSNull.h\fP.
.SH "Typedef Documentation"
.PP 
.SS "\fB__XSNull\fP"
.PP
XSNull class type. 
.PP
Definition at line 61 of file __XSNull.h.
.SH "Function Documentation"
.PP 
.SS "\fBBOOL\fP __XSNull_Equals (\fBXSObject\fPobject1, \fBXSObject\fPobject2)"
.PP
Object comparison. \fBParameters:\fP
.RS 4
\fIobject1\fP The first object to compare 
.br
\fIobject2\fP The second object to compare 
.RE
.PP
\fBReturns:\fP
.RS 4
YES if both objects are equals, otherwise NO 
.RE
.PP

.SS "void __XSNull_Initialize (void)"
.PP
Runtime initialization. \fBReturns:\fP
.RS 4
void 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for XSFoundation from the source code.
