.TH "__XSURL.h" 3 "Sun Apr 24 2011" "Version 1.2.2-0" "XSFoundation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
__XSURL.h \- 
.PP
Private XSURL class definitions.  

.SH SYNOPSIS
.br
.PP
\fC#include '../XSMacros.h'\fP
.br
\fC#include 'XS.h'\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fB__XSURL_Struct\fP"
.br
.RI "\fIXSURL class. \fP"
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef struct \fB__XSURL_Struct\fP \fB__XSURL\fP"
.br
.RI "\fIXSURL class type. \fP"
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fB__XSURL_Copy\fP (\fBXSObject\fP source, \fBXSObject\fP destination)"
.br
.RI "\fIObject copy. \fP"
.ti -1c
.RI "void \fB__XSURL_Destruct\fP (\fBXSObject\fP object)"
.br
.RI "\fIDestructor. \fP"
.ti -1c
.RI "\fBBOOL\fP \fB__XSURL_Equals\fP (\fBXSObject\fP object1, \fBXSObject\fP object2)"
.br
.RI "\fIObject comparison. \fP"
.ti -1c
.RI "void \fB__XSURL_Initialize\fP (void)"
.br
.RI "\fIRuntime initialization. \fP"
.ti -1c
.RI "\fBXSString\fP \fB__XSURL_ToString\fP (\fBXSObject\fP object)"
.br
.RI "\fIObject description. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Private XSURL class definitions. 

\fBAuthor:\fP
.RS 4
Jean-David Gadina <macmade@eosgarden.com> 
.RE
.PP

.PP
Definition in file \fB__XSURL.h\fP.
.SH "Typedef Documentation"
.PP 
.SS "\fB__XSURL\fP"
.PP
XSURL class type. 
.PP
Definition at line 67 of file __XSURL.h.
.SH "Function Documentation"
.PP 
.SS "void __XSURL_Copy (\fBXSObject\fPsource, \fBXSObject\fPdestination)"
.PP
Object copy. \fBParameters:\fP
.RS 4
\fIsource\fP The source object 
.br
\fIdestination\fP The destination object 
.RE
.PP
\fBReturns:\fP
.RS 4
void 
.RE
.PP

.SS "void __XSURL_Destruct (\fBXSObject\fPobject)"
.PP
Destructor. \fBParameters:\fP
.RS 4
\fIobject\fP A pointer to the object 
.RE
.PP
\fBReturns:\fP
.RS 4
void 
.RE
.PP

.SS "\fBBOOL\fP __XSURL_Equals (\fBXSObject\fPobject1, \fBXSObject\fPobject2)"
.PP
Object comparison. \fBParameters:\fP
.RS 4
\fIobject1\fP The first object to compare 
.br
\fIobject2\fP The second object to compare 
.RE
.PP
\fBReturns:\fP
.RS 4
YES if both objects are equals, otherwise NO 
.RE
.PP

.SS "void __XSURL_Initialize (void)"
.PP
Runtime initialization. \fBReturns:\fP
.RS 4
void 
.RE
.PP

.SS "\fBXSString\fP __XSURL_ToString (\fBXSObject\fPobject)"
.PP
Object description. \fBParameters:\fP
.RS 4
\fIobject\fP A pointer to the object 
.RE
.PP
\fBReturns:\fP
.RS 4
The object's description 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for XSFoundation from the source code.
