.TH "__XSColor_Struct" 3 "Sun Apr 24 2011" "Version 1.2.2-0" "XSFoundation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
__XSColor_Struct \- 
.PP
XSColor class.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include '__XSColor.h'\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBXSRuntimeClass\fP \fB__class\fP"
.br
.ti -1c
.RI "\fBXSFloat\fP \fBalpha\fP"
.br
.ti -1c
.RI "\fBXSFloat\fP \fBblue\fP"
.br
.ti -1c
.RI "\fBXSFloat\fP \fBgreen\fP"
.br
.ti -1c
.RI "\fBXSFloat\fP \fBhue\fP"
.br
.ti -1c
.RI "\fBXSFloat\fP \fBluminance\fP"
.br
.ti -1c
.RI "\fBXSFloat\fP \fBred\fP"
.br
.ti -1c
.RI "\fBXSFloat\fP \fBsaturation\fP"
.br
.ti -1c
.RI "\fBXSFloat\fP \fBvalue\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
XSColor class. 
.PP
Definition at line 52 of file __XSColor.h.
.SH "Field Documentation"
.PP 
.SS "\fBXSRuntimeClass\fP \fB__XSColor_Struct::__class\fP"
.PP
Definition at line 54 of file __XSColor.h.
.SS "\fBXSFloat\fP \fB__XSColor_Struct::alpha\fP"... 
.PP
Definition at line 62 of file __XSColor.h.
.SS "\fBXSFloat\fP \fB__XSColor_Struct::blue\fP"... 
.PP
Definition at line 57 of file __XSColor.h.
.SS "\fBXSFloat\fP \fB__XSColor_Struct::green\fP"... 
.PP
Definition at line 56 of file __XSColor.h.
.SS "\fBXSFloat\fP \fB__XSColor_Struct::hue\fP"... 
.PP
Definition at line 58 of file __XSColor.h.
.SS "\fBXSFloat\fP \fB__XSColor_Struct::luminance\fP"... 
.PP
Definition at line 61 of file __XSColor.h.
.SS "\fBXSFloat\fP \fB__XSColor_Struct::red\fP"Runtime class 
.PP
Definition at line 55 of file __XSColor.h.
.SS "\fBXSFloat\fP \fB__XSColor_Struct::saturation\fP"... 
.PP
Definition at line 59 of file __XSColor.h.
.SS "\fBXSFloat\fP \fB__XSColor_Struct::value\fP"... 
.PP
Definition at line 60 of file __XSColor.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for XSFoundation from the source code.
