.TH "__XSNotificationCenter_Struct" 3 "Sun Apr 24 2011" "Version 1.2.2-0" "XSFoundation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
__XSNotificationCenter_Struct \- 
.PP
XSNotificationCenter class.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include '__XSNotificationCenter.h'\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBXSRuntimeClass\fP \fB__class\fP"
.br
.ti -1c
.RI "\fBXSDictionary\fP \fBobjects\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
XSNotificationCenter class. 
.PP
Definition at line 52 of file __XSNotificationCenter.h.
.SH "Field Documentation"
.PP 
.SS "\fBXSRuntimeClass\fP \fB__XSNotificationCenter_Struct::__class\fP"
.PP
Definition at line 54 of file __XSNotificationCenter.h.
.SS "\fBXSDictionary\fP \fB__XSNotificationCenter_Struct::objects\fP"Runtime class 
.PP
Definition at line 55 of file __XSNotificationCenter.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for XSFoundation from the source code.
