.TH "__XSNumber_Struct" 3 "Sun Apr 24 2011" "Version 1.2.2-0" "XSFoundation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
__XSNumber_Struct \- 
.PP
XSNumber class.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include '__XSNumber.h'\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBXSRuntimeClass\fP \fB__class\fP"
.br
.ti -1c
.RI "\fBBOOL\fP \fBboolValue\fP"
.br
.ti -1c
.RI "double \fBdoubleValue\fP"
.br
.ti -1c
.RI "float \fBfloatValue\fP"
.br
.ti -1c
.RI "signed char \fBsCharValue\fP"
.br
.ti -1c
.RI "\fBXSInteger\fP \fBsIntegerValue\fP"
.br
.ti -1c
.RI "signed int \fBsIntValue\fP"
.br
.ti -1c
.RI "signed long long \fBsLongLongValue\fP"
.br
.ti -1c
.RI "signed long \fBsLongValue\fP"
.br
.ti -1c
.RI "signed short \fBsShortValue\fP"
.br
.ti -1c
.RI "uint16_t \fBtypes\fP"
.br
.ti -1c
.RI "unsigned char \fBuCharValue\fP"
.br
.ti -1c
.RI "\fBXSUInteger\fP \fBuIntegerValue\fP"
.br
.ti -1c
.RI "unsigned int \fBuIntValue\fP"
.br
.ti -1c
.RI "unsigned long long \fBuLongLongValue\fP"
.br
.ti -1c
.RI "unsigned long \fBuLongValue\fP"
.br
.ti -1c
.RI "unsigned short \fBuShortValue\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
XSNumber class. 
.PP
Definition at line 69 of file __XSNumber.h.
.SH "Field Documentation"
.PP 
.SS "\fBXSRuntimeClass\fP \fB__XSNumber_Struct::__class\fP"
.PP
Definition at line 71 of file __XSNumber.h.
.SS "\fBBOOL\fP \fB__XSNumber_Struct::boolValue\fP"... 
.PP
Definition at line 73 of file __XSNumber.h.
.SS "double \fB__XSNumber_Struct::doubleValue\fP"... 
.PP
Definition at line 85 of file __XSNumber.h.
.SS "float \fB__XSNumber_Struct::floatValue\fP"... 
.PP
Definition at line 84 of file __XSNumber.h.
.SS "signed char \fB__XSNumber_Struct::sCharValue\fP"... 
.PP
Definition at line 74 of file __XSNumber.h.
.SS "\fBXSInteger\fP \fB__XSNumber_Struct::sIntegerValue\fP"... 
.PP
Definition at line 86 of file __XSNumber.h.
.SS "signed int \fB__XSNumber_Struct::sIntValue\fP"... 
.PP
Definition at line 78 of file __XSNumber.h.
.SS "signed long long \fB__XSNumber_Struct::sLongLongValue\fP"... 
.PP
Definition at line 82 of file __XSNumber.h.
.SS "signed long \fB__XSNumber_Struct::sLongValue\fP"... 
.PP
Definition at line 80 of file __XSNumber.h.
.SS "signed short \fB__XSNumber_Struct::sShortValue\fP"... 
.PP
Definition at line 76 of file __XSNumber.h.
.SS "uint16_t \fB__XSNumber_Struct::types\fP"Runtime class 
.PP
Definition at line 72 of file __XSNumber.h.
.SS "unsigned char \fB__XSNumber_Struct::uCharValue\fP"... 
.PP
Definition at line 75 of file __XSNumber.h.
.SS "\fBXSUInteger\fP \fB__XSNumber_Struct::uIntegerValue\fP"... 
.PP
Definition at line 87 of file __XSNumber.h.
.SS "unsigned int \fB__XSNumber_Struct::uIntValue\fP"... 
.PP
Definition at line 79 of file __XSNumber.h.
.SS "unsigned long long \fB__XSNumber_Struct::uLongLongValue\fP"... 
.PP
Definition at line 83 of file __XSNumber.h.
.SS "unsigned long \fB__XSNumber_Struct::uLongValue\fP"... 
.PP
Definition at line 81 of file __XSNumber.h.
.SS "unsigned short \fB__XSNumber_Struct::uShortValue\fP"... 
.PP
Definition at line 77 of file __XSNumber.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for XSFoundation from the source code.
