.TH "source/include/win32/ Directory Reference" 3 "Sun Apr 24 2011" "Version 1.2.2-0" "XSFoundation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
source/include/win32/ Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBwin32-compat.h\fP"
.br
.PP

.RI "\fICompatibility macros and functions for Windows. \fP"
.ti -1c
.RI "file \fBwin32-getpid.h\fP"
.br
.PP

.RI "\fIgetpid function for Windows \fP"
.ti -1c
.RI "file \fBwin32-pthread.h\fP"
.br
.PP

.RI "\fIPOSIX thread functions for Windows. \fP"
.ti -1c
.RI "file \fBwin32-signal.h\fP"
.br
.PP

.RI "\fISignal functions for Windows. \fP"
.ti -1c
.RI "file \fBwin32-stat.h\fP"
.br
.PP

.RI "\fIStat functions for windows. \fP"
.ti -1c
.RI "file \fBwin32-types.h\fP"
.br
.PP

.RI "\fIDefinition of POSIX system types for Windows. \fP"
.ti -1c
.RI "file \fBwin32-usleep.h\fP"
.br
.PP

.RI "\fIMicro-seconds sleep function. \fP"
.ti -1c
.RI "file \fBwin32.h\fP"
.br
.PP

.RI "\fIWindows compatibility headers. \fP"
.in -1c
