.TH "source/include/std/ Directory Reference" 3 "Sun Apr 24 2011" "Version 1.2.2-0" "XSFoundation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
source/include/std/ Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBstd-ascii.h\fP"
.br
.PP

.RI "\fIASCII control characters. \fP"
.ti -1c
.RI "file \fBstd-bitwise.h\fP"
.br
.PP

.RI "\fIBitwise operations. \fP"
.ti -1c
.RI "file \fBstd-bool.h\fP"
.br
.PP

.RI "\fIDefinition of the boolean datatype. \fP"
.ti -1c
.RI "file \fBstd-c99.h\fP"
.br
.PP

.RI "\fIInclusion of the full C99 header files. \fP"
.ti -1c
.RI "file \fBstd-keywords.h\fP"
.br
.PP

.RI "\fIStandard compiant keywords. \fP"
.ti -1c
.RI "file \fBstd-math.h\fP"
.br
.PP

.RI "\fIMathematical macros. \fP"
.ti -1c
.RI "file \fBstd-md5.h\fP"
.br
.PP

.RI "\fIMD5 hash algorithm. \fP"
.ti -1c
.RI "file \fBstd-posix.h\fP"
.br
.PP

.RI "\fIInclusion of the full POSIX header files. \fP"
.ti -1c
.RI "file \fBstd-string.h\fP"
.br
.PP

.RI "\fIDefinition of the non-standard string functions. \fP"
.ti -1c
.RI "file \fBstd.h\fP"
.br
.PP

.RI "\fIC standardization. \fP"
.in -1c
