.TH "source/include/ Directory Reference" 3 "Sun Apr 24 2011" "Version 1.2.2-0" "XSFoundation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
source/include/ Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBeos-skl\fP"
.br
.ti -1c
.RI "directory \fBstd\fP"
.br
.ti -1c
.RI "directory \fBwin32\fP"
.br
.ti -1c
.RI "directory \fBxs\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBXS.h\fP"
.br
.PP

.RI "\fIXSFoundation main header file. \fP"
.in -1c
