.TH "source/include/eos-skl/__private/arch/ Directory Reference" 3 "Sun Apr 24 2011" "Version 1.2.2-0" "XSFoundation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
source/include/eos-skl/__private/arch/ Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fB__arm.h\fP"
.br
.PP

.RI "\fIEOS-SKL (Source Kit Language) ARM private routines. \fP"
.ti -1c
.RI "file \fB__i386.h\fP"
.br
.PP

.RI "\fIEOS-SKL (Source Kit Language) i386 private routines. \fP"
.in -1c
