.TH "eos-skl.h" 3 "Sun Apr 24 2011" "Version 1.2.2-0" "XSFoundation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
eos-skl.h \- 
.PP
EOS-SKL (Source Kit Language) main header file.  

.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
EOS-SKL (Source Kit Language) main header file. 

\fBAuthor:\fP
.RS 4
Jean-David Gadina <macmade@eosgarden.com> 
.RE
.PP
\fBVersion:\fP
.RS 4
4.5.3-8 
.RE
.PP
\fBSince:\fP
.RS 4
2.5.0 
.RE
.PP

.PP
Definition in file \fBeos-skl.h\fP.
.SH "Author"
.PP 
Generated automatically by Doxygen for XSFoundation from the source code.
