.TH "MD5_CTX_Struct" 3 "Sun Apr 24 2011" "Version 1.2.2-0" "XSFoundation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MD5_CTX_Struct \- 
.PP
MD5 context structure.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include 'std-md5.h'\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "unsigned char \fBbuffer\fP [64]"
.br
.ti -1c
.RI "unsigned long int \fBcount\fP [2]"
.br
.ti -1c
.RI "unsigned long int \fBstate\fP [4]"
.br
.in -1c
.SH "Detailed Description"
.PP 
MD5 context structure. 
.PP
Definition at line 47 of file std-md5.h.
.SH "Field Documentation"
.PP 
.SS "unsigned char \fBMD5_CTX_Struct::buffer\fP[64]"Number of bits, modulo 2^64 (LSB first) 
.PP
Definition at line 51 of file std-md5.h.
.SS "unsigned long int \fBMD5_CTX_Struct::count\fP[2]"State (ABCD) 
.PP
Definition at line 50 of file std-md5.h.
.SS "unsigned long int \fBMD5_CTX_Struct::state\fP[4]"
.PP
Definition at line 49 of file std-md5.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for XSFoundation from the source code.
