.TH "pthread_attr_t_struct" 3 "Sun Apr 24 2011" "Version 1.2.2-0" "XSFoundation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pthread_attr_t_struct \- 
.PP
Thread attribute structure.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include 'win32-pthread.h'\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBdetachstate\fP"
.br
.ti -1c
.RI "void * \fBstackaddr\fP"
.br
.ti -1c
.RI "size_t \fBstacksize\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Thread attribute structure. 
.PP
Definition at line 70 of file win32-pthread.h.
.SH "Field Documentation"
.PP 
.SS "int \fBpthread_attr_t_struct::detachstate\fP"
.PP
Definition at line 72 of file win32-pthread.h.
.SS "void* \fBpthread_attr_t_struct::stackaddr\fP"Detached state 
.PP
Definition at line 73 of file win32-pthread.h.
.SS "size_t \fBpthread_attr_t_struct::stacksize\fP"Stack address 
.PP
Definition at line 74 of file win32-pthread.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for XSFoundation from the source code.
