.TH "siginfo_t_struct" 3 "Sun Apr 24 2011" "Version 1.2.2-0" "XSFoundation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
siginfo_t_struct \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include 'win32-signal.h'\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "void * \fBsi_addr\fP"
.br
.ti -1c
.RI "int \fBsi_band\fP"
.br
.ti -1c
.RI "int \fBsi_code\fP"
.br
.ti -1c
.RI "int \fBsi_errno\fP"
.br
.ti -1c
.RI "\fBpid_t\fP \fBsi_pid\fP"
.br
.ti -1c
.RI "int \fBsi_signo\fP"
.br
.ti -1c
.RI "int \fBsi_status\fP"
.br
.ti -1c
.RI "\fBuid_t\fP \fBsi_uid\fP"
.br
.ti -1c
.RI "union \fBsigval\fP \fBsi_value\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 293 of file win32-signal.h.
.SH "Field Documentation"
.PP 
.SS "void* \fBsiginfo_t_struct::si_addr\fP"... 
.PP
Definition at line 301 of file win32-signal.h.
.SS "int \fBsiginfo_t_struct::si_band\fP"... 
.PP
Definition at line 303 of file win32-signal.h.
.SS "int \fBsiginfo_t_struct::si_code\fP"... 
.PP
Definition at line 296 of file win32-signal.h.
.SS "int \fBsiginfo_t_struct::si_errno\fP"... 
.PP
Definition at line 298 of file win32-signal.h.
.SS "\fBpid_t\fP \fBsiginfo_t_struct::si_pid\fP"... 
.PP
Definition at line 299 of file win32-signal.h.
.SS "int \fBsiginfo_t_struct::si_signo\fP"
.PP
Definition at line 295 of file win32-signal.h.
.SS "int \fBsiginfo_t_struct::si_status\fP"... 
.PP
Definition at line 302 of file win32-signal.h.
.SS "\fBuid_t\fP \fBsiginfo_t_struct::si_uid\fP"... 
.PP
Definition at line 300 of file win32-signal.h.
.SS "union \fBsigval\fP \fBsiginfo_t_struct::si_value\fP"... 
.PP
Definition at line 297 of file win32-signal.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for XSFoundation from the source code.
