.TH "siginfo_t" 3 "Sun Apr 24 2011" "Version 1.2.2-0" "XSFoundation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
siginfo_t \- 
.PP
...  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include 'win32-signal.h'\fP
.SH "Detailed Description"
.PP 
... 

.SH "Author"
.PP 
Generated automatically by Doxygen for XSFoundation from the source code.
