.TH "sigval" 3 "Sun Apr 24 2011" "Version 1.2.2-0" "XSFoundation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sigval \- 
.PP
...  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include 'win32-signal.h'\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBsival_int\fP"
.br
.ti -1c
.RI "void * \fBsival_ptr\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
... 
.PP
Definition at line 283 of file win32-signal.h.
.SH "Field Documentation"
.PP 
.SS "int \fBsigval::sival_int\fP"
.PP
Definition at line 285 of file win32-signal.h.
.SS "void* \fBsigval::sival_ptr\fP"... 
.PP
Definition at line 286 of file win32-signal.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for XSFoundation from the source code.
