.TH "std-bool.h" 3 "Sun Apr 24 2011" "Version 1.2.2-0" "XSFoundation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
std-bool.h \- 
.PP
Definition of the boolean datatype.  

.SH SYNOPSIS
.br
.PP
.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fB__bool_true_false_are_defined\fP   1"
.br
.RI "\fIRequired by the C standard. \fP"
.ti -1c
.RI "#define \fBbool\fP   char"
.br
.RI "\fIBoolean data type. \fP"
.ti -1c
.RI "#define \fBfalse\fP   0"
.br
.RI "\fIFalse value. \fP"
.ti -1c
.RI "#define \fBtrue\fP   1"
.br
.RI "\fITrue value. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Definition of the boolean datatype. 

\fBAuthor:\fP
.RS 4
Jean-David Gadina <macmade@eosgarden.com> 
.RE
.PP

.PP
Definition in file \fBstd-bool.h\fP.
.SH "Define Documentation"
.PP 
.SS "#define __bool_true_false_are_defined   1"
.PP
Required by the C standard. 
.PP
Definition at line 82 of file std-bool.h.
.SS "#define bool   char"
.PP
Boolean data type. 
.PP
Definition at line 62 of file std-bool.h.
.SS "#define false   0"
.PP
False value. 
.PP
Definition at line 76 of file std-bool.h.
.SS "#define true   1"
.PP
True value. 
.PP
Definition at line 70 of file std-bool.h.
.SH "Author"
.PP 
Generated automatically by Doxygen for XSFoundation from the source code.
