.TH "std-posix.h" 3 "Sun Apr 24 2011" "Version 1.2.2-0" "XSFoundation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
std-posix.h \- 
.PP
Inclusion of the full POSIX header files.  

.SH SYNOPSIS
.br
.PP
\fC#include <cpio.h>\fP
.br
\fC#include <dirent.h>\fP
.br
\fC#include <fcntl.h>\fP
.br
\fC#include <grp.h>\fP
.br
\fC#include <pthread.h>\fP
.br
\fC#include <pwd.h>\fP
.br
\fC#include <sys/ipc.h>\fP
.br
\fC#include <sys/msg.h>\fP
.br
\fC#include <sys/sem.h>\fP
.br
\fC#include <sys/stat.h>\fP
.br
\fC#include <sys/time.h>\fP
.br
\fC#include <sys/types.h>\fP
.br
\fC#include <sys/utsname.h>\fP
.br
\fC#include <sys/wait.h>\fP
.br
\fC#include <tar.h>\fP
.br
\fC#include <termios.h>\fP
.br
\fC#include <unistd.h>\fP
.br
\fC#include <utime.h>\fP
.br

.SH "Detailed Description"
.PP 
Inclusion of the full POSIX header files. 

\fBAuthor:\fP
.RS 4
Jean-David Gadina <macmade@eosgarden.com> 
.RE
.PP

.PP
Definition in file \fBstd-posix.h\fP.
.SH "Author"
.PP 
Generated automatically by Doxygen for XSFoundation from the source code.
