.TH "std-keywords.h" 3 "Sun Apr 24 2011" "Version 1.2.2-0" "XSFoundation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
std-keywords.h \- 
.PP
Standard compiant keywords.  

.SH SYNOPSIS
.br
.PP
.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fB__asm__\fP   asm"
.br
.RI "\fIInline assembly code. \fP"
.ti -1c
.RI "#define \fB__inline__\fP   inline"
.br
.RI "\fIInline functions. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Standard compiant keywords. 

\fBAuthor:\fP
.RS 4
Jean-David Gadina <macmade@eosgarden.com> 
.RE
.PP

.PP
Definition in file \fBstd-keywords.h\fP.
.SH "Define Documentation"
.PP 
.SS "#define __asm__   asm"
.PP
Inline assembly code. 
.PP
Definition at line 54 of file std-keywords.h.
.SS "#define __inline__   inline"
.PP
Inline functions. 
.PP
Definition at line 64 of file std-keywords.h.
.SH "Author"
.PP 
Generated automatically by Doxygen for XSFoundation from the source code.
