.TH "std.h" 3 "Sun Apr 24 2011" "Version 1.2.2-0" "XSFoundation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
std.h \- 
.PP
C standardization.  

.SH SYNOPSIS
.br
.PP
\fC#include 'std-c99.h'\fP
.br
\fC#include 'std-posix.h'\fP
.br
\fC#include <sys/socket.h>\fP
.br
\fC#include <netdb.h>\fP
.br
\fC#include <arpa/inet.h>\fP
.br
\fC#include 'std-keywords.h'\fP
.br
\fC#include 'std-bool.h'\fP
.br
\fC#include 'std-math.h'\fP
.br
\fC#include 'std-md5.h'\fP
.br
\fC#include 'std-bitwise.h'\fP
.br
\fC#include 'std-ascii.h'\fP
.br
\fC#include 'std-string.h'\fP
.br

.SH "Detailed Description"
.PP 
C standardization. 

\fBAuthor:\fP
.RS 4
Jean-David Gadina <macmade@eosgarden.com> 
.RE
.PP

.PP
Definition in file \fBstd.h\fP.
.SH "Author"
.PP 
Generated automatically by Doxygen for XSFoundation from the source code.
