.TH "XS.h" 3 "Sun Apr 24 2011" "Version 1.2.2-0" "XSFoundation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
XS.h \- 
.PP
XSFoundation main header file.  

.SH SYNOPSIS
.br
.PP
\fC#include 'std/std.h'\fP
.br
\fC#include 'XS/XSMacros.h'\fP
.br
\fC#include 'XS/XSConstants.h'\fP
.br
\fC#include 'XS/XSTypes.h'\fP
.br
\fC#include 'XS/XSLog.h'\fP
.br
\fC#include 'XS/XSMemory.h'\fP
.br
\fC#include 'XS/XSMemoryDebug.h'\fP
.br
\fC#include 'XS/XSRuntime.h'\fP
.br
\fC#include 'XS/XSApplicationArgument.h'\fP
.br
\fC#include 'XS/XSApplication.h'\fP
.br
\fC#include 'XS/XSArray.h'\fP
.br
\fC#include 'XS/XSBag.h'\fP
.br
\fC#include 'XS/XSBool.h'\fP
.br
\fC#include 'XS/XSBTree.h'\fP
.br
\fC#include 'XS/XSColor.h'\fP
.br
\fC#include 'XS/XSDebugLog.h'\fP
.br
\fC#include 'XS/XSData.h'\fP
.br
\fC#include 'XS/XSDictionary.h'\fP
.br
\fC#include 'XS/XSError.h'\fP
.br
\fC#include 'XS/XSException.h'\fP
.br
\fC#include 'XS/XSFile.h'\fP
.br
\fC#include 'XS/XSGeometry.h'\fP
.br
\fC#include 'XS/XSHost.h'\fP
.br
\fC#include 'XS/XSLock.h'\fP
.br
\fC#include 'XS/XSNull.h'\fP
.br
\fC#include 'XS/XSNotification.h'\fP
.br
\fC#include 'XS/XSNotificationCenter.h'\fP
.br
\fC#include 'XS/XSNumber.h'\fP
.br
\fC#include 'XS/XSSet.h'\fP
.br
\fC#include 'XS/XSSort.h'\fP
.br
\fC#include 'XS/XSString.h'\fP
.br
\fC#include 'XS/XSThread.h'\fP
.br
\fC#include 'XS/XSTimer.h'\fP
.br
\fC#include 'XS/XSURL.h'\fP
.br
\fC#include 'XS/XSURLRequest.h'\fP
.br

.SH "Detailed Description"
.PP 
XSFoundation main header file. 

\fBAuthor:\fP
.RS 4
Jean-David Gadina <macmade@eosgarden.com>
.RE
.PP
This file should be included on projects using the XEOS C Foundation Library. Other header files should never be included directly. 
.PP
Definition in file \fBXS.h\fP.
.SH "Author"
.PP 
Generated automatically by Doxygen for XSFoundation from the source code.
