.TH "XSBool.h" 3 "Sun Apr 24 2011" "Version 1.2.2-0" "XSFoundation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
XSBool.h \- 
.PP
XSBool class functions.  

.SH SYNOPSIS
.br
.PP
\fC#include 'XSMacros.h'\fP
.br

.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef struct \fB__XSBool_Struct\fP * \fBXSBool\fP"
.br
.RI "\fIOpaque type for the XSTree objects. \fP"
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "XSStatic \fBXSObject\fP \fBXSBool_Alloc\fP (void)"
.br
.RI "\fIObject allocator. \fP"
.ti -1c
.RI "\fBBOOL\fP \fBXSBool_GetValue\fP (\fBXSBool\fP xsThis)"
.br
.ti -1c
.RI "\fBXSObject\fP \fBXSBool_Init\fP (\fBXSObject\fP xsThis)"
.br
.ti -1c
.RI "void \fBXSBool_SetValue\fP (\fBXSBool\fP xsThis, \fBBOOL\fP value)"
.br
.in -1c
.SH "Detailed Description"
.PP 
XSBool class functions. 

\fBAuthor:\fP
.RS 4
Jean-David Gadina <macmade@eosgarden.com> 
.RE
.PP

.PP
Definition in file \fBXSBool.h\fP.
.SH "Typedef Documentation"
.PP 
.SS "\fBXSBool\fP"
.PP
Opaque type for the XSTree objects. 
.PP
Definition at line 50 of file XSBool.h.
.SH "Function Documentation"
.PP 
.SS "XSStatic \fBXSObject\fP XSBool_Alloc (void)"
.PP
Object allocator. \fBReturns:\fP
.RS 4
The allocated object 
.RE
.PP

.SS "\fBBOOL\fP XSBool_GetValue (\fBXSBool\fPxsThis)"
.SS "\fBXSObject\fP XSBool_Init (\fBXSObject\fPxsThis)"
.SS "void XSBool_SetValue (\fBXSBool\fPxsThis, \fBBOOL\fPvalue)"
.SH "Author"
.PP 
Generated automatically by Doxygen for XSFoundation from the source code.
