.TH "XSBTree.h" 3 "Sun Apr 24 2011" "Version 1.2.2-0" "XSFoundation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
XSBTree.h \- 
.PP
XSBTree class functions.  

.SH SYNOPSIS
.br
.PP
\fC#include 'XSMacros.h'\fP
.br

.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef struct \fB__XSBTree_Struct\fP * \fBXSBTree\fP"
.br
.RI "\fIOpaque type for the XSBTree objects. \fP"
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "XSStatic \fBXSObject\fP \fBXSBTree_Alloc\fP (void)"
.br
.RI "\fIObject allocator. \fP"
.ti -1c
.RI "XSAutoreleased \fBXSBTree\fP \fBXSBTree_CreateLeft\fP (\fBXSBTree\fP xsThis, \fBXSObject\fP value)"
.br
.ti -1c
.RI "XSAutoreleased \fBXSBTree\fP \fBXSBTree_CreateRight\fP (\fBXSBTree\fP xsThis, \fBXSObject\fP value)"
.br
.ti -1c
.RI "\fBXSUInteger\fP \fBXSBTree_GetDepth\fP (\fBXSBTree\fP xsThis)"
.br
.ti -1c
.RI "XSAutoreleased \fBXSBTree\fP * \fBXSBTree_GetLeafs\fP (\fBXSBTree\fP xsThis)"
.br
.ti -1c
.RI "XSAutoreleased \fBXSBTree\fP \fBXSBTree_GetLeft\fP (\fBXSBTree\fP xsThis)"
.br
.ti -1c
.RI "XSAutoreleased \fBXSBTree\fP \fBXSBTree_GetParent\fP (\fBXSBTree\fP xsThis)"
.br
.ti -1c
.RI "XSAutoreleased \fBXSBTree\fP \fBXSBTree_GetRight\fP (\fBXSBTree\fP xsThis)"
.br
.ti -1c
.RI "XSAutoreleased \fBXSBTree\fP \fBXSBTree_GetRoot\fP (\fBXSBTree\fP xsThis)"
.br
.ti -1c
.RI "XSAutoreleased \fBXSObject\fP \fBXSBTree_GetValue\fP (\fBXSBTree\fP xsThis)"
.br
.ti -1c
.RI "\fBXSObject\fP \fBXSBTree_Init\fP (\fBXSObject\fP xsThis)"
.br
.ti -1c
.RI "\fBBOOL\fP \fBXSBtree_IsLeaf\fP (\fBXSBTree\fP xsThis)"
.br
.ti -1c
.RI "\fBBOOL\fP \fBXSBtree_IsNode\fP (\fBXSBTree\fP xsThis)"
.br
.ti -1c
.RI "\fBBOOL\fP \fBXSBtree_IsRoot\fP (\fBXSBTree\fP xsThis)"
.br
.ti -1c
.RI "\fBXSBTree\fP \fBXSBTree_RemoveLeft\fP (\fBXSBTree\fP xsThis)"
.br
.ti -1c
.RI "\fBXSBTree\fP \fBXSBTree_RemoveRight\fP (\fBXSBTree\fP xsThis)"
.br
.ti -1c
.RI "\fBXSBTree\fP \fBXSBTree_SetLeft\fP (\fBXSBTree\fP xsThis, \fBXSBTree\fP left)"
.br
.ti -1c
.RI "\fBXSBTree\fP \fBXSBTree_SetParent\fP (\fBXSBTree\fP xsThis, \fBXSBTree\fP parent)"
.br
.ti -1c
.RI "\fBXSBTree\fP \fBXSBTree_SetRight\fP (\fBXSBTree\fP xsThis, \fBXSBTree\fP right)"
.br
.ti -1c
.RI "void \fBXSBTree_SetValue\fP (\fBXSBTree\fP xsThis, \fBXSObject\fP value)"
.br
.ti -1c
.RI "void \fBXSBTree_SwapChildren\fP (\fBXSBTree\fP xsThis)"
.br
.in -1c
.SH "Detailed Description"
.PP 
XSBTree class functions. 

\fBAuthor:\fP
.RS 4
Jean-David Gadina <macmade@eosgarden.com> 
.RE
.PP

.PP
Definition in file \fBXSBTree.h\fP.
.SH "Typedef Documentation"
.PP 
.SS "\fBXSBTree\fP"
.PP
Opaque type for the XSBTree objects. 
.PP
Definition at line 50 of file XSBTree.h.
.SH "Function Documentation"
.PP 
.SS "XSStatic \fBXSObject\fP XSBTree_Alloc (void)"
.PP
Object allocator. \fBReturns:\fP
.RS 4
The allocated object 
.RE
.PP

.SS "XSAutoreleased \fBXSBTree\fP XSBTree_CreateLeft (\fBXSBTree\fPxsThis, \fBXSObject\fPvalue)"
.SS "XSAutoreleased \fBXSBTree\fP XSBTree_CreateRight (\fBXSBTree\fPxsThis, \fBXSObject\fPvalue)"
.SS "\fBXSUInteger\fP XSBTree_GetDepth (\fBXSBTree\fPxsThis)"
.SS "XSAutoreleased \fBXSBTree\fP* XSBTree_GetLeafs (\fBXSBTree\fPxsThis)"
.SS "XSAutoreleased \fBXSBTree\fP XSBTree_GetLeft (\fBXSBTree\fPxsThis)"
.SS "XSAutoreleased \fBXSBTree\fP XSBTree_GetParent (\fBXSBTree\fPxsThis)"
.SS "XSAutoreleased \fBXSBTree\fP XSBTree_GetRight (\fBXSBTree\fPxsThis)"
.SS "XSAutoreleased \fBXSBTree\fP XSBTree_GetRoot (\fBXSBTree\fPxsThis)"
.SS "XSAutoreleased \fBXSObject\fP XSBTree_GetValue (\fBXSBTree\fPxsThis)"
.SS "\fBXSObject\fP XSBTree_Init (\fBXSObject\fPxsThis)"
.SS "\fBBOOL\fP XSBtree_IsLeaf (\fBXSBTree\fPxsThis)"
.SS "\fBBOOL\fP XSBtree_IsNode (\fBXSBTree\fPxsThis)"
.SS "\fBBOOL\fP XSBtree_IsRoot (\fBXSBTree\fPxsThis)"
.SS "\fBXSBTree\fP XSBTree_RemoveLeft (\fBXSBTree\fPxsThis)"
.SS "\fBXSBTree\fP XSBTree_RemoveRight (\fBXSBTree\fPxsThis)"
.SS "\fBXSBTree\fP XSBTree_SetLeft (\fBXSBTree\fPxsThis, \fBXSBTree\fPleft)"
.SS "\fBXSBTree\fP XSBTree_SetParent (\fBXSBTree\fPxsThis, \fBXSBTree\fPparent)"
.SS "\fBXSBTree\fP XSBTree_SetRight (\fBXSBTree\fPxsThis, \fBXSBTree\fPright)"
.SS "void XSBTree_SetValue (\fBXSBTree\fPxsThis, \fBXSObject\fPvalue)"
.SS "void XSBTree_SwapChildren (\fBXSBTree\fPxsThis)"
.SH "Author"
.PP 
Generated automatically by Doxygen for XSFoundation from the source code.
