.TH "XSClassInfos" 3 "Sun Apr 24 2011" "Version 1.2.2-0" "XSFoundation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
XSClassInfos \- 
.PP
XSFoundation runtime class type.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include 'XSTypes.h'\fP
.SH "Detailed Description"
.PP 
XSFoundation runtime class type. 

.SH "Author"
.PP 
Generated automatically by Doxygen for XSFoundation from the source code.
