.TH "XSColor.h" 3 "Sun Apr 24 2011" "Version 1.2.2-0" "XSFoundation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
XSColor.h \- 
.PP
XSColor class functions.  

.SH SYNOPSIS
.br
.PP
\fC#include 'XSMacros.h'\fP
.br

.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef struct \fB__XSColor_Struct\fP * \fBXSColor\fP"
.br
.RI "\fIOpaque type for the XSColor objects. \fP"
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "XSStatic \fBXSObject\fP \fBXSColor_Alloc\fP (void)"
.br
.RI "\fIObject allocator. \fP"
.ti -1c
.RI "XSAutoreleased XSStatic \fBXSColor\fP \fBXSColor_BlackColor\fP (void)"
.br
.RI "\fIInitializes a color with HSVA components. \fP"
.ti -1c
.RI "XSAutoreleased XSStatic \fBXSColor\fP \fBXSColor_BlueColor\fP (void)"
.br
.RI "\fIInitializes a blue color object. \fP"
.ti -1c
.RI "\fBXSFloat\fP \fBXSColor_GetAlpha\fP (\fBXSColor\fP xsThis)"
.br
.RI "\fIGet the alpha component. \fP"
.ti -1c
.RI "\fBXSFloat\fP \fBXSColor_GetBlue\fP (\fBXSColor\fP xsThis)"
.br
.RI "\fIGet the blue component. \fP"
.ti -1c
.RI "\fBXSFloat\fP \fBXSColor_GetGreen\fP (\fBXSColor\fP xsThis)"
.br
.RI "\fIGet the green component. \fP"
.ti -1c
.RI "\fBXSFloat\fP \fBXSColor_GetHue\fP (\fBXSColor\fP xsThis)"
.br
.RI "\fIGet the hue component. \fP"
.ti -1c
.RI "\fBXSFloat\fP \fBXSColor_GetLuminance\fP (\fBXSColor\fP xsThis)"
.br
.RI "\fIGet the luminance component. \fP"
.ti -1c
.RI "\fBXSFloat\fP \fBXSColor_GetRed\fP (\fBXSColor\fP xsThis)"
.br
.RI "\fIGet the red component. \fP"
.ti -1c
.RI "\fBXSFloat\fP \fBXSColor_GetSaturation\fP (\fBXSColor\fP xsThis)"
.br
.RI "\fIGet the saturation component. \fP"
.ti -1c
.RI "\fBXSFloat\fP \fBXSColor_GetValue\fP (\fBXSColor\fP xsThis)"
.br
.RI "\fIGet the value component. \fP"
.ti -1c
.RI "XSAutoreleased XSStatic \fBXSColor\fP \fBXSColor_GreenColor\fP (void)"
.br
.RI "\fIInitializes a green color object. \fP"
.ti -1c
.RI "\fBXSObject\fP \fBXSColor_Init\fP (\fBXSObject\fP xsThis)"
.br
.RI "\fIInitialize a color object. \fP"
.ti -1c
.RI "\fBXSColor\fP \fBXSColor_InitWithHSL\fP (\fBXSColor\fP xsThis, \fBXSFloat\fP h, \fBXSFloat\fP s, \fBXSFloat\fP l)"
.br
.RI "\fIInitializes a color with RGB components. \fP"
.ti -1c
.RI "\fBXSColor\fP \fBXSColor_InitWithHSLA\fP (\fBXSColor\fP xsThis, \fBXSFloat\fP h, \fBXSFloat\fP s, \fBXSFloat\fP l, \fBXSFloat\fP a)"
.br
.RI "\fIInitializes a color with RGB components. \fP"
.ti -1c
.RI "\fBXSColor\fP \fBXSColor_InitWithHSV\fP (\fBXSColor\fP xsThis, \fBXSFloat\fP h, \fBXSFloat\fP s, \fBXSFloat\fP v)"
.br
.RI "\fIInitializes a color with HSL components. \fP"
.ti -1c
.RI "\fBXSColor\fP \fBXSColor_InitWithHSVA\fP (\fBXSColor\fP xsThis, \fBXSFloat\fP h, \fBXSFloat\fP s, \fBXSFloat\fP v, \fBXSFloat\fP a)"
.br
.RI "\fIInitializes a color with HSL components. \fP"
.ti -1c
.RI "\fBXSColor\fP \fBXSColor_InitWithRGB\fP (\fBXSColor\fP xsThis, \fBXSFloat\fP r, \fBXSFloat\fP g, \fBXSFloat\fP b)"
.br
.RI "\fIInitializes a color with RGB components. \fP"
.ti -1c
.RI "\fBXSColor\fP \fBXSColor_InitWithRGBA\fP (\fBXSColor\fP xsThis, \fBXSFloat\fP r, \fBXSFloat\fP g, \fBXSFloat\fP b, \fBXSFloat\fP a)"
.br
.RI "\fIInitializes a color with RGB components. \fP"
.ti -1c
.RI "XSAutoreleased XSStatic \fBXSColor\fP \fBXSColor_RedColor\fP (void)"
.br
.RI "\fIInitializes a red color object. \fP"
.ti -1c
.RI "void \fBXSColor_SetAlpha\fP (\fBXSColor\fP xsThis, \fBXSFloat\fP v)"
.br
.RI "\fISets the alpha component. \fP"
.ti -1c
.RI "void \fBXSColor_SetBlue\fP (\fBXSColor\fP xsThis, \fBXSFloat\fP v)"
.br
.RI "\fISets the blue component. \fP"
.ti -1c
.RI "void \fBXSColor_SetGreen\fP (\fBXSColor\fP xsThis, \fBXSFloat\fP v)"
.br
.RI "\fISets the green component. \fP"
.ti -1c
.RI "void \fBXSColor_SetHue\fP (\fBXSColor\fP xsThis, \fBXSFloat\fP v)"
.br
.RI "\fISets the hue component. \fP"
.ti -1c
.RI "void \fBXSColor_SetLuminance\fP (\fBXSColor\fP xsThis, \fBXSFloat\fP v)"
.br
.RI "\fISets the luminance component. \fP"
.ti -1c
.RI "void \fBXSColor_SetRed\fP (\fBXSColor\fP xsThis, \fBXSFloat\fP v)"
.br
.RI "\fISets the red component. \fP"
.ti -1c
.RI "void \fBXSColor_SetSaturation\fP (\fBXSColor\fP xsThis, \fBXSFloat\fP v)"
.br
.RI "\fISets the saturation component. \fP"
.ti -1c
.RI "void \fBXSColor_SetValue\fP (\fBXSColor\fP xsThis, \fBXSFloat\fP v)"
.br
.RI "\fISets the value component. \fP"
.ti -1c
.RI "XSAutoreleased XSStatic \fBXSColor\fP \fBXSColor_WhiteColor\fP (void)"
.br
.RI "\fICreate a black color object. \fP"
.in -1c
.SH "Detailed Description"
.PP 
XSColor class functions. 

\fBAuthor:\fP
.RS 4
Jean-David Gadina <macmade@eosgarden.com> 
.RE
.PP

.PP
Definition in file \fBXSColor.h\fP.
.SH "Typedef Documentation"
.PP 
.SS "\fBXSColor\fP"
.PP
Opaque type for the XSColor objects. 
.PP
Definition at line 50 of file XSColor.h.
.SH "Function Documentation"
.PP 
.SS "XSStatic \fBXSObject\fP XSColor_Alloc (void)"
.PP
Object allocator. \fBReturns:\fP
.RS 4
The allocated object 
.RE
.PP

.SS "XSAutoreleased XSStatic \fBXSColor\fP XSColor_BlackColor (void)"
.PP
Initializes a color with HSVA components. \fBReturns:\fP
.RS 4
The color object 
.RE
.PP

.SS "XSAutoreleased XSStatic \fBXSColor\fP XSColor_BlueColor (void)"
.PP
Initializes a blue color object. \fBReturns:\fP
.RS 4
The color object 
.RE
.PP

.SS "\fBXSFloat\fP XSColor_GetAlpha (\fBXSColor\fPxsThis)"
.PP
Get the alpha component. \fBParameters:\fP
.RS 4
\fIxsThis\fP The color object 
.RE
.PP
\fBReturns:\fP
.RS 4
The alpha component 
.RE
.PP

.SS "\fBXSFloat\fP XSColor_GetBlue (\fBXSColor\fPxsThis)"
.PP
Get the blue component. \fBParameters:\fP
.RS 4
\fIxsThis\fP The color object 
.RE
.PP
\fBReturns:\fP
.RS 4
The blue component 
.RE
.PP

.SS "\fBXSFloat\fP XSColor_GetGreen (\fBXSColor\fPxsThis)"
.PP
Get the green component. \fBParameters:\fP
.RS 4
\fIxsThis\fP The color object 
.RE
.PP
\fBReturns:\fP
.RS 4
The green component 
.RE
.PP

.SS "\fBXSFloat\fP XSColor_GetHue (\fBXSColor\fPxsThis)"
.PP
Get the hue component. \fBParameters:\fP
.RS 4
\fIxsThis\fP The color object 
.RE
.PP
\fBReturns:\fP
.RS 4
The hue component 
.RE
.PP

.SS "\fBXSFloat\fP XSColor_GetLuminance (\fBXSColor\fPxsThis)"
.PP
Get the luminance component. \fBParameters:\fP
.RS 4
\fIxsThis\fP The color object 
.RE
.PP
\fBReturns:\fP
.RS 4
The luminance component 
.RE
.PP

.SS "\fBXSFloat\fP XSColor_GetRed (\fBXSColor\fPxsThis)"
.PP
Get the red component. \fBParameters:\fP
.RS 4
\fIxsThis\fP The color object 
.RE
.PP
\fBReturns:\fP
.RS 4
The red component 
.RE
.PP

.SS "\fBXSFloat\fP XSColor_GetSaturation (\fBXSColor\fPxsThis)"
.PP
Get the saturation component. \fBParameters:\fP
.RS 4
\fIxsThis\fP The color object 
.RE
.PP
\fBReturns:\fP
.RS 4
The saturation component 
.RE
.PP

.SS "\fBXSFloat\fP XSColor_GetValue (\fBXSColor\fPxsThis)"
.PP
Get the value component. \fBParameters:\fP
.RS 4
\fIxsThis\fP The color object 
.RE
.PP
\fBReturns:\fP
.RS 4
The value component 
.RE
.PP

.SS "XSAutoreleased XSStatic \fBXSColor\fP XSColor_GreenColor (void)"
.PP
Initializes a green color object. \fBReturns:\fP
.RS 4
The color object 
.RE
.PP

.SS "\fBXSObject\fP XSColor_Init (\fBXSObject\fPxsThis)"
.PP
Initialize a color object. \fBParameters:\fP
.RS 4
\fIxsThis\fP The color object 
.RE
.PP
\fBReturns:\fP
.RS 4
The color object 
.RE
.PP

.SS "\fBXSColor\fP XSColor_InitWithHSL (\fBXSColor\fPxsThis, \fBXSFloat\fPh, \fBXSFloat\fPs, \fBXSFloat\fPl)"
.PP
Initializes a color with RGB components. \fBParameters:\fP
.RS 4
\fIxsThis\fP The color object 
.br
\fIh\fP The hue value 
.br
\fIs\fP The saturation value 
.br
\fIl\fP The luminance value 
.RE
.PP
\fBReturns:\fP
.RS 4
The color object 
.RE
.PP

.SS "\fBXSColor\fP XSColor_InitWithHSLA (\fBXSColor\fPxsThis, \fBXSFloat\fPh, \fBXSFloat\fPs, \fBXSFloat\fPl, \fBXSFloat\fPa)"
.PP
Initializes a color with RGB components. \fBParameters:\fP
.RS 4
\fIxsThis\fP The color object 
.br
\fIh\fP The hue value 
.br
\fIs\fP The saturation value 
.br
\fIl\fP The luminance value 
.br
\fIa\fP The alpha value 
.RE
.PP
\fBReturns:\fP
.RS 4
The color object 
.RE
.PP

.SS "\fBXSColor\fP XSColor_InitWithHSV (\fBXSColor\fPxsThis, \fBXSFloat\fPh, \fBXSFloat\fPs, \fBXSFloat\fPv)"
.PP
Initializes a color with HSL components. \fBParameters:\fP
.RS 4
\fIxsThis\fP The color object 
.br
\fIh\fP The hue value 
.br
\fIs\fP The saturation value 
.br
\fIv\fP The value value 
.RE
.PP
\fBReturns:\fP
.RS 4
The color object 
.RE
.PP

.SS "\fBXSColor\fP XSColor_InitWithHSVA (\fBXSColor\fPxsThis, \fBXSFloat\fPh, \fBXSFloat\fPs, \fBXSFloat\fPv, \fBXSFloat\fPa)"
.PP
Initializes a color with HSL components. \fBParameters:\fP
.RS 4
\fIxsThis\fP The color object 
.br
\fIh\fP The hue value 
.br
\fIs\fP The saturation value 
.br
\fIv\fP The value value 
.br
\fIa\fP The alpha value 
.RE
.PP
\fBReturns:\fP
.RS 4
The color object 
.RE
.PP

.SS "\fBXSColor\fP XSColor_InitWithRGB (\fBXSColor\fPxsThis, \fBXSFloat\fPr, \fBXSFloat\fPg, \fBXSFloat\fPb)"
.PP
Initializes a color with RGB components. \fBParameters:\fP
.RS 4
\fIxsThis\fP The color object 
.br
\fIr\fP The red value 
.br
\fIg\fP The green value 
.br
\fIb\fP The blue value 
.RE
.PP
\fBReturns:\fP
.RS 4
The color object 
.RE
.PP

.SS "\fBXSColor\fP XSColor_InitWithRGBA (\fBXSColor\fPxsThis, \fBXSFloat\fPr, \fBXSFloat\fPg, \fBXSFloat\fPb, \fBXSFloat\fPa)"
.PP
Initializes a color with RGB components. \fBParameters:\fP
.RS 4
\fIxsThis\fP The color object 
.br
\fIr\fP The red value 
.br
\fIg\fP The green value 
.br
\fIb\fP The blue value 
.br
\fIa\fP The alpha value 
.RE
.PP
\fBReturns:\fP
.RS 4
The color object 
.RE
.PP

.SS "XSAutoreleased XSStatic \fBXSColor\fP XSColor_RedColor (void)"
.PP
Initializes a red color object. \fBReturns:\fP
.RS 4
The color object 
.RE
.PP

.SS "void XSColor_SetAlpha (\fBXSColor\fPxsThis, \fBXSFloat\fPv)"
.PP
Sets the alpha component. \fBParameters:\fP
.RS 4
\fIxsThis\fP The color object 
.br
\fIv\fP The alpha component 
.RE
.PP
\fBReturns:\fP
.RS 4
void 
.RE
.PP

.SS "void XSColor_SetBlue (\fBXSColor\fPxsThis, \fBXSFloat\fPv)"
.PP
Sets the blue component. \fBParameters:\fP
.RS 4
\fIxsThis\fP The color object 
.br
\fIv\fP The blue component 
.RE
.PP
\fBReturns:\fP
.RS 4
void 
.RE
.PP

.SS "void XSColor_SetGreen (\fBXSColor\fPxsThis, \fBXSFloat\fPv)"
.PP
Sets the green component. \fBParameters:\fP
.RS 4
\fIxsThis\fP The color object 
.br
\fIv\fP The green component 
.RE
.PP
\fBReturns:\fP
.RS 4
void 
.RE
.PP

.SS "void XSColor_SetHue (\fBXSColor\fPxsThis, \fBXSFloat\fPv)"
.PP
Sets the hue component. \fBParameters:\fP
.RS 4
\fIxsThis\fP The color object 
.br
\fIv\fP The hue component 
.RE
.PP
\fBReturns:\fP
.RS 4
void 
.RE
.PP

.SS "void XSColor_SetLuminance (\fBXSColor\fPxsThis, \fBXSFloat\fPv)"
.PP
Sets the luminance component. \fBParameters:\fP
.RS 4
\fIxsThis\fP The color object 
.br
\fIv\fP The luminance component 
.RE
.PP
\fBReturns:\fP
.RS 4
void 
.RE
.PP

.SS "void XSColor_SetRed (\fBXSColor\fPxsThis, \fBXSFloat\fPv)"
.PP
Sets the red component. \fBParameters:\fP
.RS 4
\fIxsThis\fP The color object 
.br
\fIv\fP The red component 
.RE
.PP
\fBReturns:\fP
.RS 4
void 
.RE
.PP

.SS "void XSColor_SetSaturation (\fBXSColor\fPxsThis, \fBXSFloat\fPv)"
.PP
Sets the saturation component. \fBParameters:\fP
.RS 4
\fIxsThis\fP The color object 
.br
\fIv\fP The saturation component 
.RE
.PP
\fBReturns:\fP
.RS 4
void 
.RE
.PP

.SS "void XSColor_SetValue (\fBXSColor\fPxsThis, \fBXSFloat\fPv)"
.PP
Sets the value component. \fBParameters:\fP
.RS 4
\fIxsThis\fP The color object 
.br
\fIv\fP The value component 
.RE
.PP
\fBReturns:\fP
.RS 4
void 
.RE
.PP

.SS "XSAutoreleased XSStatic \fBXSColor\fP XSColor_WhiteColor (void)"
.PP
Create a black color object. \fBReturns:\fP
.RS 4
The color object 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for XSFoundation from the source code.
