.TH "XSConstants.h" 3 "Sun Apr 24 2011" "Version 1.2.2-0" "XSFoundation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
XSConstants.h \- 
.PP
General constants.  

.SH SYNOPSIS
.br
.PP
\fC#include 'XSMacros.h'\fP
.br

.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBXSDecimalMaxSize\fP   ( 8 )"
.br
.ti -1c
.RI "#define \fBXSIntegerMax\fP   INT_MAX"
.br
.ti -1c
.RI "#define \fBXSIntegerMin\fP   INT_MIN"
.br
.ti -1c
.RI "#define \fBXSUIntegerMax\fP   UINT_MAX"
.br
.RI "\fINot found value for the \fBXSRange.location\fP field. \fP"
.in -1c
.SH "Detailed Description"
.PP 
General constants. 

\fBAuthor:\fP
.RS 4
Jean-David Gadina <macmade@eosgarden.com> 
.RE
.PP

.PP
Definition in file \fBXSConstants.h\fP.
.SH "Define Documentation"
.PP 
.SS "#define XSDecimalMaxSize   ( 8 )"
.PP
Definition at line 46 of file XSConstants.h.
.SS "#define XSIntegerMax   INT_MAX"
.PP
Definition at line 56 of file XSConstants.h.
.SS "#define XSIntegerMin   INT_MIN"
.PP
Definition at line 57 of file XSConstants.h.
.SS "#define XSUIntegerMax   UINT_MAX"
.PP
Not found value for the \fBXSRange.location\fP field. 
.SH "Author"
.PP 
Generated automatically by Doxygen for XSFoundation from the source code.
