.TH "XSDebugLog.h" 3 "Sun Apr 24 2011" "Version 1.2.2-0" "XSFoundation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
XSDebugLog.h \- 
.PP
Debug log functions.  

.SH SYNOPSIS
.br
.PP
\fC#include 'XSMacros.h'\fP
.br

.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBXSDebugLogLevel\fP { \fBXSDebugLogLevelEmergency\fP =  0x01, \fBXSDebugLogLevelAlert\fP =  0x02, \fBXSDebugLogLevelCritical\fP =  0x04, \fBXSDebugLogLevelError\fP =  0x05, \fBXSDebugLogLevelWarning\fP =  0x10, \fBXSDebugLogLevelNotice\fP =  0x20, \fBXSDebugLogLevelInfo\fP =  0x40, \fBXSDebugLogLevelDebug\fP =  0x80, \fBXSDebugLogLevelAll\fP =  0xFF }"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBXSDebugLog\fP (\fBXSDebugLogLevel\fP level, const char *format,...)"
.br
.ti -1c
.RI "void \fBXSDebugLogDisable\fP (\fBXSDebugLogLevel\fP level)"
.br
.ti -1c
.RI "void \fBXSDebugLogEnable\fP (\fBXSDebugLogLevel\fP level)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Debug log functions. 

\fBAuthor:\fP
.RS 4
Jean-David Gadina <macmade@eosgarden.com> 
.RE
.PP

.PP
Definition in file \fBXSDebugLog.h\fP.
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBXSDebugLogLevel\fP"
.PP
\fBEnumerator: \fP
.in +1c
.TP
\fB\fIXSDebugLogLevelEmergency \fP\fP
.TP
\fB\fIXSDebugLogLevelAlert \fP\fP
.TP
\fB\fIXSDebugLogLevelCritical \fP\fP
.TP
\fB\fIXSDebugLogLevelError \fP\fP
.TP
\fB\fIXSDebugLogLevelWarning \fP\fP
.TP
\fB\fIXSDebugLogLevelNotice \fP\fP
.TP
\fB\fIXSDebugLogLevelInfo \fP\fP
.TP
\fB\fIXSDebugLogLevelDebug \fP\fP
.TP
\fB\fIXSDebugLogLevelAll \fP\fP

.PP
Definition at line 46 of file XSDebugLog.h.
.SH "Function Documentation"
.PP 
.SS "void XSDebugLog (\fBXSDebugLogLevel\fPlevel, const char *format, ...)"
.SS "void XSDebugLogDisable (\fBXSDebugLogLevel\fPlevel)"
.SS "void XSDebugLogEnable (\fBXSDebugLogLevel\fPlevel)"
.SH "Author"
.PP 
Generated automatically by Doxygen for XSFoundation from the source code.
