.TH "XSEdgeInsets_Struct" 3 "Sun Apr 24 2011" "Version 1.2.2-0" "XSFoundation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
XSEdgeInsets_Struct \- 
.PP
Inset distances structure.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include 'XSTypes.h'\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBXSFloat\fP \fBbottom\fP"
.br
.ti -1c
.RI "\fBXSFloat\fP \fBleft\fP"
.br
.ti -1c
.RI "\fBXSFloat\fP \fBright\fP"
.br
.ti -1c
.RI "\fBXSFloat\fP \fBtop\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Inset distances structure. 
.PP
Definition at line 218 of file XSTypes.h.
.SH "Field Documentation"
.PP 
.SS "\fBXSFloat\fP \fBXSEdgeInsets_Struct::bottom\fP"The right coordinate 
.PP
Definition at line 223 of file XSTypes.h.
.SS "\fBXSFloat\fP \fBXSEdgeInsets_Struct::left\fP"
.PP
Definition at line 220 of file XSTypes.h.
.SS "\fBXSFloat\fP \fBXSEdgeInsets_Struct::right\fP"The top coordiante 
.PP
Definition at line 222 of file XSTypes.h.
.SS "\fBXSFloat\fP \fBXSEdgeInsets_Struct::top\fP"The left coordinate 
.PP
Definition at line 221 of file XSTypes.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for XSFoundation from the source code.
