.TH "XSExceptionContext_Struct" 3 "Sun Apr 24 2011" "Version 1.2.2-0" "XSFoundation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
XSExceptionContext_Struct \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include 'XSException.h'\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBcaught\fP"
.br
.ti -1c
.RI "volatile \fBXSException\fP \fBe\fP"
.br
.ti -1c
.RI "jmp_buf * \fBe_env\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 52 of file XSException.h.
.SH "Field Documentation"
.PP 
.SS "int \fBXSExceptionContext_Struct::caught\fP"
.PP
Definition at line 55 of file XSException.h.
.SS "volatile \fBXSException\fP \fBXSExceptionContext_Struct::e\fP"
.PP
Definition at line 56 of file XSException.h.
.SS "jmp_buf* \fBXSExceptionContext_Struct::e_env\fP"
.PP
Definition at line 54 of file XSException.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for XSFoundation from the source code.
