.TH "XSMemoryDebug.h" 3 "Sun Apr 24 2011" "Version 1.2.2-0" "XSFoundation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
XSMemoryDebug.h \- 
.PP
Memory debug functions.  

.SH SYNOPSIS
.br
.PP
\fC#include 'XSMacros.h'\fP
.br
\fC#include 'XSTypes.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBXSMemoryDebug_Disable\fP (void)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Memory debug functions. 

\fBAuthor:\fP
.RS 4
Jean-David Gadina <macmade@eosgarden.com> 
.RE
.PP

.PP
Definition in file \fBXSMemoryDebug.h\fP.
.SH "Function Documentation"
.PP 
.SS "void XSMemoryDebug_Disable (void)"
.SH "Author"
.PP 
Generated automatically by Doxygen for XSFoundation from the source code.
