.TH "XSNull.h" 3 "Sun Apr 24 2011" "Version 1.2.2-0" "XSFoundation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
XSNull.h \- 
.PP
XSNull class functions.  

.SH SYNOPSIS
.br
.PP
\fC#include 'XSMacros.h'\fP
.br

.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef struct \fB__XSNull_Struct\fP * \fBXSNull\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "XSStatic \fBXSObject\fP \fBXSNull_Alloc\fP (void)"
.br
.RI "\fIObject allocator. \fP"
.ti -1c
.RI "\fBXSObject\fP \fBXSNull_Init\fP (\fBXSObject\fP xsThis)"
.br
.ti -1c
.RI "XSStatic \fBXSNull\fP \fBXSNull_Null\fP (void)"
.br
.in -1c
.SH "Detailed Description"
.PP 
XSNull class functions. 

\fBAuthor:\fP
.RS 4
Jean-David Gadina <macmade@eosgarden.com> 
.RE
.PP

.PP
Definition in file \fBXSNull.h\fP.
.SH "Typedef Documentation"
.PP 
.SS "typedef struct \fB__XSNull_Struct\fP* \fBXSNull\fP"
.PP
Definition at line 50 of file XSNull.h.
.SH "Function Documentation"
.PP 
.SS "XSStatic \fBXSObject\fP XSNull_Alloc (void)"
.PP
Object allocator. \fBReturns:\fP
.RS 4
The allocated object 
.RE
.PP

.SS "\fBXSObject\fP XSNull_Init (\fBXSObject\fPxsThis)"
.SS "XSStatic \fBXSNull\fP XSNull_Null (void)"
.SH "Author"
.PP 
Generated automatically by Doxygen for XSFoundation from the source code.
