.TH "XSNumber.h" 3 "Sun Apr 24 2011" "Version 1.2.2-0" "XSFoundation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
XSNumber.h \- 
.PP
XSNumber class functions.  

.SH SYNOPSIS
.br
.PP
\fC#include 'XSMacros.h'\fP
.br

.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef struct \fB__XSNumber_Struct\fP * \fBXSNumber\fP"
.br
.RI "\fIOpaque type for the XSNumber objects. \fP"
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "XSStatic \fBXSObject\fP \fBXSNumber_Alloc\fP (void)"
.br
.RI "\fIObject allocator. \fP"
.ti -1c
.RI "\fBBOOL\fP \fBXSNumber_GetBool\fP (\fBXSNumber\fP xsThis)"
.br
.RI "\fIGets the number's value as a BOOL value. \fP"
.ti -1c
.RI "char \fBXSNumber_GetChar\fP (\fBXSNumber\fP xsThis)"
.br
.RI "\fIGets the number's value as a char value. \fP"
.ti -1c
.RI "double \fBXSNumber_GetDouble\fP (\fBXSNumber\fP xsThis)"
.br
.RI "\fIGets the number's value as a double value. \fP"
.ti -1c
.RI "float \fBXSNumber_GetFloat\fP (\fBXSNumber\fP xsThis)"
.br
.RI "\fIGets the number's value as a float value. \fP"
.ti -1c
.RI "int \fBXSNumber_GetInt\fP (\fBXSNumber\fP xsThis)"
.br
.RI "\fIGets the number's value as an int value. \fP"
.ti -1c
.RI "\fBXSInteger\fP \fBXSNumber_GetInteger\fP (\fBXSNumber\fP xsThis)"
.br
.RI "\fIGets the number's value as a XSInteger value. \fP"
.ti -1c
.RI "long \fBXSNumber_GetLong\fP (\fBXSNumber\fP xsThis)"
.br
.RI "\fIGets the number's value as a long value. \fP"
.ti -1c
.RI "long long \fBXSNumber_GetLongLong\fP (\fBXSNumber\fP xsThis)"
.br
.RI "\fIGets the number's value as a long long value. \fP"
.ti -1c
.RI "short \fBXSNumber_GetShort\fP (\fBXSNumber\fP xsThis)"
.br
.RI "\fIGets the number's value as a short value. \fP"
.ti -1c
.RI "unsigned char \fBXSNumber_GetUnsignedChar\fP (\fBXSNumber\fP xsThis)"
.br
.RI "\fIGets the number's value as an unsigned char value. \fP"
.ti -1c
.RI "unsigned int \fBXSNumber_GetUnsignedInt\fP (\fBXSNumber\fP xsThis)"
.br
.RI "\fIGets the number's value as an unsigned int value. \fP"
.ti -1c
.RI "\fBXSUInteger\fP \fBXSNumber_GetUnsignedInteger\fP (\fBXSNumber\fP xsThis)"
.br
.RI "\fIGets the number's value as a XSUInteger value. \fP"
.ti -1c
.RI "unsigned long \fBXSNumber_GetUnsignedLong\fP (\fBXSNumber\fP xsThis)"
.br
.RI "\fIGets the number's value as an unsigned long value. \fP"
.ti -1c
.RI "unsigned long long \fBXSNumber_GetUnsignedLongLong\fP (\fBXSNumber\fP xsThis)"
.br
.RI "\fIGets the number's value as an unsigned long long value. \fP"
.ti -1c
.RI "unsigned short \fBXSNumber_GetUnsignedShort\fP (\fBXSNumber\fP xsThis)"
.br
.RI "\fIGets the number's value as an unsigned short value. \fP"
.ti -1c
.RI "\fBXSObject\fP \fBXSNumber_Init\fP (\fBXSObject\fP xsThis)"
.br
.RI "\fIInitializes a number. \fP"
.ti -1c
.RI "\fBXSNumber\fP \fBXSNumber_InitWithBool\fP (\fBXSNumber\fP xsThis, \fBBOOL\fP value)"
.br
.RI "\fIInitializes a number with a BOOL value. \fP"
.ti -1c
.RI "\fBXSNumber\fP \fBXSNumber_InitWithChar\fP (\fBXSNumber\fP xsThis, char value)"
.br
.RI "\fIInitializes a number with a char value. \fP"
.ti -1c
.RI "\fBXSNumber\fP \fBXSNumber_InitWithDouble\fP (\fBXSNumber\fP xsThis, double value)"
.br
.RI "\fIInitializes a number with a double value. \fP"
.ti -1c
.RI "\fBXSNumber\fP \fBXSNumber_InitWithFloat\fP (\fBXSNumber\fP xsThis, float value)"
.br
.RI "\fIInitializes a number with a float value. \fP"
.ti -1c
.RI "\fBXSNumber\fP \fBXSNumber_InitWithInt\fP (\fBXSNumber\fP xsThis, int value)"
.br
.RI "\fIInitializes a number with an int value. \fP"
.ti -1c
.RI "\fBXSNumber\fP \fBXSNumber_InitWithInteger\fP (\fBXSNumber\fP xsThis, \fBXSInteger\fP value)"
.br
.RI "\fIInitializes a number with an integer value. \fP"
.ti -1c
.RI "\fBXSNumber\fP \fBXSNumber_InitWithLong\fP (\fBXSNumber\fP xsThis, long value)"
.br
.RI "\fIInitializes a number with a long value. \fP"
.ti -1c
.RI "\fBXSNumber\fP \fBXSNumber_InitWithLongLong\fP (\fBXSNumber\fP xsThis, long long value)"
.br
.RI "\fIInitializes a number with a long long value. \fP"
.ti -1c
.RI "\fBXSNumber\fP \fBXSNumber_InitWithShort\fP (\fBXSNumber\fP xsThis, short value)"
.br
.RI "\fIInitializes a number with a short value. \fP"
.ti -1c
.RI "\fBXSNumber\fP \fBXSNumber_InitWithUnsignedChar\fP (\fBXSNumber\fP xsThis, unsigned char value)"
.br
.RI "\fIInitializes a number with an unsigned char value. \fP"
.ti -1c
.RI "\fBXSNumber\fP \fBXSNumber_InitWithUnsignedInt\fP (\fBXSNumber\fP xsThis, unsigned int value)"
.br
.RI "\fIInitializes a number with an unsigned int value. \fP"
.ti -1c
.RI "\fBXSNumber\fP \fBXSNumber_InitWithUnsignedInteger\fP (\fBXSNumber\fP xsThis, \fBXSUInteger\fP value)"
.br
.RI "\fIInitializes a number with an unsigned integer value. \fP"
.ti -1c
.RI "\fBXSNumber\fP \fBXSNumber_InitWithUnsignedLong\fP (\fBXSNumber\fP xsThis, unsigned long value)"
.br
.RI "\fIInitializes a number with an unsigned long value. \fP"
.ti -1c
.RI "\fBXSNumber\fP \fBXSNumber_InitWithUnsignedLongLong\fP (\fBXSNumber\fP xsThis, unsigned long long value)"
.br
.RI "\fIInitializes a number with an unsigned long long value. \fP"
.ti -1c
.RI "\fBXSNumber\fP \fBXSNumber_InitWithUnsignedShort\fP (\fBXSNumber\fP xsThis, unsigned short value)"
.br
.RI "\fIInitializes a number with an unsigned short value. \fP"
.ti -1c
.RI "void \fBXSNumber_SetBool\fP (\fBXSNumber\fP xsThis, \fBBOOL\fP value)"
.br
.RI "\fISets the number's value with a BOOL value. \fP"
.ti -1c
.RI "void \fBXSNumber_SetChar\fP (\fBXSNumber\fP xsThis, char value)"
.br
.RI "\fISets the number's value with a char value. \fP"
.ti -1c
.RI "void \fBXSNumber_SetDouble\fP (\fBXSNumber\fP xsThis, double value)"
.br
.RI "\fISets the number's value with a double value. \fP"
.ti -1c
.RI "void \fBXSNumber_SetFloat\fP (\fBXSNumber\fP xsThis, float value)"
.br
.RI "\fISets the number's value with a float value. \fP"
.ti -1c
.RI "void \fBXSNumber_SetInt\fP (\fBXSNumber\fP xsThis, int value)"
.br
.RI "\fISets the number's value with an int value. \fP"
.ti -1c
.RI "void \fBXSNumber_SetInteger\fP (\fBXSNumber\fP xsThis, \fBXSInteger\fP value)"
.br
.RI "\fISets the number's value with a XSInteger value. \fP"
.ti -1c
.RI "void \fBXSNumber_SetLong\fP (\fBXSNumber\fP xsThis, long value)"
.br
.RI "\fISets the number's value with a long value. \fP"
.ti -1c
.RI "void \fBXSNumber_SetLongLong\fP (\fBXSNumber\fP xsThis, long long value)"
.br
.RI "\fISets the number's value with a long long value. \fP"
.ti -1c
.RI "void \fBXSNumber_SetShort\fP (\fBXSNumber\fP xsThis, short value)"
.br
.RI "\fISets the number's value with a short value. \fP"
.ti -1c
.RI "void \fBXSNumber_SetUnsignedChar\fP (\fBXSNumber\fP xsThis, unsigned char value)"
.br
.RI "\fISets the number's value with an unsigned char value. \fP"
.ti -1c
.RI "void \fBXSNumber_SetUnsignedInt\fP (\fBXSNumber\fP xsThis, unsigned int value)"
.br
.RI "\fISets the number's value with an unsigned int value. \fP"
.ti -1c
.RI "void \fBXSNumber_SetUnsignedInteger\fP (\fBXSNumber\fP xsThis, \fBXSUInteger\fP value)"
.br
.RI "\fISets the number's value with a XSUInteger value. \fP"
.ti -1c
.RI "void \fBXSNumber_SetUnsignedLong\fP (\fBXSNumber\fP xsThis, unsigned long value)"
.br
.RI "\fISets the number's value with an unsigned long value. \fP"
.ti -1c
.RI "void \fBXSNumber_SetUnsignedLongLong\fP (\fBXSNumber\fP xsThis, unsigned long long value)"
.br
.RI "\fISets the number's value with an unsigned long long value. \fP"
.ti -1c
.RI "void \fBXSNumber_SetUnsignedShort\fP (\fBXSNumber\fP xsThis, unsigned short value)"
.br
.RI "\fISets the number's value with an unsigned short value. \fP"
.in -1c
.SH "Detailed Description"
.PP 
XSNumber class functions. 

\fBAuthor:\fP
.RS 4
Jean-David Gadina <macmade@eosgarden.com> 
.RE
.PP

.PP
Definition in file \fBXSNumber.h\fP.
.SH "Typedef Documentation"
.PP 
.SS "\fBXSNumber\fP"
.PP
Opaque type for the XSNumber objects. 
.PP
Definition at line 50 of file XSNumber.h.
.SH "Function Documentation"
.PP 
.SS "XSStatic \fBXSObject\fP XSNumber_Alloc (void)"
.PP
Object allocator. \fBReturns:\fP
.RS 4
The allocated object 
.RE
.PP

.SS "\fBBOOL\fP XSNumber_GetBool (\fBXSNumber\fPxsThis)"
.PP
Gets the number's value as a BOOL value. Depending on the number's value, the result may be truncated. 
.PP
\fBParameters:\fP
.RS 4
\fIxsThis\fP The number object 
.RE
.PP
\fBReturns:\fP
.RS 4
The BOOL value 
.RE
.PP

.SS "char XSNumber_GetChar (\fBXSNumber\fPxsThis)"
.PP
Gets the number's value as a char value. Depending on the number's value, the result may be truncated. 
.PP
\fBParameters:\fP
.RS 4
\fIxsThis\fP The number object 
.RE
.PP
\fBReturns:\fP
.RS 4
The char value 
.RE
.PP

.SS "double XSNumber_GetDouble (\fBXSNumber\fPxsThis)"
.PP
Gets the number's value as a double value. Depending on the number's value, the result may be truncated. 
.PP
\fBParameters:\fP
.RS 4
\fIxsThis\fP The number object 
.RE
.PP
\fBReturns:\fP
.RS 4
The double value 
.RE
.PP

.SS "float XSNumber_GetFloat (\fBXSNumber\fPxsThis)"
.PP
Gets the number's value as a float value. Depending on the number's value, the result may be truncated. 
.PP
\fBParameters:\fP
.RS 4
\fIxsThis\fP The number object 
.RE
.PP
\fBReturns:\fP
.RS 4
The float value 
.RE
.PP

.SS "int XSNumber_GetInt (\fBXSNumber\fPxsThis)"
.PP
Gets the number's value as an int value. Depending on the number's value, the result may be truncated. 
.PP
\fBParameters:\fP
.RS 4
\fIxsThis\fP The number object 
.RE
.PP
\fBReturns:\fP
.RS 4
The int value 
.RE
.PP

.SS "\fBXSInteger\fP XSNumber_GetInteger (\fBXSNumber\fPxsThis)"
.PP
Gets the number's value as a XSInteger value. Depending on the number's value, the result may be truncated. 
.PP
\fBParameters:\fP
.RS 4
\fIxsThis\fP The number object 
.RE
.PP
\fBReturns:\fP
.RS 4
The XSInteger value 
.RE
.PP

.SS "long XSNumber_GetLong (\fBXSNumber\fPxsThis)"
.PP
Gets the number's value as a long value. Depending on the number's value, the result may be truncated. 
.PP
\fBParameters:\fP
.RS 4
\fIxsThis\fP The number object 
.RE
.PP
\fBReturns:\fP
.RS 4
The long value 
.RE
.PP

.SS "long long XSNumber_GetLongLong (\fBXSNumber\fPxsThis)"
.PP
Gets the number's value as a long long value. Depending on the number's value, the result may be truncated. 
.PP
\fBParameters:\fP
.RS 4
\fIxsThis\fP The number object 
.RE
.PP
\fBReturns:\fP
.RS 4
The long long value 
.RE
.PP

.SS "short XSNumber_GetShort (\fBXSNumber\fPxsThis)"
.PP
Gets the number's value as a short value. Depending on the number's value, the result may be truncated. 
.PP
\fBParameters:\fP
.RS 4
\fIxsThis\fP The number object 
.RE
.PP
\fBReturns:\fP
.RS 4
The short value 
.RE
.PP

.SS "unsigned char XSNumber_GetUnsignedChar (\fBXSNumber\fPxsThis)"
.PP
Gets the number's value as an unsigned char value. Depending on the number's value, the result may be truncated. 
.PP
\fBParameters:\fP
.RS 4
\fIxsThis\fP The number object 
.RE
.PP
\fBReturns:\fP
.RS 4
The unsigned char value 
.RE
.PP

.SS "unsigned int XSNumber_GetUnsignedInt (\fBXSNumber\fPxsThis)"
.PP
Gets the number's value as an unsigned int value. Depending on the number's value, the result may be truncated. 
.PP
\fBParameters:\fP
.RS 4
\fIxsThis\fP The number object 
.RE
.PP
\fBReturns:\fP
.RS 4
The unsigned int value 
.RE
.PP

.SS "\fBXSUInteger\fP XSNumber_GetUnsignedInteger (\fBXSNumber\fPxsThis)"
.PP
Gets the number's value as a XSUInteger value. Depending on the number's value, the result may be truncated. 
.PP
\fBParameters:\fP
.RS 4
\fIxsThis\fP The number object 
.RE
.PP
\fBReturns:\fP
.RS 4
The XSUInteger value 
.RE
.PP

.SS "unsigned long XSNumber_GetUnsignedLong (\fBXSNumber\fPxsThis)"
.PP
Gets the number's value as an unsigned long value. Depending on the number's value, the result may be truncated. 
.PP
\fBParameters:\fP
.RS 4
\fIxsThis\fP The number object 
.RE
.PP
\fBReturns:\fP
.RS 4
The unsigned long value 
.RE
.PP

.SS "unsigned long long XSNumber_GetUnsignedLongLong (\fBXSNumber\fPxsThis)"
.PP
Gets the number's value as an unsigned long long value. Depending on the number's value, the result may be truncated. 
.PP
\fBParameters:\fP
.RS 4
\fIxsThis\fP The number object 
.RE
.PP
\fBReturns:\fP
.RS 4
The unsigned long long value 
.RE
.PP

.SS "unsigned short XSNumber_GetUnsignedShort (\fBXSNumber\fPxsThis)"
.PP
Gets the number's value as an unsigned short value. Depending on the number's value, the result may be truncated. 
.PP
\fBParameters:\fP
.RS 4
\fIxsThis\fP The number object 
.RE
.PP
\fBReturns:\fP
.RS 4
The unsigned short value 
.RE
.PP

.SS "\fBXSObject\fP XSNumber_Init (\fBXSObject\fPxsThis)"
.PP
Initializes a number. \fBParameters:\fP
.RS 4
\fIxsThis\fP The number object 
.RE
.PP
\fBReturns:\fP
.RS 4
The number object 
.RE
.PP

.SS "\fBXSNumber\fP XSNumber_InitWithBool (\fBXSNumber\fPxsThis, \fBBOOL\fPvalue)"
.PP
Initializes a number with a BOOL value. \fBParameters:\fP
.RS 4
\fIxsThis\fP The number object 
.br
\fIvalue\fP The BOOL value 
.RE
.PP
\fBReturns:\fP
.RS 4
The number object 
.RE
.PP

.SS "\fBXSNumber\fP XSNumber_InitWithChar (\fBXSNumber\fPxsThis, charvalue)"
.PP
Initializes a number with a char value. \fBParameters:\fP
.RS 4
\fIxsThis\fP The number object 
.br
\fIvalue\fP The char value 
.RE
.PP
\fBReturns:\fP
.RS 4
The number object 
.RE
.PP

.SS "\fBXSNumber\fP XSNumber_InitWithDouble (\fBXSNumber\fPxsThis, doublevalue)"
.PP
Initializes a number with a double value. \fBParameters:\fP
.RS 4
\fIxsThis\fP The number object 
.br
\fIvalue\fP The double value 
.RE
.PP
\fBReturns:\fP
.RS 4
The number object 
.RE
.PP

.SS "\fBXSNumber\fP XSNumber_InitWithFloat (\fBXSNumber\fPxsThis, floatvalue)"
.PP
Initializes a number with a float value. \fBParameters:\fP
.RS 4
\fIxsThis\fP The number object 
.br
\fIvalue\fP The float value 
.RE
.PP
\fBReturns:\fP
.RS 4
The number object 
.RE
.PP

.SS "\fBXSNumber\fP XSNumber_InitWithInt (\fBXSNumber\fPxsThis, intvalue)"
.PP
Initializes a number with an int value. \fBParameters:\fP
.RS 4
\fIxsThis\fP The number object 
.br
\fIvalue\fP The int value 
.RE
.PP
\fBReturns:\fP
.RS 4
The number object 
.RE
.PP

.SS "\fBXSNumber\fP XSNumber_InitWithInteger (\fBXSNumber\fPxsThis, \fBXSInteger\fPvalue)"
.PP
Initializes a number with an integer value. \fBParameters:\fP
.RS 4
\fIxsThis\fP The number object 
.br
\fIvalue\fP The integer value 
.RE
.PP
\fBReturns:\fP
.RS 4
The number object 
.RE
.PP

.SS "\fBXSNumber\fP XSNumber_InitWithLong (\fBXSNumber\fPxsThis, longvalue)"
.PP
Initializes a number with a long value. \fBParameters:\fP
.RS 4
\fIxsThis\fP The number object 
.br
\fIvalue\fP The long value 
.RE
.PP
\fBReturns:\fP
.RS 4
The number object 
.RE
.PP

.SS "\fBXSNumber\fP XSNumber_InitWithLongLong (\fBXSNumber\fPxsThis, long longvalue)"
.PP
Initializes a number with a long long value. \fBParameters:\fP
.RS 4
\fIxsThis\fP The number object 
.br
\fIvalue\fP The long long value 
.RE
.PP
\fBReturns:\fP
.RS 4
The number object 
.RE
.PP

.SS "\fBXSNumber\fP XSNumber_InitWithShort (\fBXSNumber\fPxsThis, shortvalue)"
.PP
Initializes a number with a short value. \fBParameters:\fP
.RS 4
\fIxsThis\fP The number object 
.br
\fIvalue\fP The short value 
.RE
.PP
\fBReturns:\fP
.RS 4
The number object 
.RE
.PP

.SS "\fBXSNumber\fP XSNumber_InitWithUnsignedChar (\fBXSNumber\fPxsThis, unsigned charvalue)"
.PP
Initializes a number with an unsigned char value. \fBParameters:\fP
.RS 4
\fIxsThis\fP The number object 
.br
\fIvalue\fP The unsigned char value 
.RE
.PP
\fBReturns:\fP
.RS 4
The number object 
.RE
.PP

.SS "\fBXSNumber\fP XSNumber_InitWithUnsignedInt (\fBXSNumber\fPxsThis, unsigned intvalue)"
.PP
Initializes a number with an unsigned int value. \fBParameters:\fP
.RS 4
\fIxsThis\fP The number object 
.br
\fIvalue\fP The unsigned int value 
.RE
.PP
\fBReturns:\fP
.RS 4
The number object 
.RE
.PP

.SS "\fBXSNumber\fP XSNumber_InitWithUnsignedInteger (\fBXSNumber\fPxsThis, \fBXSUInteger\fPvalue)"
.PP
Initializes a number with an unsigned integer value. \fBParameters:\fP
.RS 4
\fIxsThis\fP The number object 
.br
\fIvalue\fP The unsigned integer value 
.RE
.PP
\fBReturns:\fP
.RS 4
The number object 
.RE
.PP

.SS "\fBXSNumber\fP XSNumber_InitWithUnsignedLong (\fBXSNumber\fPxsThis, unsigned longvalue)"
.PP
Initializes a number with an unsigned long value. \fBParameters:\fP
.RS 4
\fIxsThis\fP The number object 
.br
\fIvalue\fP The unsigned long value 
.RE
.PP
\fBReturns:\fP
.RS 4
The number object 
.RE
.PP

.SS "\fBXSNumber\fP XSNumber_InitWithUnsignedLongLong (\fBXSNumber\fPxsThis, unsigned long longvalue)"
.PP
Initializes a number with an unsigned long long value. \fBParameters:\fP
.RS 4
\fIxsThis\fP The number object 
.br
\fIvalue\fP The unsigned long long value 
.RE
.PP
\fBReturns:\fP
.RS 4
The number object 
.RE
.PP

.SS "\fBXSNumber\fP XSNumber_InitWithUnsignedShort (\fBXSNumber\fPxsThis, unsigned shortvalue)"
.PP
Initializes a number with an unsigned short value. \fBParameters:\fP
.RS 4
\fIxsThis\fP The number object 
.br
\fIvalue\fP The unsigned short value 
.RE
.PP
\fBReturns:\fP
.RS 4
The number object 
.RE
.PP

.SS "void XSNumber_SetBool (\fBXSNumber\fPxsThis, \fBBOOL\fPvalue)"
.PP
Sets the number's value with a BOOL value. \fBParameters:\fP
.RS 4
\fIxsThis\fP The number object 
.br
\fIvalue\fP The BOOL value 
.RE
.PP
\fBReturns:\fP
.RS 4
void 
.RE
.PP

.SS "void XSNumber_SetChar (\fBXSNumber\fPxsThis, charvalue)"
.PP
Sets the number's value with a char value. \fBParameters:\fP
.RS 4
\fIxsThis\fP The number object 
.br
\fIvalue\fP The char value 
.RE
.PP
\fBReturns:\fP
.RS 4
void 
.RE
.PP

.SS "void XSNumber_SetDouble (\fBXSNumber\fPxsThis, doublevalue)"
.PP
Sets the number's value with a double value. \fBParameters:\fP
.RS 4
\fIxsThis\fP The number object 
.br
\fIvalue\fP The double value 
.RE
.PP
\fBReturns:\fP
.RS 4
void 
.RE
.PP

.SS "void XSNumber_SetFloat (\fBXSNumber\fPxsThis, floatvalue)"
.PP
Sets the number's value with a float value. \fBParameters:\fP
.RS 4
\fIxsThis\fP The number object 
.br
\fIvalue\fP The float value 
.RE
.PP
\fBReturns:\fP
.RS 4
void 
.RE
.PP

.SS "void XSNumber_SetInt (\fBXSNumber\fPxsThis, intvalue)"
.PP
Sets the number's value with an int value. \fBParameters:\fP
.RS 4
\fIxsThis\fP The number object 
.br
\fIvalue\fP The int value 
.RE
.PP
\fBReturns:\fP
.RS 4
void 
.RE
.PP

.SS "void XSNumber_SetInteger (\fBXSNumber\fPxsThis, \fBXSInteger\fPvalue)"
.PP
Sets the number's value with a XSInteger value. \fBParameters:\fP
.RS 4
\fIxsThis\fP The number object 
.br
\fIvalue\fP The XSInteger value 
.RE
.PP
\fBReturns:\fP
.RS 4
void 
.RE
.PP

.SS "void XSNumber_SetLong (\fBXSNumber\fPxsThis, longvalue)"
.PP
Sets the number's value with a long value. \fBParameters:\fP
.RS 4
\fIxsThis\fP The number object 
.br
\fIvalue\fP The long value 
.RE
.PP
\fBReturns:\fP
.RS 4
void 
.RE
.PP

.SS "void XSNumber_SetLongLong (\fBXSNumber\fPxsThis, long longvalue)"
.PP
Sets the number's value with a long long value. \fBParameters:\fP
.RS 4
\fIxsThis\fP The number object 
.br
\fIvalue\fP The long long value 
.RE
.PP
\fBReturns:\fP
.RS 4
void 
.RE
.PP

.SS "void XSNumber_SetShort (\fBXSNumber\fPxsThis, shortvalue)"
.PP
Sets the number's value with a short value. \fBParameters:\fP
.RS 4
\fIxsThis\fP The number object 
.br
\fIvalue\fP The short value 
.RE
.PP
\fBReturns:\fP
.RS 4
void 
.RE
.PP

.SS "void XSNumber_SetUnsignedChar (\fBXSNumber\fPxsThis, unsigned charvalue)"
.PP
Sets the number's value with an unsigned char value. \fBParameters:\fP
.RS 4
\fIxsThis\fP The number object 
.br
\fIvalue\fP The unsigned char value 
.RE
.PP
\fBReturns:\fP
.RS 4
void 
.RE
.PP

.SS "void XSNumber_SetUnsignedInt (\fBXSNumber\fPxsThis, unsigned intvalue)"
.PP
Sets the number's value with an unsigned int value. \fBParameters:\fP
.RS 4
\fIxsThis\fP The number object 
.br
\fIvalue\fP The unsigned int value 
.RE
.PP
\fBReturns:\fP
.RS 4
void 
.RE
.PP

.SS "void XSNumber_SetUnsignedInteger (\fBXSNumber\fPxsThis, \fBXSUInteger\fPvalue)"
.PP
Sets the number's value with a XSUInteger value. \fBParameters:\fP
.RS 4
\fIxsThis\fP The number object 
.br
\fIvalue\fP The XSUInteger value 
.RE
.PP
\fBReturns:\fP
.RS 4
void 
.RE
.PP

.SS "void XSNumber_SetUnsignedLong (\fBXSNumber\fPxsThis, unsigned longvalue)"
.PP
Sets the number's value with an unsigned long value. \fBParameters:\fP
.RS 4
\fIxsThis\fP The number object 
.br
\fIvalue\fP The unsigned long value 
.RE
.PP
\fBReturns:\fP
.RS 4
void 
.RE
.PP

.SS "void XSNumber_SetUnsignedLongLong (\fBXSNumber\fPxsThis, unsigned long longvalue)"
.PP
Sets the number's value with an unsigned long long value. \fBParameters:\fP
.RS 4
\fIxsThis\fP The number object 
.br
\fIvalue\fP The unsigned long long value 
.RE
.PP
\fBReturns:\fP
.RS 4
void 
.RE
.PP

.SS "void XSNumber_SetUnsignedShort (\fBXSNumber\fPxsThis, unsigned shortvalue)"
.PP
Sets the number's value with an unsigned short value. \fBParameters:\fP
.RS 4
\fIxsThis\fP The number object 
.br
\fIvalue\fP The unsigned short value 
.RE
.PP
\fBReturns:\fP
.RS 4
void 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for XSFoundation from the source code.
