.TH "XSPoint_Struct" 3 "Sun Apr 24 2011" "Version 1.2.2-0" "XSFoundation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
XSPoint_Struct \- 
.PP
Point data-type structure.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include 'XSTypes.h'\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBXSFloat\fP \fBx\fP"
.br
.ti -1c
.RI "\fBXSFloat\fP \fBy\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Point data-type structure. 
.PP
Definition at line 148 of file XSTypes.h.
.SH "Field Documentation"
.PP 
.SS "\fBXSFloat\fP \fBXSPoint_Struct::x\fP"
.PP
Definition at line 150 of file XSTypes.h.
.SS "\fBXSFloat\fP \fBXSPoint_Struct::y\fP"The X coordinate of the point 
.PP
Definition at line 151 of file XSTypes.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for XSFoundation from the source code.
