.TH "XSRange_Struct" 3 "Sun Apr 24 2011" "Version 1.2.2-0" "XSFoundation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
XSRange_Struct \- 
.PP
Range data-type structure.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include 'XSTypes.h'\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBXSUInteger\fP \fBlength\fP"
.br
.ti -1c
.RI "\fBXSUInteger\fP \fBlocation\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Range data-type structure. 
.PP
Definition at line 196 of file XSTypes.h.
.SH "Field Documentation"
.PP 
.SS "\fBXSUInteger\fP \fBXSRange_Struct::length\fP"The start of the range 
.PP
Definition at line 199 of file XSTypes.h.
.SS "\fBXSUInteger\fP \fBXSRange_Struct::location\fP"
.PP
Definition at line 198 of file XSTypes.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for XSFoundation from the source code.
