.TH "XSRect_Struct" 3 "Sun Apr 24 2011" "Version 1.2.2-0" "XSFoundation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
XSRect_Struct \- 
.PP
Rectangle data-type structure.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include 'XSTypes.h'\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBXSPoint\fP \fBorigin\fP"
.br
.ti -1c
.RI "\fBXSSize\fP \fBsize\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Rectangle data-type structure. 
.PP
Definition at line 180 of file XSTypes.h.
.SH "Field Documentation"
.PP 
.SS "\fBXSPoint\fP \fBXSRect_Struct::origin\fP"
.PP
Definition at line 182 of file XSTypes.h.
.SS "\fBXSSize\fP \fBXSRect_Struct::size\fP"The origin point of the rectangle 
.PP
Definition at line 183 of file XSTypes.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for XSFoundation from the source code.
