.TH "XSRuntimeClass_Struct" 3 "Sun Apr 24 2011" "Version 1.2.2-0" "XSFoundation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
XSRuntimeClass_Struct \- 
.PP
Base structure for the runtime classes.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include 'XSTypes.h'\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBXSClassInfos\fP * \fBclassInfos\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Base structure for the runtime classes. 
.PP
Definition at line 342 of file XSTypes.h.
.SH "Field Documentation"
.PP 
.SS "\fBXSClassInfos\fP* \fBXSRuntimeClass_Struct::classInfos\fP"
.PP
Definition at line 344 of file XSTypes.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for XSFoundation from the source code.
