.TH "XSSize_Struct" 3 "Sun Apr 24 2011" "Version 1.2.2-0" "XSFoundation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
XSSize_Struct \- 
.PP
Size data-type structure.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include 'XSTypes.h'\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBXSFloat\fP \fBheight\fP"
.br
.ti -1c
.RI "\fBXSFloat\fP \fBwidth\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Size data-type structure. 
.PP
Definition at line 164 of file XSTypes.h.
.SH "Field Documentation"
.PP 
.SS "\fBXSFloat\fP \fBXSSize_Struct::height\fP"The width of the size 
.PP
Definition at line 167 of file XSTypes.h.
.SS "\fBXSFloat\fP \fBXSSize_Struct::width\fP"
.PP
Definition at line 166 of file XSTypes.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for XSFoundation from the source code.
