.TH "XSSort.h" 3 "Sun Apr 24 2011" "Version 1.2.2-0" "XSFoundation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
XSSort.h \- 
.PP
Sort functions.  

.SH SYNOPSIS
.br
.PP
\fC#include 'XSMacros.h'\fP
.br
\fC#include 'XSTypes.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBXSSort\fP (void *values, \fBXSDataType\fP type, \fBXSUInteger\fP size)"
.br
.RI "\fISort values using the shell sort algorithm. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Sort functions. 

\fBAuthor:\fP
.RS 4
Jean-David Gadina <macmade@eosgarden.com> 
.RE
.PP

.PP
Definition in file \fBXSSort.h\fP.
.SH "Function Documentation"
.PP 
.SS "void XSSort (void *values, \fBXSDataType\fPtype, \fBXSUInteger\fPsize)"
.PP
Sort values using the shell sort algorithm. \fBParameters:\fP
.RS 4
\fIvalues\fP The values to sort 
.br
\fItype\fP The type of the values 
.br
\fIsize\fP The number of values 
.RE
.PP
\fBReturns:\fP
.RS 4
void 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for XSFoundation from the source code.
