.TH "XSURLRequest.h" 3 "Sun Apr 24 2011" "Version 1.2.2-0" "XSFoundation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
XSURLRequest.h \- 
.PP
XSURLRequest class functions.  

.SH SYNOPSIS
.br
.PP
\fC#include 'XSMacros.h'\fP
.br
\fC#include 'XSURL.h'\fP
.br
\fC#include 'XSDictionary.h'\fP
.br
\fC#include 'XSData.h'\fP
.br

.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef struct \fB__XSURLRequest_Struct\fP * \fBXSURLRequest\fP"
.br
.RI "\fIOpaque type for the XSTree objects. \fP"
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "XSStatic \fBXSObject\fP \fBXSURLRequest_Alloc\fP (void)"
.br
.RI "\fIObject allocator. \fP"
.ti -1c
.RI "XSAutoreleased \fBXSDictionary\fP \fBXSURLRequest_GetHTTPHeaders\fP (\fBXSURLRequest\fP xsThis)"
.br
.ti -1c
.RI "XSAutoreleased \fBXSData\fP \fBXSURLRequest_GetRawBody\fP (\fBXSURLRequest\fP xsThis)"
.br
.ti -1c
.RI "XSAutoreleased \fBXSURL\fP \fBXSURLRequest_GetURL\fP (\fBXSURLRequest\fP xsThis)"
.br
.ti -1c
.RI "\fBXSObject\fP \fBXSURLRequest_InitWithURL\fP (\fBXSObject\fP xsThis, \fBXSURL\fP url)"
.br
.ti -1c
.RI "void \fBXSURLRequest_Start\fP (\fBXSURLRequest\fP xsThis)"
.br
.in -1c
.SH "Detailed Description"
.PP 
XSURLRequest class functions. 

\fBAuthor:\fP
.RS 4
Jean-David Gadina <macmade@eosgarden.com> 
.RE
.PP

.PP
Definition in file \fBXSURLRequest.h\fP.
.SH "Typedef Documentation"
.PP 
.SS "\fBXSURLRequest\fP"
.PP
Opaque type for the XSTree objects. 
.PP
Definition at line 54 of file XSURLRequest.h.
.SH "Function Documentation"
.PP 
.SS "XSStatic \fBXSObject\fP XSURLRequest_Alloc (void)"
.PP
Object allocator. \fBReturns:\fP
.RS 4
The allocated object 
.RE
.PP

.SS "XSAutoreleased \fBXSDictionary\fP XSURLRequest_GetHTTPHeaders (\fBXSURLRequest\fPxsThis)"
.SS "XSAutoreleased \fBXSData\fP XSURLRequest_GetRawBody (\fBXSURLRequest\fPxsThis)"
.SS "XSAutoreleased \fBXSURL\fP XSURLRequest_GetURL (\fBXSURLRequest\fPxsThis)"
.SS "\fBXSObject\fP XSURLRequest_InitWithURL (\fBXSObject\fPxsThis, \fBXSURL\fPurl)"
.SS "void XSURLRequest_Start (\fBXSURLRequest\fPxsThis)"
.SH "Author"
.PP 
Generated automatically by Doxygen for XSFoundation from the source code.
