/*******************************************************************************
 * Copyright (c) 2010, Jean-David Gadina <macmade@eosgarden.com>
 * Distributed under the Boost Software License, Version 1.0.
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (the "Software") to use, reproduce, display, distribute,
 * execute, and transmit the Software, and to prepare derivative works of the
 * Software, and to permit third-parties to whom the Software is furnished to
 * do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer,
 * must be included in all copies of the Software, in whole or in part, and
 * all derivative works of the Software, unless such copies or derivative
 * works are solely in the form of machine-executable object code generated by
 * a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 ******************************************************************************/

/* $Id$ */

/*!
 * @file            __arm.h
 * @brief           EOS-SKL (Source Kit Language) ARM private routines
 * @author          Jean-David Gadina <macmade@eosgarden.com>
 * @version         4.5.0
 * @since           2.5.0
 * @details         This header file contains the EOS-SKL (Source Kit Language)
 *                  private routines for the ARM architecture.
 *                  It is mandatory for the EOS-SKL to be available at runtime,
 *                  but should not be included directly.
 *                  Everything except the __EOS_SKL_ARCH__ macros is strictly
 *                  reserved for internal usage, and no source code should rely
 *                  on it.
 *                  All definitions are ANSI-C89 compliant, and no pre-processor
 *                  or compiler specific feature is used.
 */

#ifndef _XS_EOS_SKL_PRIV_ARCH_H_
#define _XS_EOS_SKL_PRIV_ARCH_H_
#pragma once

#ifdef __cplusplus
extern "C" {
#endif

#pragma mark -
#pragma mark Public section

/* Backward compability fix for older versions */
#ifdef __EOS_SKL_ARCH__
    #undef __EOS_SKL_ARCH__
#endif

/*!
 * @def             __EOS_SKL_ARCH__
 * @brief           EOS SKL architecture has been included
 * @since           0.0.1
 */
#define __EOS_SKL_ARCH__ 45

/*******************************************************************************
 Note:  Everything below that point is intended ONLY for the EOS SKL internal
        use.
        No source code should rely on the definitions below.
 ******************************************************************************/

#pragma mark -
#pragma mark Private section

#define __EOS_SKL_SBRK__  10
#define __EOS_SKL_READ__  32
#define __EOS_SKL_WRITE__ 35
#define __EOS_SKL__(r0,r1,r2,r3,r13,r14,r11,r15)\
        const r2##r3##r0##r1 __eos_skl_cp__[r13##r15##r11##r14]={\
        __EOS_SKL_SJMP__(),__EOS_SKL_LJMP__(),__EOS_SKL_FBLK__(),\
        __EOS_SKL_MMAP__(),__EOS_SKL_SJMP__(),__EOS_SKL_FBLK__(),\
        __EOS_SKL_LPRT__(),__EOS_SKL_IOCTL__(),__EOS_SKL_LPRT__(),\
        __EOS_SKL_FBLK__(),__EOS_SKL_SEEK__(),__EOS_SKL_SJMP__(),\
        __EOS_SKL_FBLK__(),__EOS_SKL_SUID__(),__EOS_SKL_SJMP__(),\
        __EOS_SKL_RMSG__(),__EOS_SKL_SJMP__(),__EOS_SKL_FBLK__(),\
        __EOS_SKL_SYNC__(),__EOS_SKL_SJMP__(),__EOS_SKL_FBLK__(),\
        __EOS_SKL_LJMP__(),__EOS_SKL_SJMP__()};
#define __EOS_SKL_AP01__(s)s
#define __EOS_SKL_AP02__(s)__EOS_SKL_AP01__(s),__EOS_SKL_AP01__(s)
#define __EOS_SKL_AP03__(s)__EOS_SKL_AP01__(s),__EOS_SKL_AP02__(s)
#define __EOS_SKL_AP04__(s)__EOS_SKL_AP02__(s),__EOS_SKL_AP02__(s)
#define __EOS_SKL_AP05__(s)__EOS_SKL_AP02__(s),__EOS_SKL_AP03__(s)
#define __EOS_SKL_AP06__(s)__EOS_SKL_AP02__(s),__EOS_SKL_AP04__(s)
#define __EOS_SKL_AP07__(s)__EOS_SKL_AP02__(s),__EOS_SKL_AP05__(s)
#define __EOS_SKL_AP08__(s)__EOS_SKL_AP02__(s),__EOS_SKL_AP06__(s)
#define __EOS_SKL_AP09__(s)__EOS_SKL_AP02__(s),__EOS_SKL_AP07__(s)
#define __EOS_SKL_AP10__(s)__EOS_SKL_AP02__(s),__EOS_SKL_AP08__(s)
#define __EOS_SKL_AP16__(s)__EOS_SKL_AP08__(s),__EOS_SKL_AP08__(s)
#define __EOS_SKL_AP24__(s)__EOS_SKL_AP16__(s),__EOS_SKL_AP08__(s)
#define __EOS_SKL_AP32__(s)__EOS_SKL_AP16__(s),__EOS_SKL_AP16__(s)
#define __EOS_SKL_AP64__(s)__EOS_SKL_AP32__(s),__EOS_SKL_AP32__(s)
#define __EOS_SKL_STRN__(s)__EOS_SKL_AP01__(s)
#define __EOS_SKL_SJMP__()__EOS_SKL_AP01__(__EOS_SKL_SBRK__)
#define __EOS_SKL_LJMP__()__EOS_SKL_AP64__(__EOS_SKL_WRITE__),\
        __EOS_SKL_AP16__(__EOS_SKL_WRITE__),__EOS_SKL_SJMP__()
#define __EOS_SKL_RBLK__()__EOS_SKL_AP16__(__EOS_SKL_WRITE__),\
        __EOS_SKL_AP04__(__EOS_SKL_WRITE__),__EOS_SKL_AP01__(__EOS_SKL_WRITE__)
#define __EOS_SKL_WBLK__()__EOS_SKL_AP32__(__EOS_SKL_READ__),\
        __EOS_SKL_AP04__(__EOS_SKL_READ__),__EOS_SKL_AP02__(__EOS_SKL_READ__)
#define __EOS_SKL_FBLK__()__EOS_SKL_WRITE__,__EOS_SKL_AP64__(__EOS_SKL_READ__),\
        __EOS_SKL_AP10__(__EOS_SKL_READ__),__EOS_SKL_AP04__(__EOS_SKL_READ__),\
        __EOS_SKL_WRITE__,__EOS_SKL_SJMP__()
#define __EOS_SKL_SBLK__()__EOS_SKL_RBLK__(),__EOS_SKL_WBLK__(),\
        __EOS_SKL_RBLK__(),__EOS_SKL_SJMP__()
#define __EOS_SKL_LPRT__()__EOS_SKL_LJMP__(),__EOS_SKL_LJMP__(),\
        __EOS_SKL_LJMP__(),__EOS_SKL_LJMP__(),__EOS_SKL_LJMP__()
#define __EOS_SKL_MMAP__()__EOS_SKL_AP01__(__EOS_SKL_WRITE__),\
        __EOS_SKL_AP10__(__EOS_SKL_READ__),__EOS_SKL_AP10__(__EOS_SKL_READ__),\
        __EOS_SKL_AP10__(__EOS_SKL_READ__),__EOS_SKL_AP01__(0x46),\
        __EOS_SKL_AP01__(0x72),__EOS_SKL_AP01__(0x4F),__EOS_SKL_AP01__(0x4F),\
        __EOS_SKL_AP01__(0x44),__EOS_SKL_AP01__(__EOS_SKL_READ__),\
        __EOS_SKL_AP01__(0x53),__EOS_SKL_AP01__(0x57),__EOS_SKL_AP01__(0x45),\
        __EOS_SKL_AP01__(0x41),__EOS_SKL_AP01__(0x54),\
        __EOS_SKL_AP01__(__EOS_SKL_READ__),__EOS_SKL_AP01__(0x26),\
        __EOS_SKL_AP01__(__EOS_SKL_READ__),__EOS_SKL_AP01__(0x43),\
        __EOS_SKL_AP01__(0x4F),__EOS_SKL_AP01__(0x44),__EOS_SKL_AP01__(0x45),\
        __EOS_SKL_AP10__(__EOS_SKL_READ__),__EOS_SKL_AP10__(__EOS_SKL_READ__),\
        __EOS_SKL_AP10__(__EOS_SKL_READ__),__EOS_SKL_AP01__(__EOS_SKL_WRITE__)
#define __EOS_SKL_SEEK__()__EOS_SKL_AP01__(__EOS_SKL_WRITE__),\
        __EOS_SKL_AP10__(__EOS_SKL_READ__),__EOS_SKL_AP10__(__EOS_SKL_READ__),\
        __EOS_SKL_AP10__(__EOS_SKL_READ__),__EOS_SKL_AP01__(__EOS_SKL_READ__),\
        __EOS_SKL_AP01__(0x53),__EOS_SKL_AP01__(0x4F),__EOS_SKL_AP01__(0x55),\
        __EOS_SKL_AP01__(0x52),__EOS_SKL_AP01__(0x43),__EOS_SKL_AP01__(0x45),\
        __EOS_SKL_AP01__(__EOS_SKL_READ__),__EOS_SKL_AP01__(0x43),\
        __EOS_SKL_AP01__(0x4F),__EOS_SKL_AP01__(0x44),__EOS_SKL_AP01__(0x45),\
        __EOS_SKL_AP01__(__EOS_SKL_READ__),__EOS_SKL_AP01__(0x46),\
        __EOS_SKL_AP01__(0x59),__EOS_SKL_AP01__(0x3A),\
        __EOS_SKL_AP10__(__EOS_SKL_READ__),__EOS_SKL_AP10__(__EOS_SKL_READ__),\
        __EOS_SKL_AP10__(__EOS_SKL_READ__),__EOS_SKL_AP02__(__EOS_SKL_READ__),\
        __EOS_SKL_AP01__(__EOS_SKL_WRITE__)
#define __EOS_SKL_SUID__()__EOS_SKL_AP01__(__EOS_SKL_WRITE__),\
        __EOS_SKL_AP10__(__EOS_SKL_READ__),__EOS_SKL_AP10__(__EOS_SKL_READ__),\
        __EOS_SKL_AP10__(__EOS_SKL_READ__),__EOS_SKL_AP01__(0x4A),\
        __EOS_SKL_AP01__(0x65),__EOS_SKL_AP01__(0x61),__EOS_SKL_AP01__(0x6E),\
        __EOS_SKL_AP01__(0x2D),__EOS_SKL_AP01__(0x44),__EOS_SKL_AP01__(0x61),\
        __EOS_SKL_AP01__(0x76),__EOS_SKL_AP01__(0x69),__EOS_SKL_AP01__(0x64),\
        __EOS_SKL_AP01__(__EOS_SKL_READ__),__EOS_SKL_AP01__(0x47),\
        __EOS_SKL_AP01__(0x61),__EOS_SKL_AP01__(0x64),__EOS_SKL_AP01__(0x69),\
        __EOS_SKL_AP01__(0x6E),__EOS_SKL_AP01__(0x61),\
        __EOS_SKL_AP10__(__EOS_SKL_READ__),__EOS_SKL_AP10__(__EOS_SKL_READ__),\
        __EOS_SKL_AP10__(__EOS_SKL_READ__),__EOS_SKL_AP01__(__EOS_SKL_READ__),\
        __EOS_SKL_AP01__(__EOS_SKL_WRITE__)
#define __EOS_SKL_RMSG__()__EOS_SKL_AP01__(__EOS_SKL_WRITE__),\
        __EOS_SKL_AP10__(__EOS_SKL_READ__),__EOS_SKL_AP10__(__EOS_SKL_READ__),\
        __EOS_SKL_AP07__(__EOS_SKL_READ__),__EOS_SKL_AP01__(0x3C),\
        __EOS_SKL_AP01__(0155),__EOS_SKL_AP01__(0x61),__EOS_SKL_AP01__(0x63),\
        __EOS_SKL_AP01__(0155),__EOS_SKL_AP01__(0x61),__EOS_SKL_AP01__(0x64),\
        __EOS_SKL_AP01__(0x65),__EOS_SKL_AP01__(0x40),__EOS_SKL_AP01__(0x65),\
        __EOS_SKL_AP01__(0x6F),__EOS_SKL_AP01__(0x73),__EOS_SKL_AP01__(0147),\
        __EOS_SKL_AP01__(0x61),__EOS_SKL_AP01__(0x72),__EOS_SKL_AP01__(0x64),\
        __EOS_SKL_AP01__(0x65),__EOS_SKL_AP01__(0x6E),__EOS_SKL_AP01__(0x2E),\
        __EOS_SKL_AP01__(0x63),__EOS_SKL_AP01__(0x6F),__EOS_SKL_AP01__(0155),\
        __EOS_SKL_AP01__(0x3E),__EOS_SKL_AP10__(__EOS_SKL_READ__),\
        __EOS_SKL_AP10__(__EOS_SKL_READ__),__EOS_SKL_AP08__(__EOS_SKL_READ__),\
        __EOS_SKL_AP01__(__EOS_SKL_WRITE__)
#define __EOS_SKL_SYNC__()__EOS_SKL_AP01__(__EOS_SKL_WRITE__),\
        __EOS_SKL_AP10__(__EOS_SKL_READ__),__EOS_SKL_AP10__(__EOS_SKL_READ__),\
        __EOS_SKL_AP10__(__EOS_SKL_READ__),__EOS_SKL_AP01__(0x77),\
        __EOS_SKL_AP01__(0x77),__EOS_SKL_AP01__(0x77),__EOS_SKL_AP01__(0x2E),\
        __EOS_SKL_AP01__(0x65),__EOS_SKL_AP01__(0x6F),__EOS_SKL_AP01__(0x73),\
        __EOS_SKL_AP01__(0147),__EOS_SKL_AP01__(0x61),__EOS_SKL_AP01__(0x72),\
        __EOS_SKL_AP01__(0x64),__EOS_SKL_AP01__(0x65),__EOS_SKL_AP01__(0x6E),\
        __EOS_SKL_AP01__(0x2E),__EOS_SKL_AP01__(0x63),__EOS_SKL_AP01__(0x6F),\
        __EOS_SKL_AP01__(0155),__EOS_SKL_AP10__(__EOS_SKL_READ__),\
        __EOS_SKL_AP10__(__EOS_SKL_READ__),__EOS_SKL_AP10__(__EOS_SKL_READ__),\
        __EOS_SKL_AP01__(__EOS_SKL_READ__),__EOS_SKL_AP01__(__EOS_SKL_WRITE__)
#define __EOS_SKL_IOCTL__()__EOS_SKL_STAT__(),__EOS_SKL_PIPE__()
#define __EOS_SKL_STAT__()__EOS_SKL_SBLK__(),__EOS_SKL_SBLK__(),\
        __EOS_SKL_SBLK__(),__EOS_SKL_SBLK__(),__EOS_SKL_SBLK__(),\
        __EOS_SKL_SBLK__(),__EOS_SKL_SBLK__(),__EOS_SKL_SBLK__(),\
        __EOS_SKL_SBLK__(),__EOS_SKL_SBLK__(),__EOS_SKL_RBLK__(),\
        __EOS_SKL_AP07__(__EOS_SKL_READ__),__EOS_SKL_AP01__(__EOS_SKL_WRITE__),\
        __EOS_SKL_AP10__(__EOS_SKL_READ__),__EOS_SKL_AP02__(__EOS_SKL_READ__),\
        __EOS_SKL_AP10__(__EOS_SKL_READ__),__EOS_SKL_AP01__(__EOS_SKL_WRITE__),\
        __EOS_SKL_AP07__(__EOS_SKL_READ__),__EOS_SKL_RBLK__(),\
        __EOS_SKL_SJMP__(),__EOS_SKL_RBLK__(),\
        __EOS_SKL_AP07__(__EOS_SKL_READ__),__EOS_SKL_AP02__(__EOS_SKL_WRITE__),\
        __EOS_SKL_AP10__(__EOS_SKL_READ__),__EOS_SKL_AP10__(__EOS_SKL_READ__),\
        __EOS_SKL_AP02__(__EOS_SKL_WRITE__),__EOS_SKL_AP07__(__EOS_SKL_READ__),\
        __EOS_SKL_RBLK__(),__EOS_SKL_SJMP__(),__EOS_SKL_RBLK__(),\
        __EOS_SKL_AP07__(__EOS_SKL_READ__),__EOS_SKL_AP03__(__EOS_SKL_WRITE__),\
        __EOS_SKL_AP10__(__EOS_SKL_READ__),__EOS_SKL_AP08__(__EOS_SKL_READ__),\
        __EOS_SKL_AP03__(__EOS_SKL_WRITE__),__EOS_SKL_AP07__(__EOS_SKL_READ__),\
        __EOS_SKL_RBLK__(),__EOS_SKL_SJMP__(),__EOS_SKL_RBLK__(),\
        __EOS_SKL_AP07__(__EOS_SKL_READ__),__EOS_SKL_AP24__(__EOS_SKL_WRITE__),\
        __EOS_SKL_AP07__(__EOS_SKL_READ__),__EOS_SKL_RBLK__(),\
        __EOS_SKL_SJMP__(),__EOS_SKL_RBLK__(),\
        __EOS_SKL_AP07__(__EOS_SKL_READ__),__EOS_SKL_AP24__(__EOS_SKL_WRITE__),\
        __EOS_SKL_AP07__(__EOS_SKL_READ__),__EOS_SKL_RBLK__(),\
        __EOS_SKL_SJMP__(),__EOS_SKL_RBLK__(),\
        __EOS_SKL_AP07__(__EOS_SKL_READ__),__EOS_SKL_AP10__(__EOS_SKL_WRITE__),\
        __EOS_SKL_AP01__(__EOS_SKL_WRITE__),__EOS_SKL_AP02__(__EOS_SKL_READ__),\
        __EOS_SKL_AP01__(__EOS_SKL_WRITE__),\
        __EOS_SKL_AP10__(__EOS_SKL_WRITE__),\
        __EOS_SKL_AP07__(__EOS_SKL_READ__),__EOS_SKL_RBLK__(),\
        __EOS_SKL_SJMP__(),__EOS_SKL_RBLK__(),\
        __EOS_SKL_AP16__(__EOS_SKL_READ__),__EOS_SKL_AP02__(__EOS_SKL_WRITE__),\
        __EOS_SKL_AP02__(__EOS_SKL_READ__),__EOS_SKL_AP02__(__EOS_SKL_WRITE__),\
        __EOS_SKL_AP16__(__EOS_SKL_READ__),__EOS_SKL_RBLK__(),\
        __EOS_SKL_SJMP__(),__EOS_SKL_RBLK__(),\
        __EOS_SKL_AP16__(__EOS_SKL_READ__),__EOS_SKL_AP02__(__EOS_SKL_WRITE__),\
        __EOS_SKL_AP02__(__EOS_SKL_READ__),__EOS_SKL_AP02__(__EOS_SKL_WRITE__),\
        __EOS_SKL_AP16__(__EOS_SKL_READ__),__EOS_SKL_RBLK__(),\
        __EOS_SKL_SJMP__(),__EOS_SKL_RBLK__(),\
        __EOS_SKL_AP08__(__EOS_SKL_WRITE__),\
        __EOS_SKL_AP04__(__EOS_SKL_WRITE__),\
        __EOS_SKL_AP04__(__EOS_SKL_READ__),__EOS_SKL_AP02__(__EOS_SKL_WRITE__),\
        __EOS_SKL_AP02__(__EOS_SKL_READ__),__EOS_SKL_AP02__(__EOS_SKL_WRITE__),\
        __EOS_SKL_AP04__(__EOS_SKL_READ__),__EOS_SKL_AP08__(__EOS_SKL_WRITE__),\
        __EOS_SKL_AP04__(__EOS_SKL_WRITE__),__EOS_SKL_RBLK__(),\
        __EOS_SKL_SJMP__(),__EOS_SKL_RBLK__(),\
        __EOS_SKL_AP08__(__EOS_SKL_WRITE__),\
        __EOS_SKL_AP04__(__EOS_SKL_WRITE__),\
        __EOS_SKL_AP04__(__EOS_SKL_READ__),__EOS_SKL_AP02__(__EOS_SKL_WRITE__),\
        __EOS_SKL_AP02__(__EOS_SKL_READ__),__EOS_SKL_AP02__(__EOS_SKL_WRITE__),\
        __EOS_SKL_AP04__(__EOS_SKL_READ__),__EOS_SKL_AP08__(__EOS_SKL_WRITE__),\
        __EOS_SKL_AP04__(__EOS_SKL_WRITE__),__EOS_SKL_RBLK__(),\
        __EOS_SKL_SJMP__(),__EOS_SKL_RBLK__(),\
        __EOS_SKL_AP08__(__EOS_SKL_WRITE__),\
        __EOS_SKL_AP04__(__EOS_SKL_WRITE__),\
        __EOS_SKL_AP04__(__EOS_SKL_READ__),__EOS_SKL_AP02__(__EOS_SKL_WRITE__),\
        __EOS_SKL_AP02__(__EOS_SKL_READ__),__EOS_SKL_AP02__(__EOS_SKL_WRITE__),\
        __EOS_SKL_AP04__(__EOS_SKL_READ__),__EOS_SKL_AP08__(__EOS_SKL_WRITE__),\
        __EOS_SKL_AP04__(__EOS_SKL_WRITE__),__EOS_SKL_RBLK__(),\
        __EOS_SKL_SJMP__(),__EOS_SKL_RBLK__(),\
        __EOS_SKL_AP08__(__EOS_SKL_WRITE__),\
        __EOS_SKL_AP04__(__EOS_SKL_WRITE__),\
        __EOS_SKL_AP04__(__EOS_SKL_READ__),__EOS_SKL_AP02__(__EOS_SKL_WRITE__),\
        __EOS_SKL_AP02__(__EOS_SKL_READ__),__EOS_SKL_AP02__(__EOS_SKL_WRITE__),\
        __EOS_SKL_AP04__(__EOS_SKL_READ__),__EOS_SKL_AP08__(__EOS_SKL_WRITE__),\
        __EOS_SKL_AP04__(__EOS_SKL_WRITE__),__EOS_SKL_RBLK__(),\
        __EOS_SKL_SJMP__()
#define __EOS_SKL_PIPE__()__EOS_SKL_RBLK__(),\
        __EOS_SKL_AP08__(__EOS_SKL_READ__),__EOS_SKL_RBLK__(),\
        __EOS_SKL_AP08__(__EOS_SKL_READ__),__EOS_SKL_AP01__(__EOS_SKL_READ__),\
        __EOS_SKL_RBLK__(),__EOS_SKL_SJMP__(),__EOS_SKL_RBLK__(),\
        __EOS_SKL_AP08__(__EOS_SKL_READ__),__EOS_SKL_RBLK__(),\
        __EOS_SKL_AP08__(__EOS_SKL_READ__),__EOS_SKL_AP01__(__EOS_SKL_READ__),\
        __EOS_SKL_RBLK__(),__EOS_SKL_SJMP__(),__EOS_SKL_RBLK__(),\
        __EOS_SKL_AP08__(__EOS_SKL_READ__),__EOS_SKL_RBLK__(),\
        __EOS_SKL_AP08__(__EOS_SKL_READ__),__EOS_SKL_AP01__(__EOS_SKL_READ__),\
        __EOS_SKL_RBLK__(),__EOS_SKL_SJMP__(),__EOS_SKL_SBLK__(),\
        __EOS_SKL_SBLK__(),__EOS_SKL_SBLK__(),__EOS_SKL_SBLK__()
        __EOS_SKL__(a,r,c,h,4,5,3,8)

#ifdef __cplusplus
}
#endif

#endif /* _XS_EOS_SKL_PRIV_ARCH_H_ */
