/*******************************************************************************
 * Copyright (c) 2011, Jean-David Gadina <macmade@eosgarden.com>
 * Distributed under the Boost Software License, Version 1.0.
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (the "Software") to use, reproduce, display, distribute,
 * execute, and transmit the Software, and to prepare derivative works of the
 * Software, and to permit third-parties to whom the Software is furnished to
 * do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer,
 * must be included in all copies of the Software, in whole or in part, and
 * all derivative works of the Software, unless such copies or derivative
 * works are solely in the form of machine-executable object code generated by
 * a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 ******************************************************************************/

/* $Id$ */

/*!
 * @file        XSMemory.h
 * @brief       Memory management functions and XSAutoreleasePool class functions
 * @author      Jean-David Gadina <macmade@eosgarden.com>
 */

#ifndef _XS_MEMORY_H_
#define _XS_MEMORY_H_
#pragma once

#include "XSMacros.h"

XS_EXTERN_C_BEGIN

#include "XSTypes.h"

/*!
 * @typedef     XSAutoreleasePool
 * @brief       Opaque type for the XSAutoreleasePool objects
 */
typedef struct __XSAutoreleasePool_Struct * XSAutoreleasePool;

/*!
 * @brief       Object allocator
 * @result      The allocated object
 */
XSStatic XSObject XSAutoreleasePool_Alloc( void );

/*!
 * @brief       Initializes a new auto-release pool
 * @details     The newly created pool will be set as the active one, meaning
 *              objects auto-released after the pool creation will be placed
 *              inside it.
 * @result      The new auto-release pool object
 */
XSObject XSAutoreleasePool_Init( XSObject xsThis );

/*!
 * @brief       Removes objects from the current auto-release pool, sending the a release message.
 * @result      void
 */
XSStatic void XSAutoreleasePool_Drain( void );

/*!
 * @def         XSAlloc
 * @brief       Allocates memory
 * descriton    Returned pointer will have to be passed to the XSRelease
 *              function in order to be free.
 * @param       ...     Reserved for internal runtime use
 * @result      A pointer to the allocated memory
 */
#define XSAlloc( ... ) XSAllocWithInfos( __FILE__, __LINE__, __func__, __VA_ARGS__ )

/*!
 * @brief       Allocates memory
 * description  This function is used for internal memory debugging. Do not
 *              call it directly. Use XSAlloc instead.
 * @param       file    The file name
 * @param       line    The line number
 * @param       func    The function name
 * @param       size    The number of bytes to allocate
 * @param       ...     Reserved for internal runtime use
 * @result      A pointer to the allocated memory
 */
void * XSAllocWithInfos( const char * file, int line, const char * func, size_t size, ... );

/*!
 * @def         XSRealloc
 * @brief       Reallocates memory
 * @param       ptr     The pointer to reallocate
 * @param       size    The new size in bytes
 * @result      The new pointer to the reallocated memory
 */
#define XSRealloc( ptr, size ) XSReallocWithInfos( __FILE__, __LINE__, __func__, ptr, size )

/*!
 * @brief       Reallocates memory
 * description  This function is used for internal memory debugging. Do not
 *              call it directly. Use XSRealloc instead.
 * @param       file    The file name
 * @param       line    The line number
 * @param       func    The function name
 * @param       ptr     The pointer to reallocate
 * @param       size    The new size in bytes
 * @result      The new pointer to the reallocated memory
 */
void * XSReallocWithInfos( const char * file, int line, const char * func, void * ptr, size_t size );

/*!
 * @brief       Retains a memory pointer, preventing it to be freed
 * @details     When retaining an object, the internal retain count is
 *              incremented. It means you own an object that you retain, and
 *              that you are responsible to release it using XSRelease.
 * @param       ptr     The pointer to retain
 * @result      The pointer passed, to allow function chaining
 */
void * XSRetain( void * ptr );

/*!
 * @def         XSRelease
 * @brief       Releases a memory pointer
 * @details     When releasing an object, the internal retain count is
 *              decremented. When it reaches 0, the pointer will be
 *              automatically freed.
 * @param       ptr     The pointer to release
 * @result      The pointer passed, to allow function chaining
 */
#define XSRelease( ptr ) XSReleaseWithInfos( __FILE__, __LINE__, __func__, ptr )

/*!
 * @brief       Releases a memory pointer
 * description  This function is used for internal memory debugging. Do not
 *              call it directly. Use XSRelease instead.
 * @param       file    The file name
 * @param       line    The line number
 * @param       func    The function name
 * @param       ptr     The pointer to release
 * @result      The pointer passed, to allow function chaining
 */
void * XSReleaseWithInfos( const char * file, int line, const char * func, void * ptr );

/*!
 * @brief       Marks a memory pointer as auto-releasable
 * @details     The pointer will be placed in the instance of the current
 *              auto-release pool, and will receive a release message the next
 *              the auto-release pool is drained.
 * @param       ptr     The memory pointer to mark as auto-releasable
 * @result      The pointer passed, to allow function chaining
 */
void * XSAutorelease( void * ptr );

/*!
 * @def         XSAutoAlloc
 * @brief       Allocates auto-releasable memory
 * @details     When using this function, the object will automatically receive
 *              a release message the next time the current auto-release pool
 *              is drained. It means you don't own it, and that you are not
 *              responsible to release it explicitely.
 * @param       size    The size to allocate in bytes
 * @result      A pointer to the allocated memory,
 */
#define XSAutoAlloc( size ) XSAutoAllocWithInfos( __FILE__, __LINE__, __func__, size )

/*!
 * @brief       Allocates auto-releasable memory
 * description  This function is used for internal memory debugging. Do not
 *              call it directly. Use XSAutoAlloc instead.
 * @param       file    The file name
 * @param       line    The line number
 * @param       func    The function name
 * @param       size    The size to allocate in bytes
 * @result      A pointer to the allocated memory,
 */
void * XSAutoAllocWithInfos( const char * file, int line, const char * func, size_t size );

/*!
 * @def         XSCopy
 * @brief       Copies a pointer
 * @details     This function executes a soft-copy. When using a structure with
 *              pointers, only the first level is copied.
 *              Note that you are responsible to release the copied pointer
 *              by using the XSRelease function.
 * @param       ptr     The pointer to copy
 * @result      The copy of the new pointer
 */
#define XSCopy( ptr ) XSCopyWithInfos( __FILE__, __LINE__, __func__, ptr )

/*!
 * @brief       Copies a pointer
 * description  This function is used for internal memory debugging. Do not
 *              call it directly. Use XSCopy instead.
 * @param       file    The file name
 * @param       line    The line number
 * @param       func    The function name
 * @param       ptr     The pointer to copy
 * @result      The copy of the new pointer
 */
void * XSCopyWithInfos( const char * file, int line, const char * func, void * ptr );

/*!
 * @brief       Compares two pointers/objects
 * @param       ptr1    The first pointer/object
 * @param       ptr2    The second pointer/object
 * @result      True if the two pointers/objects are equals, otherwise false
 */
BOOL XSEquals( void * ptr1, void * ptr2 );

/*!
 * @brief       Hashes a pointer/object
 * @param       ptr     The pointer/object to hash
 * @result      The hash of the pointer/object
 */
const char * XSHash( void * ptr );

/*!
 * @brief       Gets the retain count for a pointer
 * @param       ptr     The pointer
 * @result      The retain count
 */
XSUInteger XSGetRetainCount( void * ptr );

/*!
 * @brief       Gets the number of memory allocations
 * @result      The number of memory allocations
 */
size_t XSGetAllocationCount( void );

XS_EXTERN_C_END

#endif /* _XS_MEMORY_H_ */
