/*******************************************************************************
 * Copyright (c) 2011, Jean-David Gadina <macmade@eosgarden.com>
 * Distributed under the Boost Software License, Version 1.0.
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (the "Software") to use, reproduce, display, distribute,
 * execute, and transmit the Software, and to prepare derivative works of the
 * Software, and to permit third-parties to whom the Software is furnished to
 * do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer,
 * must be included in all copies of the Software, in whole or in part, and
 * all derivative works of the Software, unless such copies or derivative
 * works are solely in the form of machine-executable object code generated by
 * a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 ******************************************************************************/
 
/* $Id$ */

/*!
 * @file        XSNotification.h
 * @brief       XSNotification class functions
 * @author      Jean-David Gadina <macmade@eosgarden.com>
 */

#ifndef _XS_NOTIFIATION_H_
#define _XS_NOTIFIATION_H_
#pragma once

#include "XSMacros.h"

XS_EXTERN_C_BEGIN

/*!
 * @typedef     XSNotification
 * @brief       Opaque type for the XSNotification objects
 */
typedef struct __XSNotification * XSNotification;

/*!
 * @brief       Object allocator
 * @result      The allocated object
 */
XSStatic XSObject XSNotification_Alloc( void );

/*!
 * @brief       Creates a notification object
 * @param       xsThis  The notification object
 * @result      The notification object
 */
XSObject XSNotification_Init( XSObject xsThis );

/*!
 * @brief       Gets the notification's represented object
 * @param       xsThis  The notification object
 * @result      The notification's represented object
 */
XSObject XSNotification_GetObject( XSNotification xsThis );

/*!
 * @brief       Sets the notification's represented object
 * @param       xsThis  The notification object
 * @param       object  The notification's represented object
 * @result      void
 */
void XSNotification_SetObject( XSNotification xsThis, XSObject object );

/*!
 * @brief       Gets the notification name
 * @param       xsThis  The notification object
 * @result      The notification name
 */
XSString XSNotification_GetName( XSNotification xsThis );

/*!
 * @brief       Sets the notification name
 * @param       xsThis  The notification object
 * @param       name    The notification name
 * @result      void
 */
void XSNotification_SetName( XSNotification xsThis, XSString name );

XS_EXTERN_C_END

#endif /* _XS_NOTIFIATION_CENTER_H_ */
