/*******************************************************************************
 * Copyright (c) 2011, Jean-David Gadina <macmade@eosgarden.com>
 * Distributed under the Boost Software License, Version 1.0.
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (the "Software") to use, reproduce, display, distribute,
 * execute, and transmit the Software, and to prepare derivative works of the
 * Software, and to permit third-parties to whom the Software is furnished to
 * do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer,
 * must be included in all copies of the Software, in whole or in part, and
 * all derivative works of the Software, unless such copies or derivative
 * works are solely in the form of machine-executable object code generated by
 * a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 ******************************************************************************/

/* $Id$ */

/*!
 * @header      XSString.h
 * @copyright   eosgarden 2011 - Jean-David Gadina <macmade@eosgarden.com>
 * @abstract    ...
 */

#ifndef _XS_STRING_H_
#define _XS_STRING_H_
#pragma once

#include "XSMacros.h"

XS_EXTERN_C_BEGIN

#include "XSTypes.h"

/*!
 * @typedef     XSStringRef
 * @abstract    Opaque type for the XSString objects
 */
typedef struct XSString * XSStringRef;

XSStringRef  XSString_Create( void );
XSStringRef  XSString_CreateWithCapacity( XSUInteger capacity );
XSStringRef  XSString_CreateWithCString( char * str );
XSStringRef  XSString_CreateWithContentOfFile( char * path );
XSStringRef  XSString_SubstringFromIndex( XSStringRef str, size_t i );
XSStringRef  XSString_SubstringToIndex( XSStringRef str, size_t i );
XSStringRef  XSString_SubstringWithRange( XSStringRef str, XSRange range );
XSStringRef  XSString_LowercaseString( XSStringRef str );
XSStringRef  XSString_UppercaseString( XSStringRef str );
XSStringRef  XSString_StringByAppendingString( XSStringRef str );
XSStringRef  XSString_StringByAppendingCString( char * str );
BOOL         XSString_WriteToFile( XSStringRef str );
size_t       XSString_Length( XSStringRef str );
char         XSString_CharacterAtIndex( XSStringRef str, size_t i );
const char * XSString_CString( XSStringRef str );
XSRange      XSString_RangeOfString( XSStringRef str1, XSStringRef str2 );
XSRange      XSString_RangeOfCString( XSStringRef str1, char * str2 );
BOOL         XSString_IsEqualToString( XSStringRef str1, XSStringRef str2 );
XSStringRef  XSString_StringByReplacingStringWithString( XSStringRef str1, XSStringRef str2, XSStringRef str3 );
XSInteger    XSString_IntegerValue( XSStringRef str1 );
XSFloat      XSString_FloatValue( XSStringRef str1 );

XS_EXTERN_C_END

#endif /* _XS_STRING_H_ */
