/*******************************************************************************
 * Copyright (c) 2011, Jean-David Gadina <macmade@eosgarden.com>
 * Distributed under the Boost Software License, Version 1.0.
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (the "Software") to use, reproduce, display, distribute,
 * execute, and transmit the Software, and to prepare derivative works of the
 * Software, and to permit third-parties to whom the Software is furnished to
 * do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer,
 * must be included in all copies of the Software, in whole or in part, and
 * all derivative works of the Software, unless such copies or derivative
 * works are solely in the form of machine-executable object code generated by
 * a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 ******************************************************************************/
 
/* $Id$ */

/*!
 * @file        XSTimer.h
 * @brief       XSTimer class functions
 * @author      Jean-David Gadina <macmade@eosgarden.com>
 */

#ifndef _XS_TIMER_H_
#define _XS_TIMER_H_
#pragma once

#include "XSMacros.h"

XS_EXTERN_C_BEGIN

/*!
 * @typedef     XSTimer
 * @brief       Opaque type for the XSTree objects
 */
typedef struct __XSTimer_Struct * XSTimer;

/*!
 * @brief       Object allocator
 * @result      The allocated object
 */
XSStatic XSObject XSTimer_Alloc( void );

/*!
 * @brief       Creates a timer object scheduled to run at a specific time
 * @param       xsThis          The timer object
 * @param       func            A pointer to to function to call when the timer fires
 * @param       milliseconds    The timer interval, in milliseconds
 * @result      The timer object
 */
XSObject XSTimer_Init( XSTimer xsThis, void ( * func )( XSTimer timer ), XSUInteger milliseconds );

/*!
 * @brief       Runs a specific timer once, after its time interval has been reached
 * @param       xsThis  The timer object
 * @result      void
 */
void XSTimer_RunOnce( XSTimer xsThis );

/*!
 * @brief       Runs a specific timer every time its time interval has been reached
 * @param       xsThis  The timer object
 * @result      void
 */
void XSTimer_RunAndRepeat( XSTimer xsThis );

/*!
 * @brief       Invalidates a timer scheduled to repeat
 * @param       xsThis  The timer object
 * @result      void
 */
void XSTimer_Invalidate( XSTimer xsThis );

/*!
 * @brief       Checks whether a timer is valid or not
 * @param       xsThis  The timer object
 * @result      True if the timer is valid, otherwise false
 */
BOOL XSTimer_IsValid( XSTimer xsThis );

XS_EXTERN_C_END

#endif /* _XS_TIMER_H_ */
