/*******************************************************************************
 * Copyright (c) 2011, Jean-David Gadina <macmade@eosgarden.com>
 * Distributed under the Boost Software License, Version 1.0.
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (the "Software") to use, reproduce, display, distribute,
 * execute, and transmit the Software, and to prepare derivative works of the
 * Software, and to permit third-parties to whom the Software is furnished to
 * do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer,
 * must be included in all copies of the Software, in whole or in part, and
 * all derivative works of the Software, unless such copies or derivative
 * works are solely in the form of machine-executable object code generated by
 * a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 ******************************************************************************/
 
/* $Id$ */

/*!
 * @header      __XSArray.h
 * @copyright   eosgarden 2011 - Jean-David Gadina <macmade@eosgarden.com>
 * @abstract    Private XSColor class definitions
 */

#ifndef ___XS_COLOR_H_
#define ___XS_COLOR_H_
#pragma once

#include "../XSMacros.h"

XS_EXTERN_C_BEGIN

#include "XS.h"

/*!
 * @typdef      __XSColor
 * @abastract   XSColor class
 * @field       __class     Runtime class
 */
typedef struct __XSColor_Struct
{
    XSRuntimeClass __class;
    XSFloat        red;
    XSFloat        green;
    XSFloat        blue;
    XSFloat        hue;
    XSFloat        saturation;
    XSFloat        value;
    XSFloat        luminance;
    XSFloat        alpha;
}
__XSColor;

/*!
 * @function    __XSColor_Initialize
 * @abstract    Runtime initialization
 * @result      void
 */
void __XSColor_Initialize( void );

/*!
 * @function    __XSColor_RGBToHSL
 * @abstract    Converts the RGB components to HSV
 * @param       color   The color object
 * @result      void
 */
void __XSColor_RGBToHSL( __XSColor * color );

/*!
 * @function    __XSColor_RGBToHSV
 * @abstract    Converts the RGB components to HSL
 * @param       color   The color object
 * @result      void
 */
void __XSColor_RGBToHSV( __XSColor * color );

/*!
 * @function    __XSColor_HSVToRGB
 * @abstract    Converts the HSV components to RGB
 * @param       color   The color object
 * @result      void
 */
void __XSColor_HSVToRGB( __XSColor * color );

/*!
 * @function    __XSColor_HSVToHSL
 * @abstract    Converts the HSV components to HSL
 * @param       color   The color object
 * @result      void
 */
void __XSColor_HSVToHSL( __XSColor * color );

/*!
 * @function    __XSColor_HSLToRGB
 * @abstract    Converts the HSL components to RGB
 * @param       color   The color object
 * @result      void
 */
void __XSColor_HSLToRGB( __XSColor * color );

/*!
 * @function    __XSColor_HSLToHSV
 * @abstract    Converts the HSL components to HSV
 * @param       color   The color object
 * @result      void
 */
void __XSColor_HSLToHSV( __XSColor * color );

XS_EXTERN_C_END

#endif /* ___XS_COLOR_H_ */
