/*******************************************************************************
 * Copyright (c) 2011, Jean-David Gadina <macmade@eosgarden.com>
 * Distributed under the Boost Software License, Version 1.0.
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (the "Software") to use, reproduce, display, distribute,
 * execute, and transmit the Software, and to prepare derivative works of the
 * Software, and to permit third-parties to whom the Software is furnished to
 * do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer,
 * must be included in all copies of the Software, in whole or in part, and
 * all derivative works of the Software, unless such copies or derivative
 * works are solely in the form of machine-executable object code generated by
 * a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 ******************************************************************************/

/* $Id$ */

/*!
 * @file        std-math.h
 * @brief       Mathematical macros
 * @author      Jean-David Gadina <macmade@eosgarden.com>
 */

#ifndef _XS_STD_MATH_
#define _XS_STD_MATH_
#pragma once

#ifdef __cplusplus
extern "C" {
#endif

#ifndef M_PI
    
    /*!
     * @def         M_PI
     * @brief       Pi (π) constant
     */
    #define M_PI        3.1415926535897932384626433832795
    
#endif

#ifndef LOG2
    
    /*!
     * @def         __LOG2
     * @brief       Constant for the binary logarithm macro
     */
    #define __LOG2      0.301029995663981f
    
    /*!
     * @def         LOG2
     * @brief       Binary logarithm
     * @param       x   The value
     */
    #define LOG2( x )   ( log10( x ) / __LOG2 )
    
#endif

#ifndef MAX
    
    /*!
     * @def         MAX
     * @brief       Get the max of two values
     * @param       a   The first value
     * @param       b   The second value
     */
    #define MAX( a, b ) ( ( ( a ) > ( b ) ) ? a : b )
    
#endif

#ifndef MIN
    
    /*!
     * @def         MIN
     * @brief       Get the min of two values
     * @param       a   The first value
     * @param       b   The second value
     */
    #define MIN( a, b ) ( ( ( a ) < ( b ) ) ? a : b )
    
#endif

#ifndef ABS
    
    /*!
     * @def         ABS
     * @brief       Absolute value
     * @param       a   The value
     */
    #define ABS( a ) ( ( a ) < 0 ? ( -( a ) ) : ( a ) )
    
#endif

#ifdef __cplusplus
}
#endif

#endif /* _XS_STD_MATH_ */
