/*******************************************************************************
 * Copyright (c) 2011, Jean-David Gadina - www.xs-labs.com
 * Distributed under the Boost Software License, Version 1.0.
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (the "Software") to use, reproduce, display, distribute,
 * execute, and transmit the Software, and to prepare derivative works of the
 * Software, and to permit third-parties to whom the Software is furnished to
 * do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer,
 * must be included in all copies of the Software, in whole or in part, and
 * all derivative works of the Software, unless such copies or derivative
 * works are solely in the form of machine-executable object code generated by
 * a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 ******************************************************************************/

/* $Id$ */

/*!
 * @file        std-ascii.h
 * @brief       ASCII control characters
 * @author      Jean-David Gadina - www.xs-labs.com
 */

#ifndef _XS_STD_ASCII_H_
#define _XS_STD_ASCII_H_
#pragma once

#ifdef __cplusplus
extern "C" {
#endif

/*!
 * @def     ASCII_NUL
 * @brief   Null character
 */
#define ASCII_NUL   '\0'

/*!
 * @def     ASCII_SOH
 * @brief   Start of header
 */
#define ASCII_SOH   '\1'

/*!
 * @def     ASCII_STX
 * @brief   Start of text
 */
#define ASCII_STX   '\2'

/*!
 * @def     ASCII_ETX
 * @brief   End of text
 */
#define ASCII_ETX   '\3'

/*!
 * @def     ASCII_EOT
 * @brief   End of transmission
 */
#define ASCII_EOT   '\4'

/*!
 * @def     ASCII_ENQ
 * @brief   Enquiery
 */
#define ASCII_ENQ   '\5'

/*!
 * @def     ASCII_ACK
 * @brief   Aknowledgment
 */
#define ASCII_ACK   '\6'

/*!
 * @def     ASCII_BEL
 * @brief   Bell
 */
#define ASCII_BEL   '\7'

/*!
 * @def     ASCII_BS
 * @brief   Backspace
 */
#define ASCII_BS    '\8'

/*!
 * @def     ASCII_TAB
 * @brief   Horizontal tab
 */
#define ASCII_TAB   '\9'

/*!
 * @def     ASCII_LF
 * @brief   Line feed
 */
#define ASCII_LF    '\10'

/*!
 * @def     ASCII_VT
 * @brief   Vertical tab
 */
#define ASCII_VT    '\11'

/*!
 * @def     ASCII_FF
 * @brief   Form feed
 */
#define ASCII_FF    '\12'

/*!
 * @def     ASCII_CR
 * @brief   Carriage return
 */
#define ASCII_CR    '\13'

/*!
 * @def     ASCII_SO
 * @brief   Shift out
 */
#define ASCII_SO    '\14'

/*!
 * @def     ASCII_SI
 * @brief   Shift in
 */
#define ASCII_SI    '\15'

/*!
 * @def     ASCII_DLE
 * @brief   Data link escape
 */
#define ASCII_DLE   '\16'

/*!
 * @def     ASCII_DC1
 * @brief   Device control 1 (oft. XON)
 */
#define ASCII_DC1   '\17'

/*!
 * @def     ASCII_DC2
 * @brief   Device control 2
 */
#define ASCII_DC2   '\18'

/*!
 * @def     ASCII_DC3
 * @brief   Device control 3 (oft. XOFF)
 */
#define ASCII_DC3   '\19'

/*!
 * @def     ASCII_DC4
 * @brief   Device control 4
 */
#define ASCII_DC4   '\20'

/*!
 * @def     ASCII_NAK
 * @brief   Negative acknowledgement
 */
#define ASCII_NAK   '\21'

/*!
 * @def     ASCII_SYN
 * @brief   Synchronous idle
 */
#define ASCII_SYN   '\22'

/*!
 * @def     ASCII_ETB
 * @brief   End of transmission block
 */
#define ASCII_ETB   '\23'

/*!
 * @def     ASCII_CAN
 * @brief   Cancel
 */
#define ASCII_CAN   '\24'

/*!
 * @def     ASCII_EM
 * @brief   End of medium
 */
#define ASCII_EM    '\25'

/*!
 * @def     ASCII_SUB
 * @brief   Substitute
 */
#define ASCII_SUB   '\26'

/*!
 * @def     ASCII_ESC
 * @brief   Escape
 */
#define ASCII_ESC   '\27'

/*!
 * @def     ASCII_FS
 * @brief   File separator
 */
#define ASCII_FS    '\28'

/*!
 * @def     ASCII_GS
 * @brief   Group separator
 */
#define ASCII_GS    '\29'

/*!
 * @def     ASCII_RS
 * @brief   Record separator
 */
#define ASCII_RS    '\30'

/*!
 * @def     ASCII_US
 * @brief   Unit separator
 */
#define ASCII_US    '\31'

#ifdef __cplusplus
}
#endif

#endif /* _XS_STD_ASCII_H_ */
