/*******************************************************************************
 * Copyright (c) 2011, Jean-David Gadina <macmade@eosgarden.com>
 * Distributed under the Boost Software License, Version 1.0.
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (the "Software") to use, reproduce, display, distribute,
 * execute, and transmit the Software, and to prepare derivative works of the
 * Software, and to permit third-parties to whom the Software is furnished to
 * do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer,
 * must be included in all copies of the Software, in whole or in part, and
 * all derivative works of the Software, unless such copies or derivative
 * works are solely in the form of machine-executable object code generated by
 * a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 ******************************************************************************/
 
/* $Id$ */

/*!
 * @file        win32-stat.h
 * @brief       Stat functions for windows
 * @author      Jean-David Gadina <macmade@eosgarden.com>
 */

#ifndef _XS_WIN32_STAT_H_
#define _XS_WIN32_STAT_H_
#pragma once

#ifdef __cplusplus
extern "C" {
#endif

/*!
 * @def         S_IFMT
 * @brief       Type of file
 */
#define S_IFMT      0

/*!
 * @def         S_IFBLK
 * @brief       Block special
 */
#define S_IFBLK     0

/*!
 * @def         S_IFCHR
 * @brief       Character special
 */
#define S_IFCHR     0

/*!
 * @def         S_IFDIR
 * @brief       Directory
 */
#define S_IFDIR     0

/*!
 * @def         S_IFIFO
 * @brief       FIFO special
 */
#define S_IFIFO     0

/*!
 * @def         S_IFREG
 * @brief       Regular
 */
#define S_IFREG     0

/*!
 * @def         S_IFLNK
 * @brief       Symbolic link
 */
#define S_IFLNK     0

/*!
 * @def         S_IFSOCK
 * @brief       Socket
 */
#define S_IFSOCK    0

/*!
 * @def         S_IRWXU
 * @brief       Read, write, execute/search by owner
 */
#define S_IRWXU     0

/*!
 * @def         S_IRUSR
 * @brief       Read permission, owner
 */
#define S_IRUSR     0

/*!
 * @def         S_IRWXU
 * @brief       Write permission, owner
 */
#define S_IWUSR     0

/*!
 * @def         S_IWUSR
 * @brief       Execute/search permission, owner
 */
#define S_IXUSR     0

/*!
 * @def         S_IRWXG
 * @brief       Read, write, execute/search by group
 */
#define S_IRWXG     0

/*!
 * @def         S_IRGRP
 * @brief       Read permission, group
 */
#define S_IRGRP     0
/*!
 * @def         S_IWGRP
 * @brief       Write permission, group
 */
#define S_IWGRP     0

/*!
 * @def         S_IXGRP
 * @brief       Execute/search permission, group
 */
#define S_IXGRP     0

/*!
 * @def         S_IRWXO
 * @brief       Read, write, execute/search by others
 */
#define S_IRWXO     0

/*!
 * @def         S_IROTH
 * @brief       Read permission, others
 */
#define S_IROTH     0

/*!
 * @def         S_IRWXO
 * @brief       Write permission, others
 */
#define S_IWOTH     0

/*!
 * @def         S_IXOTH
 * @brief       Execute/search permission, others
 */
#define S_IXOTH     0

/*!
 * @def         S_ISUID
 * @brief       Set-user-ID on execution
 */
#define S_ISUID     0

/*!
 * @def         S_ISGID
 * @brief       Set-group-ID on execution
 */
#define S_ISGID     0

/*!
 * @brief       Obtains information about the named file and write it to the area pointed to by the buf argument
 * @details     Read, write, or execute permission of the named file is not
 *              required. An implementation that provides additional or
 *              alternate file access control mechanisms may, under
 *              implementation-defined conditions, cause stat() to fail.
 *              In particular, the system may deny the existence of the file
 *              specified by path.
 *              If the named file is a symbolic link, the stat() function shall
 *              continue pathname resolution using the contents of the symbolic
 *              link, and shall return information pertaining to the resulting
 *              file if the file exists.
 * @param       path    The file path
 * @param       buf     A pointer to the stat information structure
 * @result      O on success, otherwise -1.
 */
int stat( const char * path, struct stat * buf );

#ifdef __cplusplus
}
#endif

#endif /* _XS_WIN32_STAT_H_ */
