/*******************************************************************************
 * Copyright (c) 2011, Jean-David Gadina <macmade@eosgarden.com>
 * Distributed under the Boost Software License, Version 1.0.
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (the "Software") to use, reproduce, display, distribute,
 * execute, and transmit the Software, and to prepare derivative works of the
 * Software, and to permit third-parties to whom the Software is furnished to
 * do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer,
 * must be included in all copies of the Software, in whole or in part, and
 * all derivative works of the Software, unless such copies or derivative
 * works are solely in the form of machine-executable object code generated by
 * a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 ******************************************************************************/
 
/* $Id$ */

/*!
 * @file        __XSString.c
 * @brief       Private implementation for the XSString class
 * @author      Jean-David Gadina <macmade@eosgarden.com>
 */

#include "XS.h"
#include "__XSString.h"

/*!
 * @var         __XSStringClass
 * @brief       Runtime class definition
 */
static const XSClassInfos __XSStringClass =
{
    "XSString",             /* Class name */
    sizeof( __XSString ),   /* Object size */
    NULL,                   /* Constructor */
    __XSString_Destruct,    /* Destructor */
    XSString_Init,          /* Default initializer */
    __XSString_Copy,        /* Object copy */
    __XSString_ToString,    /* Object description */
    __XSString_Equals       /* Object comparison */
};

/*!
 * @var         __XSStringClassID
 * @brief       Type ID for the runtime class
 */
XSClassID __XSStringClassID;

void __XSString_Initialize( void )
{
    __XSStringClassID = XSRuntime_RegisterClass( &__XSStringClass );
    
    XSRuntime_BindMethodToClassID( __XSStringClassID, ( void ( * )( void ) )XSString_Init, "Init", "void" );
    XSRuntime_BindMethodToClassID( __XSStringClassID, ( void ( * )( void ) )XSString_InitWithCapacity, "InitWithCapacity", "void" );
    XSRuntime_BindMethodToClassID( __XSStringClassID, ( void ( * )( void ) )XSString_InitWithCString, "InitWithCString", "void" );
    XSRuntime_BindMethodToClassID( __XSStringClassID, ( void ( * )( void ) )XSString_SubstringFromIndex, "SubstringFromIndex", "void" );
    XSRuntime_BindMethodToClassID( __XSStringClassID, ( void ( * )( void ) )XSString_SubstringToIndex, "SubstringToIndex", "void" );
    XSRuntime_BindMethodToClassID( __XSStringClassID, ( void ( * )( void ) )XSString_SubstringWithRange, "SubstringWithRange", "void" );
    XSRuntime_BindMethodToClassID( __XSStringClassID, ( void ( * )( void ) )XSString_LowercaseString, "LowercaseString", "void" );
    XSRuntime_BindMethodToClassID( __XSStringClassID, ( void ( * )( void ) )XSString_UppercaseString, "UppercaseString", "void" );
    XSRuntime_BindMethodToClassID( __XSStringClassID, ( void ( * )( void ) )XSString_StringByAppendingString, "StringByAppendingString", "void" );
    XSRuntime_BindMethodToClassID( __XSStringClassID, ( void ( * )( void ) )XSString_StringByAppendingCString, "StringByAppendingCString", "void" );
    XSRuntime_BindMethodToClassID( __XSStringClassID, ( void ( * )( void ) )XSString_AppendFormat, "AppendFormat", "void" );
    XSRuntime_BindMethodToClassID( __XSStringClassID, ( void ( * )( void ) )XSString_AppendString, "AppendString", "void" );
    XSRuntime_BindMethodToClassID( __XSStringClassID, ( void ( * )( void ) )XSString_AppendCString, "AppendCString", "void" );
    XSRuntime_BindMethodToClassID( __XSStringClassID, ( void ( * )( void ) )XSString_Length, "Length", "void" );
    XSRuntime_BindMethodToClassID( __XSStringClassID, ( void ( * )( void ) )XSString_CharacterAtIndex, "CharacterAtIndex", "void" );
    XSRuntime_BindMethodToClassID( __XSStringClassID, ( void ( * )( void ) )XSString_CString, "CString", "void" );
    XSRuntime_BindMethodToClassID( __XSStringClassID, ( void ( * )( void ) )XSString_RangeOfString, "RangeOfString", "void" );
    XSRuntime_BindMethodToClassID( __XSStringClassID, ( void ( * )( void ) )XSString_IsEqualToString, "IsEqualToString", "void" );
    XSRuntime_BindMethodToClassID( __XSStringClassID, ( void ( * )( void ) )XSString_MD5Hash, "MD5Hash", "void" );
    XSRuntime_BindMethodToClassID( __XSStringClassID, ( void ( * )( void ) )XSString_SplitWithCString, "SplitWithCString", "void" );
}

void __XSString_Destruct( XSObject object )
{
    __XSString * str;
    
    str = ( __XSString * )object;
    
    XSRelease( str->str );
}

void __XSString_Copy( XSObject source, XSObject destination )
{
    __XSString * str1 = ( __XSString * )source;
    __XSString * str2 = ( __XSString * )destination;
    
    ( void )str1;
    
    str2->str = XSCopy( str1->str );
}

XSString __XSString_ToString( XSObject object )
{
    return ( XSString )object;
}

BOOL __XSString_Equals( XSObject object1, XSObject object2 )
{
    __XSString * s1;
    __XSString * s2;
    
    s1 = ( __XSString * )object1;
    s2 = ( __XSString * )object2;
    
    return ( strcmp( s1->str, s2->str ) == 0 ) ? YES : NO;
}
