/*******************************************************************************
 * Copyright (c) 2011, Jean-David Gadina <macmade@eosgarden.com>
 * Distributed under the Boost Software License, Version 1.0.
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (the "Software") to use, reproduce, display, distribute,
 * execute, and transmit the Software, and to prepare derivative works of the
 * Software, and to permit third-parties to whom the Software is furnished to
 * do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer,
 * must be included in all copies of the Software, in whole or in part, and
 * all derivative works of the Software, unless such copies or derivative
 * works are solely in the form of machine-executable object code generated by
 * a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 ******************************************************************************/
 
/* $Id$ */

/*!
 * @header      XSApplication.c
 * @copyright   eosgarden 2011 - Jean-David Gadina <macmade@eosgarden.com>
 * @abstract    ...
 */

#include "XS.h"
#include "__XSApplication.h"

static XSApplication      * __xsapp = NULL;
static XSAutoreleasePoolRef __xsarp = NULL;
static BOOL __xsapp_argv_processed  = NO;

XSApplicationRef XSApplication_Start( int argc, const char ** argv )
{
    XSRuntime_Initialize();
    
    __xsapp = __XSApplication_Alloc();
    __xsarp = XSAutoreleasePool_Create();
    
    __xsapp->argc       = argc - 1;
    __xsapp->argv       = argv + 1;
    __xsapp->executable = argv[ 0 ];
    
    return ( XSApplicationRef )__xsapp;
}

XSApplicationRef XSApplication_SharedApplication( void )
{
    return ( XSApplicationRef )__xsapp;
}

void XSApplication_RegisterArgument( XSApplicationRef app, const char * name, XSApplicationArgumentType type )
{
    XSApplication          * _app;
    XSApplicationArgumentRef arg;
    
    _app = ( XSApplication * )app;
    arg  = XSApplicationArgument_Create( name, type );
    
    if( _app->arg_count == _app->arg_alloc )
    {
        XSRealloc( _app->args, _app->arg_count + 25 );
        
        _app->arg_alloc += 25;
    }
    
    _app->args[ _app->arg_count++ ] = arg;
}

XSApplicationArgumentRef XSApplication_GetArgument( XSApplicationRef app, const char * name )
{
    XSUInteger      i;
    XSApplication * _app;
    
    _app = ( XSApplication * )app;
    
    for( i = 0; i < _app->arg_count; i++ )
    {
        if( strcmp( name, XSApplicationArgument_GetName( _app->args[ i ] ) ) == 0 )
        {
            return _app->args[ i ];
        }
    }
    
    return NULL;
}

BOOL XSApplication_HasArgument( XSApplicationRef app, const char * name )
{
    if( __xsapp_argv_processed == NO )
    {
        __XSApplication_ProcessArguments( ( XSApplication * )app );
        
        __xsapp_argv_processed = YES;
    }
    
    return XSApplication_GetArgument( app, name ) != NULL;
}

BOOL XSApplication_GetFlag( XSApplicationRef app, const char * name )
{
    XSApplicationArgumentRef arg;
    
    if( __xsapp_argv_processed == NO )
    {
        __XSApplication_ProcessArguments( ( XSApplication * )app );
        
        __xsapp_argv_processed = YES;
    }
    
    arg  = XSApplication_GetArgument( app, name );
    
    if( arg == NULL )
    {
        return NO;
    }
    
    return XSApplicationArgument_GetFlag( arg );
}

XSInteger XSApplication_GetInteger( XSApplicationRef app, const char * name )
{
    XSApplicationArgumentRef arg;
    
    if( __xsapp_argv_processed == NO )
    {
        __XSApplication_ProcessArguments( ( XSApplication * )app );
        
        __xsapp_argv_processed = YES;
    }
        
    arg  = XSApplication_GetArgument( app, name );
    
    if( arg == NULL )
    {
        return 0;
    }
    
    return XSApplicationArgument_GetIntegerValue( arg );
}

XSUInteger XSApplication_GetUnsignedInteger( XSApplicationRef app, const char * name )
{
    XSApplicationArgumentRef arg;
    
    if( __xsapp_argv_processed == NO )
    {
        __XSApplication_ProcessArguments( ( XSApplication * )app );
        
        __xsapp_argv_processed = YES;
    }
    
    arg  = XSApplication_GetArgument( app, name );
    
    if( arg == NULL )
    {
        return 0;
    }
    
    return XSApplicationArgument_GetUnsignedIntegerValue( arg );
}

XSStringRef XSApplication_GetString( XSApplicationRef app, const char * name )
{
    XSApplicationArgumentRef arg;
    
    if( __xsapp_argv_processed == NO )
    {
        __XSApplication_ProcessArguments( ( XSApplication * )app );
        
        __xsapp_argv_processed = YES;
    }
    
    arg  = XSApplication_GetArgument( app, name );
    
    if( arg == NULL )
    {
        return NULL;
    }
    
    return XSAutorelease( XSSTR( ( char * )XSApplicationArgument_GetStringValue( arg ) ) );
}

XSArrayRef XSApplication_GetUnnamedArguments( XSApplicationRef app )
{
    XSApplication * _app;
    
    _app = ( XSApplication * )app;
    
    return NULL;
}

void XSApplication_Exit( void )
{
    XSRelease( __xsarp );
    XSRelease( __xsapp );
    
    __xsarp = NULL;
    __xsapp = NULL;
    
    pthread_exit( NULL );
}