/*******************************************************************************
 * Copyright (c) 2011, Jean-David Gadina <macmade@eosgarden.com>
 * Distributed under the Boost Software License, Version 1.0.
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (the "Software") to use, reproduce, display, distribute,
 * execute, and transmit the Software, and to prepare derivative works of the
 * Software, and to permit third-parties to whom the Software is furnished to
 * do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer,
 * must be included in all copies of the Software, in whole or in part, and
 * all derivative works of the Software, unless such copies or derivative
 * works are solely in the form of machine-executable object code generated by
 * a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 ******************************************************************************/
 
/* $Id$ */

/*!
 * @header      XSApplicationArgument.c
 * @copyright   eosgarden 2011 - Jean-David Gadina <macmade@eosgarden.com>
 * @abstract    ...
 */

#include "XS.h"
#include "__XSApplicationArgument.h"

/*!
 * @function    XSApplicationArgument_Create
 * @abstract    Creates a CLI argument object
 * @param       name    The name of the CLI argument, including dashes (- or --)
 * @param       type    The type of the CLI argument
 * @result      The argument object
 */
XSApplicationArgumentRef XSApplicationArgument_Create( const char * name, XSApplicationArgumentType type, ... )
{
    va_list                 args;
    const char            * help;
    XSApplicationArgument * arg;
    
    va_start( args, type );
    
    help = va_arg( args, const char * );
    
    va_end( args );
    
    arg           = __XSApplicationArgument_Alloc();
    arg->name     = name;
    arg->type     = type;
    arg->uint_val = 0;
    arg->int_val  = 0;
    arg->str_val  = NULL;
    arg->flag_val = NO;
    arg->help     = NULL;
    
    if( help )
    {
        arg->help = help;
    }
    
    return ( XSApplicationArgumentRef )arg;
}

/*!
 * @function    XSApplicationArgument_GetName
 * @abstract    Gets the name of the CLI argument
 * @param       arg     The argument object
 * @result      The name of the argument object
 */
const char * XSApplicationArgument_GetName( XSApplicationArgumentRef arg )
{
    return ( ( XSApplicationArgument * )arg )->name;
}

/*!
 * @function    XSApplicationArgument_GetHelp
 * @abstract    Gets the help text of the CLI argument
 * @param       arg     The argument object
 * @result      The help text of the argument object
 */
const char * XSApplicationArgument_GetHelp( XSApplicationArgumentRef arg )
{
    return ( ( XSApplicationArgument * )arg )->help;
}

/*!
 * @function    XSApplicationArgument_GetType
 * @abstract    Gets the type of the CLI argument
 * @param       arg     The argument object
 * @result      The type of the argument object
 */
XSApplicationArgumentType XSApplicationArgument_GetType( XSApplicationArgumentRef arg )
{
    return ( ( XSApplicationArgument * )arg )->type;
}

/*!
 * @function    XSApplicationArgument_SetFlag
 * @abstract    Sets the flag to 'on' for the argument
 * @param       arg     The argument object
 * @result      void
 */
void XSApplicationArgument_SetFlag( XSApplicationArgumentRef arg )
{
    XSApplicationArgument * _arg;
    
    _arg           = ( XSApplicationArgument * )arg;
    _arg->flag_val = YES;
}

/*!
 * @function    XSApplicationArgument_SetIntegerValue
 * @abstract    Sets the integer value for the argument
 * @param       arg     The argument object
 * @result      void
 */
void XSApplicationArgument_SetIntegerValue( XSApplicationArgumentRef arg, XSInteger value )
{
    XSApplicationArgument * _arg;
    
    _arg          = ( XSApplicationArgument * )arg;
    _arg->int_val = value;
}

/*!
 * @function    XSApplicationArgument_SetUnsignedIntegerValue
 * @abstract    Sets the unsigned integer value for the argument
 * @param       arg     The argument object
 * @result      void
 */
void XSApplicationArgument_SetUnsignedIntegerValue( XSApplicationArgumentRef arg, XSUInteger value )
{
    XSApplicationArgument * _arg;
    
    _arg           = ( XSApplicationArgument * )arg;
    _arg->uint_val = value;
}

/*!
 * @function    XSApplicationArgument_SetStringValue
 * @abstract    Sets the string value for the argument
 * @param       arg     The argument object
 * @result      void
 */
void XSApplicationArgument_SetStringValue( XSApplicationArgumentRef arg, const char * value )
{
    XSApplicationArgument * _arg;
    
    _arg          = ( XSApplicationArgument * )arg;
    _arg->str_val = value;
}

/*!
 * @function    XSApplicationArgument_GetFlag
 * @abstract    Gets the flag state for the argument
 * @param       arg     The argument object
 * @result      A boolean value indicating if the flag is set
 */
BOOL XSApplicationArgument_GetFlag( XSApplicationArgumentRef arg )
{
    XSApplicationArgument * _arg;
    
    _arg = ( XSApplicationArgument * )arg;
    
    return _arg->flag_val;
}

/*!
 * @function    XSApplicationArgument_GetIntegerValue
 * @abstract    Gets the integer value for the argument
 * @param       arg     The argument object
 * @result      The argument's integer value
 */
XSInteger XSApplicationArgument_GetIntegerValue( XSApplicationArgumentRef arg )
{
    XSApplicationArgument * _arg;
    
    _arg = ( XSApplicationArgument * )arg;
    
    return _arg->int_val;
}

/*!
 * @function    XSApplicationArgument_GetUnsignedIntegerValue
 * @abstract    Gets the unsigned integer value for the argument
 * @param       arg     The argument object
 * @result      The argumen'ts unsigned integer value
 */
XSUInteger XSApplicationArgument_GetUnsignedIntegerValue( XSApplicationArgumentRef arg )
{
    XSApplicationArgument * _arg;
    
    _arg = ( XSApplicationArgument * )arg;
    
    return _arg->uint_val;
}

/*!
 * @function    XSApplicationArgument_GetStringValue
 * @abstract    Gets the string value for the argument
 * @param       arg     The argument object
 * @result      The argument's string value
 */
const char * XSApplicationArgument_GetStringValue( XSApplicationArgumentRef arg )
{
    XSApplicationArgument * _arg;
    
    _arg = ( XSApplicationArgument * )arg;
    
    return _arg->str_val;
}