/*******************************************************************************
 * Copyright (c) 2011, Jean-David Gadina <macmade@eosgarden.com>
 * Distributed under the Boost Software License, Version 1.0.
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (the "Software") to use, reproduce, display, distribute,
 * execute, and transmit the Software, and to prepare derivative works of the
 * Software, and to permit third-parties to whom the Software is furnished to
 * do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer,
 * must be included in all copies of the Software, in whole or in part, and
 * all derivative works of the Software, unless such copies or derivative
 * works are solely in the form of machine-executable object code generated by
 * a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 ******************************************************************************/
 
/* $Id$ */

/*!
 * @header      XSData.c
 * @copyright   eosgarden 2011 - Jean-David Gadina <macmade@eosgarden.com>
 * @abstract    ...
 */

#include "XS.h"
#include "__XSColor.h"

extern XSClassID __XSColorClassID;

XSStatic XSColor XSColor_Alloc( void )
{
    return ( XSColor )XSRuntime_CreateInstance( __XSColorClassID );
}

XSObject XSColor_Init( XSObject xsThis )
{
    return xsThis;
}

XSColor XSColor_InitWithRGB( XSColor xsThis, XSFloat r, XSFloat g, XSFloat b )
{
    return XSColor_InitWithRGBA( xsThis, r, g, b, ( XSFloat )100 );
}

XSColor XSColor_InitWithHSL( XSColor xsThis, XSFloat h, XSFloat s, XSFloat l )
{
    return XSColor_InitWithHSLA( xsThis, h, s, l, ( XSFloat )100 );
}

XSColor XSColor_InitWithHSV( XSColor xsThis, XSFloat h, XSFloat s, XSFloat v )
{
    return XSColor_InitWithHSVA( xsThis, h, s, v, ( XSFloat )100 );
}

XSColor XSColor_InitWithRGBA( XSColor xsThis, XSFloat r, XSFloat g, XSFloat b, XSFloat a )
{
    __XSColor * color;
    
    color = ( __XSColor * )xsThis;
    
    color->red   = MIN( r, 255 );
    color->green = MIN( g, 255 );
    color->blue  = MIN( b, 255 );
    color->alpha = MIN( a, 100 );
    
    __XSColor_RGBToHSL( color );
    __XSColor_RGBToHSV( color );
    
    return ( XSColor )color;
}

XSColor XSColor_InitWithHSLA( XSColor xsThis, XSFloat h, XSFloat s, XSFloat l, XSFloat a )
{
    __XSColor * color;
    
    color = ( __XSColor * )xsThis;
    
    color->hue        = MIN( h, 360 );
    color->saturation = MIN( s, 100 );
    color->luminance  = MIN( l, 100 );
    color->alpha      = MIN( a, 100 );
    
    __XSColor_HSLToRGB( color );
    __XSColor_HSLToHSV( color );
    
    return ( XSColor )color;
}

XSColor XSColor_InitWithHSVA( XSColor xsThis, XSFloat h, XSFloat s, XSFloat v, XSFloat a )
{
    __XSColor * color;
    
    color = ( __XSColor * )xsThis;
    
    color->hue        = MIN( h, 360 );
    color->saturation = MIN( s, 100 );
    color->value      = MIN( v, 100 );
    color->alpha      = MIN( a, 100 );
    
    __XSColor_HSVToRGB( color );
    __XSColor_HSVToHSL( color );
    
    return ( XSColor )color;
}

XSAutoreleased XSStatic XSColor XSColor_BlackColor( void )
{
    return XSAutorelease( XSColor_InitWithRGB( XSColor_Alloc(), ( XSFloat )0, ( XSFloat )0, ( XSFloat )0 ) );
}

XSAutoreleased XSStatic XSColor XSColor_WhiteColor( void )
{
    return XSAutorelease( XSColor_InitWithRGB( XSColor_Alloc(), ( XSFloat )255, ( XSFloat )255, ( XSFloat )255 ) );
}

XSAutoreleased XSStatic XSColor XSColor_RedColor( void )
{
    return XSAutorelease( XSColor_InitWithRGB( XSColor_Alloc(), ( XSFloat )255, ( XSFloat )0, ( XSFloat )0 ) );
}

XSAutoreleased XSStatic XSColor XSColor_GreenColor( void )
{
    return XSAutorelease( XSColor_InitWithRGB( XSColor_Alloc(), ( XSFloat )0, ( XSFloat )255, ( XSFloat )0 ) );
}

XSAutoreleased XSStatic XSColor XSColor_BlueColor( void )
{
    return XSAutorelease( XSColor_InitWithRGB( XSColor_Alloc(), ( XSFloat )0, ( XSFloat )0, ( XSFloat )255 ) );
}

XSFloat XSColor_GetRed( XSColor xsThis )
{
    return ( ( __XSColor * )xsThis )->red;
}

/*!
 * @function    XSColor_GetGreen
 * @abstract    Get the green component
 * @param       color   The color object
 * @result      The green component
 */
XSFloat XSColor_GetGreen( XSColor xsThis )
{
    return ( ( __XSColor * )xsThis )->green;
}

XSFloat XSColor_GetBlue( XSColor xsThis )
{
    return ( ( __XSColor * )xsThis )->blue;
}

XSFloat XSColor_GetHue( XSColor xsThis )
{
    return ( ( __XSColor * )xsThis )->hue;
}

XSFloat XSColor_GetSaturation( XSColor xsThis )
{
    return ( ( __XSColor * )xsThis )->saturation;
}

XSFloat XSColor_GetLuminance( XSColor xsThis )
{
    return ( ( __XSColor * )xsThis )->luminance;
}

/*!
 * @function    XSColor_GetValue
 * @abstract    Get the value component
 * @param       color   The color object
 * @result      The value component
 */
XSFloat XSColor_GetValue( XSColor xsThis )
{
    return ( ( __XSColor * )xsThis )->value;
}

XSFloat XSColor_GetAlpha( XSColor xsThis )
{
    return ( ( __XSColor * )xsThis )->alpha;
}

void XSColor_SetRed( XSColor xsThis, XSFloat v )
{
    ( ( __XSColor * )xsThis )->red = MIN( v, 255 );
    
    __XSColor_RGBToHSL( ( __XSColor * )xsThis );
    __XSColor_RGBToHSV( ( __XSColor * )xsThis );
}

void XSColor_SetGreen( XSColor xsThis, XSFloat v )
{
    ( ( __XSColor * )xsThis )->green = MIN( v, 255 );
    
    __XSColor_RGBToHSL( ( __XSColor * )xsThis );
    __XSColor_RGBToHSV( ( __XSColor * )xsThis );
}

void XSColor_SetBlue( XSColor xsThis, XSFloat v )
{
    ( ( __XSColor * )xsThis )->blue = MIN( v, 255 );
    
    __XSColor_RGBToHSL( ( __XSColor * )xsThis );
    __XSColor_RGBToHSV( ( __XSColor * )xsThis );
}

void XSColor_SetHue( XSColor xsThis, XSFloat v )
{
    ( ( __XSColor * )xsThis )->hue = MIN( v, 360 );
    
    __XSColor_HSLToRGB( ( __XSColor * )xsThis );
}

void XSColor_SetSaturation( XSColor xsThis, XSFloat v )
{
    ( ( __XSColor * )xsThis )->saturation = MIN( v, 100 );
    
    __XSColor_HSLToRGB( ( __XSColor * )xsThis );
}

void XSColor_SetLuminance( XSColor xsThis, XSFloat v )
{
    ( ( __XSColor * )xsThis )->luminance = MIN( v, 100 );
    
    __XSColor_HSLToRGB( ( __XSColor * )xsThis );
    __XSColor_HSLToHSV( ( __XSColor * )xsThis );
}

void XSColor_SetValue( XSColor xsThis, XSFloat v )
{
    ( ( __XSColor * )xsThis )->value = MIN( v, 100 );
    
    __XSColor_HSLToRGB( ( __XSColor * )xsThis );
    __XSColor_HSVToHSL( ( __XSColor * )xsThis );
}

void XSColor_SetAlpha( XSColor xsThis, XSFloat v )
{
    ( ( __XSColor * )xsThis )->alpha = MIN( v, 100 );
}