/*******************************************************************************
 * Copyright (c) 2011, Jean-David Gadina <macmade@eosgarden.com>
 * Distributed under the Boost Software License, Version 1.0.
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (the "Software") to use, reproduce, display, distribute,
 * execute, and transmit the Software, and to prepare derivative works of the
 * Software, and to permit third-parties to whom the Software is furnished to
 * do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer,
 * must be included in all copies of the Software, in whole or in part, and
 * all derivative works of the Software, unless such copies or derivative
 * works are solely in the form of machine-executable object code generated by
 * a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 ******************************************************************************/
 
/* $Id$ */

/*!
 * @file        XSMemory.c
 * @copyright   eosgarden 2011 - Jean-David Gadina <macmade@eosgarden.com>
 * @abstract    Memory management
 */

#include "XS.h"
#include "__XSMemory.h"
#include "__XSMemoryDebug.h"

extern XSClassID __XSAutoreleasePoolClassID;

static size_t __xsmemory_alloc = 0;

XSStatic XSAutoreleasePool XSAutoreleasePool_Alloc( void )
{
    return ( XSAutoreleasePool )XSRuntime_CreateInstance( __XSAutoreleasePoolClassID );
}

XSAutoreleasePool XSAutoreleasePool_Init( XSAutoreleasePool xsThis )
{
    __XSAutoreleasePool * ap;
    
    ap = ( __XSAutoreleasePool * )xsThis;
    
    if( __xsmemory_ar_pools_num == XS_MEMORY_MAX_AR_POOLS )
    {
        XSFatalError( "maximum number of auto-release pools reached: %u", XS_MEMORY_MAX_AR_POOLS );
    }
    
    if( NULL == ( ap->objects = ( void ** )XSAlloc( sizeof( void * ) * XS_MEMORY_NUM_OBJECTS ) ) )
    {
        free( ap );
        XSFatalError( "unable to allocate memory for the auto-release pool" );
    }
    
    ap->size                                         = XS_MEMORY_NUM_OBJECTS;
    ap->numObjects                                   = 0;
    __xsmemory_ar_pools[ __xsmemory_ar_pools_num++ ] = ap;
    
    return ( XSAutoreleasePool )ap;
}

XSStatic void XSAutoreleasePool_Drain( void )
{
    __XSAutoreleasePool * ap;
    
    ap = __XSMemory_GetCurrentAutoreleasePool();
    
    __XSMemory_AutoreleasePoolDrain( ap );
}

void * XSAllocWithInfos( const char * file, int line, const char * func, size_t size, ... )
{
    static size_t              allocID = 0;
    va_list                    args;
    __XSMemoryObject         * o;
    char                     * ptr;
    XSClassID                  classID;
    const XSClassInfos const * cls;
    
    ( void )file;
    ( void )line;
    ( void )func;
    
    va_start( args, size );
    
    classID = va_arg( args, XSClassID );
    
    va_end( args );
    
    o = calloc( sizeof( __XSMemoryObject ) + size, 1 );
    
    if( o == NULL )
    {
        return NULL;
    }
    
    if( classID > 0 && XSRuntime_GetClassForClassID( classID ) != NULL )
    {
        o->classID = classID;
    }
    else
    {
        classID = 0;
    }
    
    o->retainCount = 1;
    o->allocID     = allocID++;
    o->size        = size;
    
    ptr     =  ( char * )o;
    ptr    += ( sizeof( __XSMemoryObject ) );
    o->data = ptr;
    
    if( classID > 0 )
    {
        cls = XSRuntime_GetClassForClassID( o->classID );
        
        if( cls->construct != NULL )
        {
            cls->construct( ptr );
        }
    }
    
    XSHash( ptr );
    
    __xsmemory_alloc++;
    
    __XSMemoryDebug_NewRecord( o, file, line, func );
    
    return ptr;
}

void * XSReallocWithInfos( const char * file, int line, const char * func, void * ptr, size_t size )
{
    __XSMemoryObject * o1;
    __XSMemoryObject * o2;
    void             * data;
    
    ( void )file;
    ( void )line;
    ( void )func;
    
    if( ptr == NULL )
    {
        return NULL;
    }
    
    o1    = __XSMemory_GetMemoryObject( ptr );
    o2    = o1;
    data = realloc( o2, size + sizeof( __XSMemoryObject ) );
    
    if( data == NULL )
    {
        return NULL;
    }
    
    o2->data = data;
    o2->size = size;
    
    __XSMemoryDebug_UpdateRecord( o1, o2, file, line, func );
    
    return o2->data;
}

void * XSRetain( void * ptr )
{
    __XSMemoryObject * o;
    
    if( ptr == NULL )
    {
        return NULL;
    }
    
    o = __XSMemory_GetMemoryObject( ptr );
    
    o->retainCount++;
    
    return ptr;
}

void * XSReleaseWithInfos( const char * file, int line, const char * func, void * ptr )
{
    __XSMemoryObject         * o;
    const XSClassInfos const * cls;
    
    ( void )file;
    ( void )line;
    ( void )func;
    
    if( ptr == NULL )
    {
        return NULL;
    }
    
    o = __XSMemory_GetMemoryObject( ptr );
    
    o->retainCount--;
    
    if( o->retainCount == 0 )
    {
        if( o->classID != 0 )
        {
            cls = XSRuntime_GetClassForClassID( o->classID );
            
            if( cls->destruct != NULL )
            {
                cls->destruct( ptr );
            }
        }
        
        __XSMemoryDebug_FreeRecord( o, file, line, func );
        
        free( o );
        
        __xsmemory_alloc--;
        
        return NULL;
    }
    
    return ptr;
}

void * XSAutorelease( void * ptr )
{
    __XSAutoreleasePool * ap;
    
    if( ptr == NULL )
    {
        return NULL;
    }
    
    ap = __XSMemory_GetCurrentAutoreleasePool();
    
    if( ap == NULL )
    {
        XSLog( "Warning: autoreleasing object %p with no auto-release pool in place - leaking memory", ptr );
    }
    
    if( ap->numObjects == ap->size )
    {
        ap->objects = ( void ** )XSRealloc( ap->objects, sizeof( void * ) * ( ap->size + XS_MEMORY_NUM_OBJECTS ) );
        
        if( ap->objects == NULL )
        {
            XSFatalError( "unable to allocate memory for the auto-release pool" );
        }
        
        ap->size += XS_MEMORY_NUM_OBJECTS;
    }
    
    ap->objects[ ap->numObjects++ ] = ptr;
    
    return ptr;
}

void * XSAutoAllocWithInfos( const char * file, int line, const char * func, size_t size )
{
    void * ptr;
    
    ptr = XSAllocWithInfos( file, line, func, size );
    
    XSAutorelease( ptr );
    
    return ptr;
}

void * XSCopyWithInfos( const char * file, int line, const char * func, void * ptr )
{
    __XSMemoryObject         * o;
    void                     * ptr2;
    const XSClassInfos const * cls;
    
    if( ptr == NULL )
    {
        return NULL;
    }
    
    o = __XSMemory_GetMemoryObject( ptr );
    
    if( o->classID != 0 )
    {
        cls  = XSRuntime_GetClassForClassID( o->classID );
        ptr2 = XSAllocWithInfos( file, line, func, o->size, o->classID );
        
        if( ptr2 == NULL )
        {
            return NULL;
        }
        
        memcpy( ptr2, o->data, o->size );
        
        if( cls->copy != NULL )
        {
            cls->copy( ptr, ptr2 );
        }
    }
    else
    {
        ptr2 = XSAllocWithInfos( file, line, func, o->size );
        
        if( ptr2 == NULL )
        {
            return NULL;
        }
        
        memcpy( ptr2, o->data, o->size );
    }
    
    return ptr2;
}

BOOL XSEquals( void * ptr1, void * ptr2 )
{
    __XSMemoryObject         * o;
    const XSClassInfos const * cls;
    
    if( ptr1 == NULL && ptr2 == NULL )
    {
        return YES;
    }
    
    if( ptr1 == NULL || ptr2 == NULL )
    {
        return NO;
    }
    
    o = __XSMemory_GetMemoryObject( ptr1 );
    
    if( o->classID != 0 )
    {
        cls = XSRuntime_GetClassForClassID( o->classID );
        
        if( cls->equals != NULL )
        {
            return cls->equals( ptr1, ptr2 );
        }
    }
    
    return ( ptr1 == ptr2 ) ? YES : NO;
}

const char * XSHash( void * ptr )
{
    __XSMemoryObject         * o;
    const XSClassInfos const * cls;
    Str255                     size;
    
    o = __XSMemory_GetMemoryObject( ptr );
    
    if( strlen( ( char * )o->hash ) )
    {
        return ( const char * )o->hash;
    }
    
    if( o->classID != 0 )
    {
        cls = XSRuntime_GetClassForClassID( o->classID );
        
        utoa( cls->instanceSize, ( char * )size, 10 );
        strcat( ( char * )o->hash, "HASH:" );
        sprintf( ( char * )( o->hash + strlen( ( char * )o->hash ) ), "%08X", ( unsigned int )o->classID );
        strcat( ( char * )o->hash, ":" );
        strcat( ( char * )o->hash, cls->className );
        strcat( ( char * )o->hash, ":" );
        sprintf( ( char * )( o->hash + strlen( ( char * )o->hash ) ), "%08X", ( unsigned int )o->allocID );
        strcat( ( char * )o->hash, ":" );
        strcat( ( char * )o->hash, ( char * )size );
        
        return ( const char * )o->hash;
    }
    
    strcat( ( char * )o->hash, "HASH:00000000:NONE:" );
    sprintf( ( char * )( o->hash + strlen( ( char * )o->hash ) ), "%08X", ( unsigned int )o->allocID );
    utoa( o->size, ( char * )size, 10 );
    strcat( ( char * )o->hash, ":" );
    strcat( ( char * )o->hash, ( char * )size );
    
    return ( const char * )o->hash;
}

XSUInteger XSGetRetainCount( void * ptr )
{
    __XSMemoryObject * o;
    
    if( ptr == NULL )
    {
        return 0;
    }
    
    o = __XSMemory_GetMemoryObject( ptr );
    
    return o->retainCount;
}

size_t XSGetAllocationCount( void )
{
    return __xsmemory_alloc;
}