/*******************************************************************************
 * Copyright (c) 2011, Jean-David Gadina <macmade@eosgarden.com>
 * Distributed under the Boost Software License, Version 1.0.
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (the "Software") to use, reproduce, display, distribute,
 * execute, and transmit the Software, and to prepare derivative works of the
 * Software, and to permit third-parties to whom the Software is furnished to
 * do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer,
 * must be included in all copies of the Software, in whole or in part, and
 * all derivative works of the Software, unless such copies or derivative
 * works are solely in the form of machine-executable object code generated by
 * a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 ******************************************************************************/
 
/* $Id$ */

/*!
 * @file        XSNotification.c
 * @brief       Implementation for the XSNotification class
 * @author      Jean-David Gadina <macmade@eosgarden.com>
 */

#include "XS.h"
#include "__XSNotification.h"

extern XSClassID __XSNotificationClassID;

XSStatic XSObject XSNotification_Alloc( void )
{
    return ( XSObject )XSRuntime_CreateInstance( __XSNotificationClassID );
}

XSObject XSNotification_Init( XSObject xsThis )
{
    return xsThis;
}

XSObject XSNotification_GetObject( XSNotification xsThis )
{
    __XSNotification * notification;
    
    if( xsThis == NULL )
    {
        return NULL;
    }
    
    notification = ( __XSNotification * )xsThis;
    
    return notification->object;
}

void XSNotification_SetObject( XSNotification xsThis, XSObject object )
{
    __XSNotification * notification;
    
    if( xsThis == NULL )
    {
        return;
    }
    
    notification = ( __XSNotification * )xsThis;

    if( notification->object != NULL )
    {
        XSRelease( notification->object );
    }
    
    notification->object = XSRetain( object );
}

XSString XSNotification_GetName( XSNotification xsThis )
{
    __XSNotification * notification;
    
    if( xsThis == NULL )
    {
        return NULL;
    }
    
    notification = ( __XSNotification * )xsThis;
    
    return notification->name;
}

void XSNotification_SetName( XSNotification xsThis, XSString name )
{
    __XSNotification * notification;
    
    if( xsThis == NULL )
    {
        return;
    }
    
    notification = ( __XSNotification * )xsThis;

    if( notification->name != NULL )
    {
        XSRelease( notification->name );
    }
    
    notification->name = XSRetain( name );
}