/*******************************************************************************
 * Copyright (c) 2011, Jean-David Gadina <macmade@eosgarden.com>
 * Distributed under the Boost Software License, Version 1.0.
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (the "Software") to use, reproduce, display, distribute,
 * execute, and transmit the Software, and to prepare derivative works of the
 * Software, and to permit third-parties to whom the Software is furnished to
 * do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer,
 * must be included in all copies of the Software, in whole or in part, and
 * all derivative works of the Software, unless such copies or derivative
 * works are solely in the form of machine-executable object code generated by
 * a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 ******************************************************************************/
 
/* $Id$ */

/*!
 * @header      XSNumber.c
 * @copyright   eosgarden 2011 - Jean-David Gadina <macmade@eosgarden.com>
 * @abstract    ...
 */

#include "XS.h"
#include "__XSNumber.h"

extern XSClassID __XSNumberClassID;

XSStatic XSNumber XSNumber_Alloc( void )
{
    return ( XSNumber )XSRuntime_CreateInstance( __XSNumberClassID );
}

XSNumber XSNumber_InitWithBool( XSNumber xsThis, BOOL value )
{
    ( void )value;
    
    return xsThis;
}

XSNumber XSNumber_InitWithChar( XSNumber xsThis, char value )
{
    ( void )value;
    
    return xsThis;
}

XSNumber XSNumber_InitWithDouble( XSNumber xsThis, double value )
{
    ( void )value;
    
    return xsThis;
}

XSNumber XSNumber_InitWithFloat( XSNumber xsThis, float value )
{
    ( void )value;
    
    return xsThis;
}

XSNumber XSNumber_InitWithInt( XSNumber xsThis, int value )
{
    ( void )value;
    
    return xsThis;
}

XSNumber XSNumber_InitWithInteger( XSNumber xsThis, XSInteger value )
{
    ( void )value;
    
    return xsThis;
}

XSNumber XSNumber_InitWithLong( XSNumber xsThis, long value )
{
    ( void )value;
    
    return xsThis;
}

XSNumber XSNumber_InitWithLongLong( XSNumber xsThis, long long value )
{
    ( void )value;
    
    return xsThis;
}

XSNumber XSNumber_InitWithShort( XSNumber xsThis, short value )
{
    ( void )value;
    
    return xsThis;
}

XSNumber XSNumber_InitWithUnsignedChar( XSNumber xsThis, unsigned char value )
{
    ( void )value;
    
    return xsThis;
}

XSNumber XSNumber_InitWithUnsignedInt( XSNumber xsThis, unsigned int value )
{
    ( void )value;
    
    return xsThis;
}

XSNumber XSNumber_InitWithUnsignedInteger( XSNumber xsThis, XSUInteger value )
{
    ( void )value;
    
    return xsThis;
}

XSNumber XSNumber_InitWithUnsignedLong( XSNumber xsThis, unsigned long value )
{
    ( void )value;
    
    return xsThis;
}

XSNumber XSNumber_InitWithUnsignedLongLong( XSNumber xsThis, unsigned long long value )
{
    ( void )value;
    
    return xsThis;
}

XSNumber XSNumber_InitWithUnsignedShort( XSNumber xsThis, unsigned short value )
{
    ( void )value;
    
    return xsThis;
}
