/*******************************************************************************
 * Copyright (c) 2011, Jean-David Gadina <macmade@eosgarden.com>
 * Distributed under the Boost Software License, Version 1.0.
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (the "Software") to use, reproduce, display, distribute,
 * execute, and transmit the Software, and to prepare derivative works of the
 * Software, and to permit third-parties to whom the Software is furnished to
 * do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer,
 * must be included in all copies of the Software, in whole or in part, and
 * all derivative works of the Software, unless such copies or derivative
 * works are solely in the form of machine-executable object code generated by
 * a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 ******************************************************************************/
 
/* $Id$ */

/*!
 * @file        XSSort.c
 * @brief       Implementation of the sort functions
 * @author      Jean-David Gadina <macmade@eosgarden.com>
 */

#include "XS.h"
#include "__XSSort.h"

void XSSort( void * values, XSDataType type, XSUInteger size )
{
    switch( type )
    {
        case XSDataTypeChar:        __XSShellSortChar( values, size );      break;
        case XSDataTypeUChar:       __XSShellSortUChar( values, size );     break;
        case XSDataTypeShort:       __XSShellSortShort( values, size );     break;
        case XSDataTypeUShort:      __XSShellSortUShort( values, size );    break;
        case XSDataTypeInt:         __XSShellSortInt( values, size );       break;
        case XSDataTypeUInt:        __XSShellSortUInt( values, size );      break;
        case XSDataTypeLong:        __XSShellSortLong( values, size );      break;
        case XSDataTypeULong:       __XSShellSortULong( values, size );     break;
        case XSDataTypeLongLong:    __XSShellSortLongLong( values, size );  break;
        case XSDataTypeULongLong:   __XSShellSortULongLong( values, size ); break;
        case XSDataTypeFloat:       __XSShellSortFloat( values, size );     break;
        case XSDataTypeDouble:      __XSShellSortDouble( values, size );    break;
        case XSDataTypeInteger:     __XSShellSortInteger( values, size );   break;
        case XSDataTypeUInteger:    __XSShellSortUInteger( values, size );  break;
        default:                                                            break;
    }
}
