/*******************************************************************************
 * Copyright (c) 2011, Jean-David Gadina <macmade@eosgarden.com>
 * Distributed under the Boost Software License, Version 1.0.
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (the "Software") to use, reproduce, display, distribute,
 * execute, and transmit the Software, and to prepare derivative works of the
 * Software, and to permit third-parties to whom the Software is furnished to
 * do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer,
 * must be included in all copies of the Software, in whole or in part, and
 * all derivative works of the Software, unless such copies or derivative
 * works are solely in the form of machine-executable object code generated by
 * a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 ******************************************************************************/
 
/* $Id$ */

/*!
 * @header      XSURLRequest.c
 * @copyright   eosgarden 2011 - Jean-David Gadina <macmade@eosgarden.com>
 * @abstract    Implementation for the XSURLRequest class
 */

#include "XS.h"
#include "__XSURLRequest.h"

extern XSClassID __XSURLRequestClassID;

XSStatic XSObject XSURLRequest_Alloc( void )
{
    return ( XSObject )XSRuntime_CreateInstance( __XSURLRequestClassID );
}

XSObject XSURLRequest_InitWithURL( XSObject xsThis, XSURL url )
{
    __XSURLRequest * req;
    
    if( xsThis == NULL || url == NULL )
    {
        return xsThis;
    }
    
    req         = ( __XSURLRequest * )xsThis;
    req->url    = XSCopy( url );
    req->host   = XSHost_InitWithURL( XSHost_Alloc(), url );
    req->socket = XSHost_GetSocket( req->host );
    
    return xsThis;
}

XSAutoreleased XSURL XSURLRequest_GetURL( XSURLRequest xsThis )
{
    __XSURLRequest * req;
    
    if( xsThis == NULL )
    {
        return NULL;
    }
    
    req = ( __XSURLRequest * )xsThis;
    
    return req->url;
}

XSAutoreleased XSDictionary XSURLRequest_GetHTTPHeaders( XSURLRequest xsThis )
{
    __XSURLRequest * req;
    
    if( xsThis == NULL )
    {
        return NULL;
    }
    
    req = ( __XSURLRequest * )xsThis;
    
    return req->headers;
}

XSAutoreleased XSData XSURLRequest_GetRawBody( XSURLRequest xsThis )
{
    __XSURLRequest * req;
    
    if( xsThis == NULL )
    {
        return NULL;
    }
    
    req = ( __XSURLRequest * )xsThis;
    
    return req->data;
}

void XSURLRequest_Start( XSURLRequest xsThis )
{
    XSUInteger       i;
    XSUInteger       j;
    __XSURLRequest * req;
    const char     * msgFormat;
    XSString         msg;
    char           * sendMsg;
    char           * buffer;
    char           * buffer_orig;
    XSString         url;
    XSString         query;
    XSString         fragment;
    BOOL             hasHeaders;
    char           * headersEnd;
    char           * headerParts;
    XSString         headers;
    XSString         header;
    XSArray          headerArray;
    XSString         headerName;
    XSString         headerValue;
    XSArray          headersArray;
    XSInteger        length;
    
    if( xsThis == NULL )
    {
        return;
    }
    
    if( req->started == YES )
    {
        return;
    }
    
    req          = ( __XSURLRequest * )xsThis;
    req->started = YES;
    
    if( XSHost_Connect( req->host, req->socket ) == -1 )
    {
        return;
    }
    
    msgFormat = "GET %s HTTP/1.1\r\n"
                "Host: %s\r\n"
                "Connection: close\r\n"
                "\r\n";
    
    msg      = XSString_Init( XSString_Alloc() );
    url      = XSString_Init( XSString_Alloc() );
    
    query    = XSURL_GetQuery( req->url );
    fragment = XSURL_GetFragment( req->url );
    
    XSString_AppendFormat( url, ( char * )"%s", XSString_CString( XSURL_GetPath( req->url ) ) );
    
    if( query != NULL )
    {
        XSString_AppendFormat( url, ( char * )"?%s", XSString_CString( query ) );
    }
    
    if( fragment != NULL )
    {
        XSString_AppendFormat( url, ( char * )"#%s", XSString_CString( fragment ) );
    }
    
    XSString_AppendFormat( msg, ( char * )msgFormat, XSString_CString( url ), XSString_CString( XSURL_GetDomain( req->url ) ) );
    
    sendMsg     = ( char * )XSString_CString( msg );
    buffer      = XSAlloc( 17000 * sizeof( char ) );
    buffer_orig = buffer;
    
    if( send( req->socket, sendMsg, strlen( sendMsg ), 0 ) == -1 )
    {
        XSRelease( msg );
        XSRelease( buffer );
        XSHost_Disconnect( req->host, req->socket );
        
        return;
    }
    
    hasHeaders = NO;
    headers    = XSString_InitWithCapacity( XSString_Alloc(), 20000 );
    
    while( ( length = recv( req->socket, buffer, 16384, 0 ) ) > 0 )
    {
        if( hasHeaders == NO )
        {
            headersEnd = strstr( buffer, "\r\n\r\n" );
            
            if( headersEnd != NULL )
            {
                headersEnd[ 2 ] = 0;
                headersEnd[ 3 ] = 0;
                headerParts     = buffer;
                buffer          = headersEnd + 4;
                hasHeaders      = YES;
                
                XSString_AppendCString( headers, headerParts );
                XSData_AppendBytes( req->data, ( void * )buffer, length );
                
                headersArray = XSString_SplitWithCString( headers, ( char * )"\r\n" );
                
                if( XSArray_Count( headersArray ) > 0 )
                {
                    req->status = XSRetain( XSArray_ValueAtIndex( headersArray, 0 ) );
                    
                    XSArray_RemoveValueAtIndex( headersArray, 0 );
                }
                
                for( i = 0; i < XSArray_Count( headersArray ); i++ )
                {
                    header      = XSArray_ValueAtIndex( headersArray, i );
                    headerArray = XSString_SplitWithCString( header, ( char * )": " );
                    
                    if( XSArray_Count( headerArray ) < 2 )
                    {
                        continue;
                    }
                    
                    headerName  = XSArray_ValueAtIndex( headerArray, 0 );
                    headerValue = XSString_Init( XSString_Alloc() );
                    
                    XSArray_RemoveValueAtIndex( headerArray, 0 );
                    
                    for( j = 0; j < XSArray_Count( headerArray ); j++ )
                    {
                        XSString_AppendString( headerValue, XSArray_ValueAtIndex( headerArray, j ) );
                    }
                    
                    XSDictionary_SetValueForKey( req->headers, headerValue, headerName );
                    
                    XSRelease( headerValue );
                }
            }
            else
            {
                XSString_AppendCString( headers, headerParts );
            }
        }
        else
        {
            XSData_AppendBytes( req->data, ( void * )buffer, length );
        }
    }
    
    XSHost_Disconnect( req->host, req->socket );
    XSRelease( msg );
    XSRelease( url );
    XSRelease( headers );
    XSRelease( buffer_orig );
}